### ISSUE TITLE
CDP URI LDAP validation issue (commas)

### ISSUE THREAD

**Issue by bmalnersic** [chris2511/xca#100]
Trying to issue a CA certificate with LDAP URI in CDP, validation fails if URI string contains commas, e.g. 
```
Validation failed:
'URI:ldap:///test,CN=test'
error:2208E094:X509 V3 routines:X509V3_get_section:operation not defined
```
Issuance of such certificate is not possible.

If I replace commas with semicolons, validation is successful and I can issue the certificate:
```
Validation successful:
'Full Name:
  URI:ldap:///test;CN=test'
```

While some use cases with such certificates will work (e.g. certutil.exe -urlfetch -verify), in other cases I will get a failure, probably due the CRL retrial issue (e.g. certutil.exe -scinfo).

Maybe in the later case issue caused by something else (The revocation function was unable to check revocation because the revocation server was offline.), however I can use the smart card for Windows Smart Card Logon if I disable CRL verification in KDC and LSA. So I would like to eliminate issue with LDAP URI format - according to RFC4516, value pairs in LDAP URL should be separated by commas.

Maybe there is already a way to use commas in CDP (and probably AIA) URIs?

**Comment by DoraPaula** [comment]
I've the same issue here, while trying to migrate my openssl.cnf containing the following cdp section:

[ cdps ]
URI.1="http://pki.example.com/rootCA/ca.crl"
URI.2="ldap://pki.example.com/cn=crl,ou=rootCA,dc=example,dc=com?certificateRevocationList?base"

The http-URL (URL.1) validates fine using XCA, but the ldap-URL (URL.2) fails. It gets split in various parts at the commas.

**Comment by graphik55** [comment]
I am running into the exact same issue right now.

Is there any way to get around this?

May hope was to add a possible fix but my best guess is that the validation is causing the issue:
https://github.com/chris2511/xca/blob/17258633253f324d0f9bfdf4e3d65419ad5d3a88/lib/x509v3ext.cpp#L543
I am not to familiar with C++ so no good idea to experiment here.

**Comment by chris2511** [comment]
The OpenSSL documentation https://www.openssl.org/docs/manmaster/man5/x509v3_config.html has a good example:
```
crlDistributionPoints = crldp1_section

[crldp1_section]
fullname = URI:http://example.com/myca.crl
CRLissuer = dirName:issuer_sect

[issuer_sect]
C = UK
O = Organisation
CN = Some Name
```
Put this into the "Advanced Tab" (Edit mode)
