### ISSUE TITLE
Issue Building 2.1.2

### ISSUE THREAD

**Issue by apuhl** [chris2511/xca#102]
Hello.

I'm trying to build XCA 2.1.2 on my Crucnchbang (it is a Debian 9.8 64bits). I added support for 32bits architecture and installed packages indicated on INSTALL.w32 (some of them changed, mingw32 doesn't exist, then I installed mingw-w64-i686, for example).

My first question: do I need a 32bits debian running? Is there a specific version where I can build XCA?

Steps executed:

1) Install packages indicated on INSTALL.w32
2) Create directory xca-w32
3) Download source code and extract it inside xca-w32
4) Create empty file "build-libs" inside xca-w32
5) Being in xca-w32, I run script xca-2.1.2/misc/build-w32.sh

The process download and compile openssl 1.1.1 and libtool, installing them in "install" directory.

But when the XCA build is running I have issues stopping the process. I made a log file for error.

The log attached is for the command below:

`i686-w64-mingw32-g++ -I/home/estanislau/xca-w32/xca-2.1.2 -I/home/estanislau/xca-w32/qt/mingw48_32/include/QtGui -I/home/estanislau/xca-w32/qt/mingw48_32/include/QtCore -I/home/estanislau/xca-w32/qt/mingw48_32/include/QtWidgets -I/home/estanislau/xca-w32/qt/mingw48_32/include/QtSql -I/home/estanislau/xca-w32/qt/mingw48_32/include -I/home/estanislau/xca-w32/install/include -I/home/estanislau/xca-w32/xca_build -I/home/estanislau/xca-w32/xca_build/ui -I/home/estanislau/xca-w32/xca-2.1.2 -I/home/estanislau/xca-w32/xca_build -I/home/estanislau/xca-w32/xca_build/ui -Wall -g -O2 -mthreads  -mwindows -mnop-fun-dllimport -Wno-strict-aliasing -std=c++11  -c moc_MainWindow.cpp -o moc_MainWindow.o`

[moc_MainWindow.cpp.log](https://github.com/chris2511/xca/files/2906701/moc_MainWindow.cpp.log)

I don't know if the problem is my environment or some variable I need to export.

Can you help me with this process?

Thanks in advance,
Alexandre Estanislau

**Comment by vitomeuli** [comment]
I had problems building on a Linux Ubuntu 18.04 LTS.
I managed to get it working in the end, my findings is on https://askubuntu.com/questions/1143995/install-xca-2-in-ubuntu-18-04-lts/1144027

**Comment by chris2511** [comment]
Windows build has been improved and switched to 64 bit with 2.2.0
