### ISSUE TITLE
Also show sha256 digests of public keys

### ISSUE THREAD

**Issue by ralfhauser** [chris2511/xca#104]
As we noticed that in particular issuer certificates are some times changed with the same public key, but different root and life-time, we no longer use sha256 fingerprints on them, but directly pin with the public key sha256. There please also display that value

(similar to https://sourceforge.net/p/xca/feature-requests/97/)

**Comment by ralfhauser** [comment]
@Chris: does this closing mean that the feature will be implemented ?

**Comment by chris2511** [comment]
Closed by github because i committed 1bc340a which will be part of the next release:
It displays the same hash as
  `openssl pkey -pubout -outform DER < key.pem | sha256sum`
