### ISSUE TITLE
Adding multiple PKCS#11 dll libs breaks both entries after closing problem

### ISSUE THREAD

**Issue by LetItGlow** [chris2511/xca#107]
Issue is what the title says.

When adding at least two PKCS#11 dll, after saving and reopening XCA, it fails with an error message.
When going into the setting, both lines have been cat into one line, breaking the PKCS#11.

**Comment by chris2511** [comment]
I also noticed that while working on #91 and fixed it with ced0995862d90885e1fa6 for the next release.
