### ISSUE TITLE
poor documentation for use of remote databases on Windows

### ISSUE THREAD

**Issue by GeroldGruber** [chris2511/xca#108]
Hi,

I would like to have a documentation how I could use a remote database from the windows xca software.

I can use ma postgresql db remote from another Linux (xca version is always 2.1.2 for now).
On windows I copied the postgresql driver from the same qt version as the with the installation installed qsqlite driver and get the use of an remote postgres DB offered now.
I fill the form with the access data and get next "Driver not Loaded Driver not loaded", from some reason written twice in one line.
I can also not see any packets on the network between the client and the postgres machine.

So which steps should I follow to get a remote access from xca windows programm to a remote Postgres DB?

Best regards

Gerold

**Comment by chris2511** [comment]
This actually worked for me last time i tested it.
The setup.exe should install all neccessary drivers.
Probably #95 helps?

**Comment by GeroldGruber** [comment]
You mean the xca setup exe on windows should install the drivers needed to access a postgres DB?
(I read #95, but could not get the point where the mentioned dlls came from.)

**Comment by GeroldGruber** [comment]
i.e. I see the `sqldrivers\qsqlmysql.dll` in the Qt installation, but no `libmysql.dll`.
same with the equivalents for postgres.
Interrestingly enough, with only the Mingw `qsqlpsql.dll` installed (besides the `qsqlite.dll` from the xca install itself)  I get not only postgres DB connection type offered but also mysql!?

**Comment by GeroldGruber** [comment]
I guess I solved it:
A clean install an a fresh system with the installation option "include MySQL/PostgreSQL drivers" checked gave a working setup. 
All the trouble on my other system came from a messed up installation, which got even more confused from an Qt installation containing the drivers also. With my first (test) install I had no intention to use a My-/Postgre-SQL database. To keep a lean system I probably unchecked the installation of the database support files. 
So to justify my issue title ;-) : 
Maybe you want to add a line mentioning the need of this option checked on installation when someone wants to use database connections on Windows?
In this case the abovementioned dlls come with the xca windows setup, your completely right.

So a big thanks for your great work.

Best regards

Gerold
p.s. do you see a OCSP daemon show up some day?
