### ISSUE TITLE
Translation for Simplified Chinese

### ISSUE THREAD

**Issue by xczh** [chris2511/xca#110]
Hello, I'm a developer from China. I have completed the translation of some of the content in `xca.ts`. How could I view the translation effect in the GUI? I need to check whether the translation is appropriate in the context of the GUI. Sorry, I am not familiar with QT development, and I don't know how to compile the translated language files to the GUI.

Could you help me? Thanks a lot.

**Comment by chris2511** [comment]
The `lrelease` application is required to compile a .ts file to a .qm file.
You may then replace e.g the german `xca_de.qm` by your .qm file and select the german laguage in XCA. Looks like the `linguist` is not capable of compiling the .qm file.
You may send the file to me and I will compile it.

**Comment by xczh** [comment]
Is there any `lrelease` binary file for windows?

**Comment by xczh** [comment]
Well, I have found a solution. I will complete the translation as soon as possible, thank you for your help!

**Comment by xczh** [comment]
I noticed that the `xca.ts` file was updated, but the new items did not appear in the `xca_zh.ts` file at the same time. I use `Qt Linguist` to complete the translation work. How can I update `xca_zh.ts`? Thanks.

**Comment by chris2511** [comment]
"make trans" in the XCA toplevel directory updates the TS files.
It requires the QT "lupdate" and "lconvert" tools.
I usually do this some time before a release as now with:
fa4d3f1031e7467fbb016f6e86544c86ad5afdba
