### ISSUE TITLE
Private keys can be exported without providing password

### ISSUE THREAD

**Issue by magnucha** [chris2511/xca#111]
Using XCA 2.1.2, it is possible to press Alt+F4 when prompted with the password dialog. The user is then greeted with a warning saying **Using or exporting private keys will not be possible without providing the correct password**, where closing the dialog opens the vault as normal.  

While exporting private keys is indeed impossible when exporting to file, exporting to clipboard still works.

**Comment by chris2511** [comment]
> Using or exporting private keys will not be possible without providing the correct password
This is not by implementation, but conceptionally.
The keys are encrypted with the password. Without knowing the password XCA cannot decrypt the keys, even if I failed to implement it correctly.
On the contrary, every time when trying to export a private key, XCA asks for the database password.

**Comment by magnucha** [comment]
> Without knowing the password XCA cannot decrypt the keys, even if I failed to implement it correctly
This would make sense, but how am I then able to export private keys to clipboard without providing the password?

**Comment by chris2511** [comment]
> This would make sense, but how am I then able to export private keys to clipboard without providing the password?

You aren't:
- Create a new database with password
- Create new private key
- Close database
- Open database
- Right click key, select Export->Clipboard
- Select key type"PEM private" or 'PKCS#8'
- Click OK
- XCA asks for password.
- Neither clicking OK, nor Cancel nor an empty password will result in a successfully exported key.

**Comment by magnucha** [comment]
Here is what happens:

After performing steps 1-4, and pressing Alt+F4 on the password prompt I am greeted with this.
![opendb](https://user-images.githubusercontent.com/16681430/56636235-6a720500-6668-11e9-87dc-27e20e10af1d.png)

Export->Clipboard opens this dialog. Pressing OK does not open a password prompt. It just closes this dialog. I can then paste the key into a text editor.
![export](https://user-images.githubusercontent.com/16681430/56636244-72ca4000-6668-11e9-9a3d-0b006b1dc8cd.png)

I also tried sending the .xdb file to another computer (both running Ubuntu). Opening the db without a password, and using Export->Clipboard allows me to paste the key into a text editor there as well.

**Comment by magnucha** [comment]
Oh, I see what I did wrong. You're absolutely right.
