### ISSUE TITLE
TLS connection to Remote DB

### ISSUE THREAD

**Issue by tomaskir** [chris2511/xca#112]
I would like to request support for TLS connections to the remote database.
This is for security purposes when using XCA with a Remote DB in the cloud.

Not looking for client-cert auth to the DB (altho that would be useful as well), looking for TLS-secured DB connection using username/password auth.

Thanks!

**Comment by ImplicitDeny** [comment]
I am also precisely looking for such a thing. Storing encrypted database over an insecure network is not that useful.

Additionnaly, I can't find any intel on how is hashed the Key Encryption Key (KEK) before being sent over the network. Product's documentation mentions that "This (the KEK) password is never transmitted over the network to the database server un-hashed." but there is no intel on the employed hashing method, and I've not yet tried to sniff XCA's traffic to determine this.

**Comment by tomaskir** [comment]
We force using an SSH tunnel to connect to our XCA DB for now.
In MariaDB, we only allow connection from localhost (127.0.0.1) for the user that has access to XCA.

It would be better to simply have native TLS connection support in XCA so a user doesn't have to have SSH access to access the XCA DB, but for now this is a workaround we use.

**Comment by chris2511** [comment]
You may follow this documentation to TLS-encrypt the database access:

https://mariadb.com/kb/en/securing-connections-for-client-and-server/
https://www.postgresql.org/docs/10/ssl-tcp.html
https://www.postgresql.org/docs/10/libpq-ssl.html

You probably find a better suited tool than `openssl` to generate the required CA and client certificates.

**Comment by tomaskir** [comment]
This ticket was for XCA itself to use TLS to connect to the DB.
None of the mentioned article explain how to configure XCA itself to use TLS for DB connections.

**Comment by chris2511** [comment]
I wrongly assumed that after setting up TLS for the mysql/postgres library client in the config files and checking that the client also uses it, the Qt SQL framework simply also will.

But that was too straightforward. :confused:

https://forum.qt.io/post/53691

**Comment by chris2511** [comment]
Got back on this issue.
My previous statement was wrong and my first investigation correct.
It is that straightforward. I tested it heavily and it works fine. For PostgreSQL it even works perfect. TLS + CA-chain + CommonName/SAN hostname verification.
MariaDB does the TLS encryption, but no server certificate nor hostname verification.
No changes necessary in XCA.
All documented at https://www.hohnstaedt.de/xca/index.php/documentation/remote-databases
Try it out.
Further discussion for improvement of the documentation welcome here.
