### ISSUE TITLE
PKCS#12 export of wildcard certificate (*.example.domain) NOT possible

### ISSUE THREAD

**Issue by matthias-net-guru** [chris2511/xca#113]
If i do the same for a standard host certificate host.example.domain export to PKCS#12 is possible. 

If i try the wildcard certificate, PKCS#12 was not provided as possible export format.

Is this a technical limitation or my mistake or a software issue ?

**Comment by chris2511** [comment]
The PKCS#12 export contains the certificate and the private key. It is only offered as export-format if the private key is available in the database and is a software key (not a token).
The little certificate icon has a key symbol in the lower right corner and the certificate details show the key name in green.

**Comment by matthias-net-guru** [comment]
Thanks for that - that point me to the problem private key and used CSR does not fit ...

i used a new private key and a new csr and requested re-generation at global-sign.
Now it works.

Thank you very much.

XCA is a very cool tool to handle with certificates ...
