### ISSUE TITLE
Duplicate extensions erroneously shown

### ISSUE THREAD

**Issue by eabalea** [chris2511/xca#116]
When building a template with a proprietary extension using the Advanced tab, xca tells me that there's a duplicate extension, while it's wrong.

For example, using only the following:
  1.3.6.1.4.1.5606.1.1=DER:30:02:05:00
  1.3.6.1.4.1.5606.1.2=DER:30:02:05:00
raises the issue, and it tells me that 1.3.6.1.4.1.5606.1.2 is a duplicate extension.

**Comment by chris2511** [comment]
Yes, you are right, this is a bug. I will fix it.
If you register the OID in "oids.txt" with a name, adding the extensions will work as expected.
Please see
https://hohnstaedt.de/xca/index.php/documentation/objectids
for details.
