### ISSUE TITLE
SQL for Linux?

### ISSUE THREAD

**Issue by teward** [chris2511/xca#117]
Remote database support seems to be disabled by default in Linux, or perhaps the builds I'm issuing are missing dependent libraries.  Are there any details on which dependent libraries or configure arguments I have to pass in to make remote DB support work on Linux builds?

**Comment by chris2511** [comment]
You want to install either libqt5sql5-mysql or libqt5sql5-psql or perhaps both.
On non-debian based hosts, the package names may vary.
If this answer solves the issue, please close.
I will update the documentation @ https://hohnstaedt.de/xca/index.php/documentation/remote-databases

**Comment by teward** [comment]
Does this need to be available at build time, or only during runtime?  I'm assuming at build time.

**Comment by chris2511** [comment]
No. XCA will detect available plugins during startup.

**Comment by teward** [comment]
This seems to have worked, yes.  I'll be opening a bug in Debian and Ubuntu against the XCA package to update the packaging to:

(1) Update XCA to latest as it's not the latest, and 
(2) Add those two packages to the runtime dependencies, as they are otherwise missing.

Thank you for the very swift response!
