### ISSUE TITLE
PostgreSQL: Errors thrown when using PSQL

### ISSUE THREAD

**Issue by teward** [chris2511/xca#118]
Whenever attempting to write data to the PostgreSQL databases remotely (which unfortunately means using PostgreSQL 10 or other actually *supported* PostgreSQL release), the following error message is triggered:

![Screenshot from 2019-05-08 15-35-32](https://user-images.githubusercontent.com/327952/57403137-f591e580-71a6-11e9-9817-a15e26e5f4af.png)

This is generated for *any* action which would require committing information, and is also triggered even when hitting "New Certificate" or generating a new Key.

The information *is* written to the database, however this error shows up numerous times.

**TESTED INFRASTRUCTURE**:
OS: Ubuntu 18.04.2 LTS
XCA Version: 2.1.2 (source-built, using same XCA package 'template' as was in Debian - packages available at https://launchpad.net/~teward/+archive/ubuntu/xca which is a PPA)
PostgreSQL Version: 10 (remote server is Ubuntu 18.04)

**Comment by chris2511** [comment]
You may start xca with the environment variable` XCA_DEBUG=1` to get all issued SQL commands printed.
Maybe that helps to track down the issue. The error is reported by the driver.
During my tests this did not happen.

**Comment by teward** [comment]
I'm actually going to chalk this up to a temporary system weirdness.  I can't replicate the same errors anymore.  This said, I had to reboot this computer I was using for testing due to kernel updates, so maybe it was just system weirdness...
