### ISSUE TITLE
Problems with database file on a windows shared folder

### ISSUE THREAD

**Issue by vitomeuli** [chris2511/xca#121]
I built XCA 2.1.2 on a Linux Ubuntu 18.04 machine, and installed the setup exe on a Windows 10 machine. We both use the same database file, stored on a windows shared folder (SMB/CIFS mounted on the linux box).

On Windows I have no errors.
Whereas on Linux I have some errors:
* before asking for the database password it complains "database is locked Impossibile effettuare la transazione"; pressing OK it opens it anyway;
the same message pops up many times afterward (I guess once per private key, or once per certificate);
* before closing the program it complains: "cannot start a transaction within a transaction Impossibile iniziare la transazione"; pressing OK it quits anyway.

The program works anyway, but it's bothersome.

When I open the same database file stored in my home in Linux, no error.

**Comment by virtualdreams** [comment]
I have the same error. It seems, the error comes from the QT-Framework.
Btw, i don't like the automatic save. I want a save button!

**Comment by chris2511** [comment]
Maybe using  one of the supported SQL Servers is an option.
https://www.hohnstaedt.de/xca/index.php/documentation/remote-databases
