### ISSUE TITLE
Snap and Flatpak packages for XCA

### ISSUE THREAD

**Issue by 6XGate** [chris2511/xca#123]
I've been using XCA on Windows for a while and find it pretty full featured and easy enough for my needs both in professional and personal use cases. The only sore spot has been using it on Linux since most non-rolling distros don't update XCA till they go through a cycle update.

It would be more useful to have a Flatpak or Snap package (I prefer snap due to using Ubuntu) to allow installing the latest version from a download. Plus I'm sure you could publish the newest version in each package format's official store (Flathub and Snapcraft).

**Comment by chris2511** [comment]
XCA is Open Source. How about contributing and maintaining FlatPack and Snap ports yourself?

**Comment by SharkyRawr** [comment]
Hi, I created a flatpak package and would like to add it to the flathub registry if that's okay.

https://github.com/SharkyRawr/flathub/tree/io.github.chris2511.xca

**Comment by chris2511** [comment]
Hi, thanks for the work and of course you may add it to the flathub registry.

**Comment by chris2511** [comment]
https://github.com/flathub/flathub/pull/5521
