### ISSUE TITLE
Could not add X509v3 SubjectAlt of type URI containing ":" or numbers

### ISSUE THREAD

**Issue by cacamille3** [chris2511/xca#126]
Hi,

I am using the latest Release of xca (2.1.2) and it is currently not allowed to add a Subject Alternative Name of type URI that contains numbers or ":" character

**Comment by 0rbiter** [comment]
Setting ldap URIs doesn't work either

**Comment by chris2511** [comment]
For me `URI:https://example.com:443` works like a charm with 2.1.2 and 2.2.1
