### ISSUE TITLE
Unattended Installation

### ISSUE THREAD

**Issue by xenadmin** [chris2511/xca#129]
Please provide a way for unattended / silent installations. I need that for Software Deployment and OS Builds. Thank you.

![image](https://user-images.githubusercontent.com/12057348/63154800-b4b13480-c011-11e9-9d63-a4b25c993a11.png)

**Comment by chris2511** [comment]
I switched to MSI, please test the 2.2.0-pre version.
https://hohnstaedt.de/downloads/xca-2.2.0-pre.msi
