### ISSUE TITLE
help,help.I forgot password

### ISSUE THREAD

**Issue by HydeSir** [chris2511/xca#133]
I forgot the password of my database.Now, I can't export private keys from xca.What should I do?

**Comment by chris2511** [comment]
Despair.
There is no known way to recover the keys.
Any way to recover the keys is a serious security breach that will be fixed immediately.
The only way I see is to re-generate and re-distribute all certificates and keys.

**Comment by mfriedrich74** [comment]
I noticed that you do not need a password to access the private keys in the database.
The database is not encrypted and even xca shows the private keys on screen when opened without a password.

**Comment by chris2511** [comment]
You may even open the database with any SQLite database browser.
The private keys, however, are still PKCS#8 encrypted with the database password.
 https://www.hohnstaedt.de/xca-doc/database_schema.html
