### ISSUE TITLE
Groups and search?

### ISSUE THREAD

**Issue by tromlet** [chris2511/xca#134]
Hey so - 

First off, great application, you deserve absolute commendation for this, it's lovely, and it's wonderful to see this thing still in development. I'm paying off a billion debts, but only for the next few months - I will be sure and be delighted to donate to you! It's in my Google Calendar!

Secondly, it'd be really cool if we could group items _and_ search them under each of the tabs ("Private keys", "Certificate signing requests", "Certificates", etc.) - I have a couple of distinct PKIs and manage them, so it'd be nice to be able to arrange them like this. Some of these PKIs are also quite large, so search would also be pretty neat.

**Comment by chris2511** [comment]
Hi Tromlet

- There is a search bar at the bottom right.
- Almost all properties of certificates can be shown in separate columns in the certificate view.
- The certificate list can be sorted by each row.
- Grouping could be done by having one database for each PKI.

What exactly do you want to achieve that can't be done by the mechanisms above?
