### ISSUE TITLE
Export private key as PKCS#8 file (*.pk8 unencrypted)

### ISSUE THREAD

**Issue by MiJo112** [chris2511/xca#137]
In need the private key as a PKCS#8 file, but unencrypted.
How is that possible?

**Comment by chris2511** [comment]
Go to the private keys tab and select "Export->File" and select "PKCS#8" from the bottom of the drop-down menu. This is not available for public keys.

**Comment by MiJo112** [comment]
Perfect tip, I only saw the export in the tab Certificates.
