### ISSUE TITLE
continous "Date changed for"

### ISSUE THREAD

**Issue by rlucassen2** [chris2511/xca#139]
Version: 2.1.2-2, Debian Bullseye (testing), quite a lot certificates imported from "TinyCA2". When started from the command line, xca continously reports "Date changed for " entries. Even when I create a new CA and one certificate, it reports these "Date changed for" entries (but with 1 cert it does so once in a while):

Date changed for "test-root-ca" : "Expiry date" Col: 55 "2029-10-26"
Date changed for "test1.xaq.nl" : "Expiry date" Col: 55 "2020-10-26"
Date changed for "test-root-ca" : "Expiry date" Col: 55 "2029-10-26"
Date changed for "test1.xaq.nl" : "Expiry date" Col: 55 "2020-10-26"
Date changed for "test-root-ca" : "Expiry date" Col: 55 "2029-10-26"
Date changed for "test1.xaq.nl" : "Expiry date" Col: 55 "2020-10-26"
Date changed for "test-root-ca" : "Expiry date" Col: 55 "2029-10-26"
Date changed for "test1.xaq.nl" : "Expiry date" Col: 55 "2020-10-26"

XCA seems to work perfectly well btw.

Richard.

**Comment by chris2511** [comment]
This is normal debugging output.
Debugging output has been silenced and improved in the post 2.1.2 commit 7d5ecacad8a25c639fb46e442a353bce46295322
