### ISSUE TITLE
[Feature Request] Support Ed25519/Curve25519

### ISSUE THREAD

**Issue by ya-isakov** [chris2511/xca#142]
These curves are gaining more and more popular nowadays, e.g. SSH is generating keys using them. OpenSSL-1.1+ supports them, and many other libraries.

**Comment by xczh** [comment]
Indeed, I also think that this key algorithm should be supported.

**Comment by jpele-tis** [comment]
Problem persist
Error message for me 
```
L'erreur suivante s'est produite:
(7pki_evp[]:)
error:09088074:PEM routines:do_PVK_header:bad magic number

(pki_evp.cpp:355)
```

**Comment by schwindtwla** [comment]
We also want to use them for OpenVPN as replacement for RSA2048 and higher.
What does the roadmap look like?

**Comment by ya-isakov** [comment]
@chris2511 Thanks a lot! Brief testing shows that everything works properly, at least openssl is fine with generated keys/certs. Will these changes allow me to use Yubikey with ed25519 key as a CA, when OpenSC with PKCS #11 v3.0 changes will be available? If not, I'll create a ticket when OpenSC will be released.
