### ISSUE TITLE
Hotkey for import

### ISSUE THREAD

**Issue by mr-tron** [chris2511/xca#143]
I think if something like Ctrl+i opens PEM import window (and parse buffer of course) it will be cool.

**Comment by chris2511** [comment]
Hiting CTRL-V in XCA with one (or several concatenated)  PEM encoded item(s) in the clipboard should work. On linux the "middle-mouse-button" also works

**Comment by mr-tron** [comment]
Thank you! May be you can add suggestion to menu like this?
![image](https://user-images.githubusercontent.com/702560/70226758-77101d00-1762-11ea-8f5b-6bcd7d0e14df.png)
