### ISSUE TITLE
Import and Export certificate

### ISSUE THREAD

**Issue by carlosrodriguesIT** [chris2511/xca#145]
Hello,

I want to know that certificate import and export can be done with openssl commands via cli, or this is a limitation of xca?

Regards

**Comment by chris2511** [comment]
Please see: https://hohnstaedt.de/xca-doc/xca-3.html#ss3.1

Export can be done with the sqlite3 tool, combined with OpenSSL.

Import needs XCA, but you may bulk-import files with e.g. "xca -d database.xdb *.pem"
