### ISSUE TITLE
File browser unable to see Dokan-mounted filesystems on Windows until  opening files with Explorer

### ISSUE THREAD

**Issue by Karunamon** [chris2511/xca#150]
XCA version 2.1.2 (also applies on version 1.4.1), Windows 10 10.0.18362.535

I have my XCA database stored in a Keybase KBFS volume, mounted to my system using the Dokan library ([further info here](https://github.com/keybase/client/tree/master/go/kbfs/kbfsdokan)). 

For all intents and purposes, I have a K: drive on my system that points to this volume.

Trying to open the database by navigating to it using the `File -> Open DataBase` menu option doesn't show the K: drive, and trying to enter it in the location bar manually results in a "Drive K: does not exist" error. 

However, if I use Explorer to open the K: drive, navigate to the database, and open it there, then everything works as normal, AND all file browsers (example, export, dump, etc.) are able to see the K: drive until XCA is shut down.

Since there's a viable workaround, this is incredibly low priority, but hey, still technically a bug :)

**Comment by chris2511** [comment]
This is a KBFS or windows bug or something else in your setup, but not an XCA bug.
If the operating system says there is no drive K:, XCA does not question it.
How do other applications notepad, excel, etc. behave?

**Comment by Karunamon** [comment]
That's just it. All other apps on my system can see and interact with the drive normally. Only XCA treats it in this strange way.
