### ISSUE TITLE
How can we specify the Cryptographic Service Provider

### ISSUE THREAD

**Issue by chrisderham** [chris2511/xca#152]
I love this tool. It is so good, since I started using it years ago, it just does everything. However recently we hit an issue on a windows server, whereby we had to specify the Cryptographic Service Provider. I can't see how this can be done using this tool. Perhaps I just don't know the correct terminology, and it is already built into the tool. 

This article shows how to perform the action on an existing pfx - https://www.componentspace.com/Forums/1578/SHA256-and-Converting-the-Cryptographic-Service-Provider-Type. This article shows how to generate a CSR which specifies the CSP from IIS https://www.thesslstore.com/knowledgebase/ssl-generate/csr-generation-guide-for-microsoft-iis8/.

**Comment by chris2511** [comment]
> Perhaps I just don't know the correct terminology, and it is already built into the tool.

No, it is not. It is a feature request.
Actually not that complicated.

**Comment by reece00** [comment]
Temporary method: opemssl modify .12 file csp(For windows)
openssl rsa -in "%temp%\test.pem" -out "%temp%\test.key"
openssl pkcs12 -in %1 -nokeys -out "%temp%\test.crt"
openssl pkcs12 -export -in "%temp%\test.crt" -inkey "%temp%\test.key" -CSP "Microsoft Enhanced RSA and AES Cryptographic Provider" -out %1
del "%temp%\test.pem"
del "%temp%\test.key"
del "%temp%\test.crt"
Save as .bat

**Comment by Phoenixoboros** [comment]
I'm having the same issue, this feature would be cool.
