### ISSUE TITLE
new version release date

### ISSUE THREAD

**Issue by gkl1368** [chris2511/xca#154]
When version 2.2.0 will be released？

**Comment by chris2511** [comment]
soon :-)

**Comment by lkraider** [comment]
What's new for 2.2.0 ?

**Comment by chris2511** [comment]
https://github.com/chris2511/xca/blob/master/changelog

**Comment by gkl1368** [comment]
Can I download preview version now？

**Comment by chris2511** [comment]
Use the source :-)
I don't possess a valid code-signing certificate.
I could compile a windows pre version tonight, but it will be code-signed by an expired certificate.

**Comment by gkl1368** [comment]
OK. I will build it from source. Thanks.

**Comment by gkl1368** [comment]
Finished. Dark Mode UI in new version.

**Comment by gkl1368** [comment]
Why I can't choose remote database?

**Comment by chris2511** [comment]
> Finished build. Dark Mode UI in new version. Good~~

What OS are you using?
What do you mean by "Dark Mode UI"?

> Why I can't choose remote database?

https://hohnstaedt.de/xca/index.php/documentation/remote-databases
For MacOSX:` brew install qt4 --with-mysql-client --with-postgresql`

**Comment by gkl1368** [comment]
![image](https://user-images.githubusercontent.com/12904884/71956356-e9729200-3225-11ea-9fff-f648e989e2c9.png)
In MacOS  10.15, it has dark ui mode.

**Comment by gkl1368** [comment]
> > Finished build. Dark Mode UI in new version. Good~~
> 
> What OS are you using?
> What do you mean by "Dark Mode UI"?
> 
> > Why I can't choose remote database?
> 
> https://hohnstaedt.de/xca/index.php/documentation/remote-databases
> For MacOSX:` brew install qt4 --with-mysql-client --with-postgresql`

There is no option for the latest brew version.

**Comment by chris2511** [comment]
> There is no option for the latest brew version. So can't use option --with-mysql-client --with-postgresql

What a pity.

The problem is that the brew qt is missing the sqldrivers for mysql /postgresql.

I got the options from a rather old stackoverflow post
https://stackoverflow.com/questions/7579212/mysql-for-qt-on-mac
but can not test it currently. Also, I'm not that familiar with "brew".

If you find a solution, please tell me.

**Comment by gkl1368** [comment]
> > There is no option for the latest brew version. So can't use option --with-mysql-client --with-postgresql
> 
> What a pity.
> 
> The problem is that the brew qt is missing the sqldrivers for mysql /postgresql.
> 
> I got the options from a rather old stackoverflow post
> https://stackoverflow.com/questions/7579212/mysql-for-qt-on-mac
> but can not test it currently. Also, I'm not that familiar with "brew".
> 
> If you find a solution, please tell me.

Resolved.
![image](https://user-images.githubusercontent.com/12904884/72034806-00ba8980-32d1-11ea-98fc-ba853b72646d.png)

1.brew install qt mysql-client
2.Download QT and MySQL, unzip to anywhere
3. In download_qt, run configure -sql-mysql MYSQL_PREFIX=/download_mysql
4. Go to download_qt\Src/qtbase/plugins/sqldrivers/, run make sub-mysql, copy all dylib file to /usr/local/opt/qt/plugins/sqldrivers
5. Build XCA
6. copy libmysqlclient.21.dylib from mysql-client to /Applications/xca.app/Contents/Frameworks
7. Run xca.app

**Comment by gkl1368** [comment]
Build from source. Perfect~~~
![image](https://user-images.githubusercontent.com/12904884/72311159-c1b87980-36be-11ea-823c-0df43c7a0eae.png)

**Comment by chris2511** [comment]
Release 2.2.1: 55976b5d425e76e06622a191aefda47275368284 done
