### ISSUE TITLE
Similar certificate drops key usage critical flag

### ISSUE THREAD

**Issue by lkraider** [chris2511/xca#155]
By default, using the function `Transform->Similar Certificate` will create a new certificate without keeping the Key Usage `Critical` flag from the original.

Steps to reproduce:
- Create a new SSL certificate.
- Set Basic Constraint for End Entity as Critical.
- Set Key Usage for Digital Signature and Key Encipherment as Critical.
- From this certificate, select Transform->Similar Certificate.
- Take note that the Critical flag for the Key Usage is not marked, but for Basic Usage it is.

Is this by design? If so, can you provide the rationale?

Thanks for a great app!

**Comment by chris2511** [comment]
The described behavior is a bug!
Thanks for the report.
Fixed for the next release with ae94faebaffdf83a7da6a0866a54271ad8ff6fa6
