### ISSUE TITLE
Opening existing database

### ISSUE THREAD

**Issue by dryiceza** [chris2511/xca#159]
Hi,

When trying to open an existing database (not sure if database is potentially corrupt?), I get the following error:
duplicate column name: del Unable to execute statement -:0 (ALTER TABLE items ADD del SMALLINT NOT NULL DEFAULT 0)

![xca - error](https://user-images.githubusercontent.com/29375323/73408631-b0bc5a80-42b1-11ea-9855-aa492c08fc30.png)

I didn't have this issue when running on the previous version 2.1.2. 

Let me know if you need other information?

Thanks!

**Comment by jonhp** [comment]
I am having the exact same problem.

**Comment by chris2511** [comment]
Me too... :-)

**Comment by kalmufti** [comment]
Same here, I can still open the database using version 2.1.2

**Comment by dryiceza** [comment]
Fantastic resolution time on this issue! Thanks!

**Comment by jonhp** [comment]
I 2nd @dryiceza.
