### ISSUE TITLE
Mention MacPorts install option on https://www.hohnstaedt.de/xca/index.php/download

### ISSUE THREAD

**Issue by lhaeger** [chris2511/xca#160]
Please consider mentioning [MacPorts](https://www.macports.org/install.php) as an install option for xca on macOS on your download page. 
All it takes is `sudo port install xca` for a build with local SQLite-only support (as in v2.1.2 and earlier) while `sudo port install xca +RemoteSQL` installs xca including the new MySQL/MariaDB/PostgeSQL support introduced in v2.2.0.

Also, feel free to take over maintainership for this [port](https://github.com/macports/macports-ports/blob/master/security/xca/Portfile), it's just a short TCL script and you'd be just the right guy for this, I guess. :-)

**Comment by chris2511** [comment]
Done as requested.
Also added a reference to brew.
> Also, feel free to take over maintainership for this port, it's just a short TCL script and you'd be just the right guy for this, I guess. :-)

No, thanks. :-)
I already have enough to do to build the different OS releases.
At debian and other linux distros other people tha me take care of XCA for their platform. Your effort here is very welcome.

**Comment by lhaeger** [comment]
Thanks for the update, that was quick! One more thing: there's a small typo in the menu bar of your website, "collaboration" should probably get a second "l".
