### ISSUE TITLE
Feature request: show key type/size on column of Certificates tab

### ISSUE THREAD

**Issue by iddq** [chris2511/xca#163]
Feature request: show key type/size on column of Certificates tab

**Comment by iddq** [comment]
Szia Chris, köszi :)

btw I compiled it on linux and the internal templates for new certificate are missing.

**Comment by chris2511** [comment]
Szivesen :-)

The templates are searched in PREFIX (`/usr/share/xca` or `/usr/local/share/xca`)
XCA dos not look for them in the current directory, so you need to "make install".
The about dialog shows the prefix.
The debian package is installed in `/usr`, the sources use `/usr/local` as default prefix.
