### ISSUE TITLE
“xca.app” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by Nothing4You** [chris2511/xca#167]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/3694534/75092849-49c25680-557c-11ea-8d55-fb8103314bee.png">

possibly related to #97

This is happening on Catalina 10.15.3 (19D76).

```
➜  ~ brew cask info xca
xca: 2.2.1
https://hohnstaedt.de/xca/
/usr/local/Caskroom/xca/2.2.1 (18 files, 87.5KB)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/xca.rb
==> Name
XCA
==> Artifacts
xca.app (App)
```

**Comment by Nothing4You** [comment]
As hinted by @idcrook in #97 a workaround is right clicking xca.app in Finder, selecting Open and you will be shown the option to bypass this. It seems that skipping it once "fixes" it locally, the prompt does not show up on later restarts e.g. via spotlight.

**Comment by chris2511** [comment]
https://github.com/chris2511/xca/releases/download/RELEASE.2.4.0/xca-2.4.0.dmg
is signed and notified
