### ISSUE TITLE
XCA on linux spits everything to journal

### ISSUE THREAD

**Issue by fyvfy** [chris2511/xca#168]
Hi!
I use xca 2.1.2 from official arch repo. PKGBUILD [here](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/xca)

It logs everything to (systemd) journal:
```
$ journalctl -b | grep xca
Feb 17 10:25:59 localhost xca[117684]: Date changed for "MYCA OMV Server" : "Expiry date" Col: 55 "2038-07-18"
Feb 17 10:25:59 localhost xca[117684]: Date changed for "MYCA Root CA" : "Expiry date" Col: 55 "2039-07-15"
```

Imo you should not write anything about certificates to journal, even public info. Errors like "could not find library xx", or "cannot open file yy" are acceptable.

But wait, there is more!!
```
$ journalctl | grep xca | grep -i private
Feb 17 23:29:36 localhost xca[135636]: "QUERY: db_base.cpp:102 (SELECT x509super.item FROM x509super JOIN private_keys O
N x509super.pkey = private_keys.item JOIN certs ON certs.item = x509super.item WHERE certs.ca=1) - Rows selected: -1"
Feb 17 23:30:15 localhost xca[135636]: "QUERY: pki_evp.cpp:644 (INSERT INTO private_keys (item, ownPass, private) VALUES
 (?, ?, ?)[3, 0, MIIJrTBXB..deleted..WLk]) - Rows affected: 1"
```
I don't even want to check if it's really my private keys

**Comment by chris2511** [comment]
Debug log has been turned off in the current release 2.2.1
I wasn't aware that systemd logs everything it can get its hands on.
