### ISSUE TITLE
xca-portable-2.2.1 cannot change language

### ISSUE THREAD

**Issue by xczh** [chris2511/xca#170]
`xca-portable-2.2.1` cannot change language.  How to fix it?

![image](https://user-images.githubusercontent.com/12578552/75759140-0cc24500-5d70-11ea-9503-5888723c36eb.png)

**Comment by chris2511** [comment]
oh

**Comment by chris2511** [comment]
the `xca_*.qm ` files in the `i18n` folder are/should be checked.

**Comment by xczh** [comment]
I know what happened. Because the path of xca.exe contains Chinese characters, which causes this bug.

**Comment by xczh** [comment]
Translation is not available when the file path contains non ASCII characters. Can you fix this problem?Or, should we alert users to this problem? @chris2511
