### ISSUE TITLE
Multiple OCSP Responders

### ISSUE THREAD

**Issue by DraugurHundur** [chris2511/xca#172]
Although xca allows you to define multiple OCSP responders in Extensions>Authority Information Access, the generated syntax is refused is by OpenSSL and generates:
`error:2208B08F:X509 V3 routines:v2i_AUTHORITY_INFO_ACCESS:invalid syntax `

![image](https://user-images.githubusercontent.com/46813462/76614549-9ae0bd00-6520-11ea-83ba-f469428dbe35.png)

The workaround is to enter the information in the advanced tab instead:
`authorityInfoAccess = OCSP;URI:http://ocsp.my.host/,OCSP;URI:http://ocsp2.my.host/`

**Comment by JonathanWilbur** [comment]
@DraugurHundur @chris2511 Question for you both: what is the _correct_ behavior when there are multiple OCSP responders: must all of them be checked, or is one sufficient? I cannot find authoritative material on this.

**Comment by DraugurHundur** [comment]
I really don't know. I'm expecting that one is sufficient but not sure this is how all the clients are implemented (and how badly OCSP or OCSP must-staple support is implemented).
