### ISSUE TITLE
authorityInfoAccess : OCSP & CA Issuers

### ISSUE THREAD

**Issue by moocan** [chris2511/xca#176]
Hello,

Adding an`OCSP Responder URI` and a `CA Issuers URI` or trying to add multiple  `CA Issuers URI` generate this error
`error:2208B08F:X509 V3 routines:v2i_AUTHORITY_INFO_ACCESS:invalid syntax`

Seems that the workaround in `Multiple OCSP Responders #172` is working.
Clicking on `validate` button does not generate an error.
`authorityInfoAccess = OCSP;URI:http://ocsp.my.host/,CA Issuers;URI:http://crt.my.host/ca.crt,CA Issuers;URI:http://crt.my2.host/ca.crt`

Kind Regards

**Comment by chris2511** [comment]
fixed with c4eb23f2af24b34297d87ed2cc084fff874866d7
