### ISSUE TITLE
migrate from sqlite to sql

### ISSUE THREAD

**Issue by kjanss** [chris2511/xca#180]
Hi,
apart from using 'dump database', what would be the appropriate way to move from a file-based database to a SQL database ?
I am concerned about the ca's serial numbers.
the aim is to be able to work with multiple users concurrently on the same database.

**Comment by chris2511** [comment]
Dump the XDB file:
`sqlite3 ~/your.xdb .dump > DUMP`
For mysql mariadb:
Delete the first 2 lines with
`
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
`
and insert  instead
`SET SESSION SQL_MODE='ANSI';`

For postgres no modification is required.
Insert the SQL Dump via:

`mysql -u xca  -p xca <DUMP`
`psql -h localhost xca xca <DUMP`
 See https://www.hohnstaedt.de/xca/index.php/documentation/remote-databases how to create a database

**Comment by chris2511** [comment]
Could be useful for others, too.
Should be documented on https://www.hohnstaedt.de/xca/index.php/documentation/remote-databases

**Comment by kjanss** [comment]
I had to make 2 changes:
comment out:
/*PRAGMA foreign_keys=OFF;*/

remove the replace function: I replaced replace\(.*char.*\)\) with 'imported text deleted'
eg in:
INSERT INTO items VALUES(57,'*.blablabla',3,2,'20190531125238Z',replace('(Template ''bbla bla bla)\n','\n',char(10)),65);

I do not know sqlite, but replace seems to be a function specific to it.
