### ISSUE TITLE
[Feature Request] Integration with LetsEncrypt

### ISSUE THREAD

**Issue by dryiceza** [chris2511/xca#181]
Hi,

I was wondering if there was possible to do some integration with LetsEncrypt by having the xca application interact with LetsEncrypt to get server certificates?

Let me know if you have any questions!
Thanks!
Nolan

**Comment by chris2511** [comment]
I don't think this is a good idea and I don't see a real use case.
On internet hosts where the certbot is active, you usually don't run XCA.

What you could do is to cat all PEM files from /etc/letsencrypt/live to one big PEM
file, and import it into XCA. But this file will contain all your private keys unencrypted.

**Comment by chris2511** [comment]
Rejected as explained above.

**Comment by ziQ** [comment]
Stumbled over this today, as I was searching for XCA and Let's Encrypt consolidation.

I think a use case for integration would be to replace the certbot and to consolidate all key management, csr management and certificate management into XCA. Probably even include a feature to cross-sign certificates with an internal CA. Could be relevant for [DNS-01 challenges](https://letsencrypt.org/docs/challenge-types/), thus wouldn't require Internet connectivity within XCA.

Probably not the kind of use case that warrants a lot of development effort for you. I just wanted to add a different perspective.
