### ISSUE TITLE
UI not using Windows native theme in 2.2.1 portable

### ISSUE THREAD

**Issue by Alex131089** [chris2511/xca#182]
Hello, 

I just updated xca from 2.1.1 ("portable" by extracting using 7-zip) to 2.2.1 (official portable) and I couldn't miss the UI got a lot .. less nice 😏 (2.1.1 left, 2.2.1 right):
![image](https://user-images.githubusercontent.com/1735067/78122531-2d33fc80-740d-11ea-839c-f073df0a71a9.png)

Thanks for xca, making really easy to generate, play with and understand certificates. I only wish it had a webui part/equivalent to be deported on a lab host (but I just saw there's SQL connectors 🙂).

**Comment by chris2511** [comment]
Looks like some styles are missing.
Try putting the `styles` folder from https://www.hohnstaedt.de/downloads/
into your xca portable-app folder (and don't get irritated by the file name `qwindowsvistastyle.dll`)
Will deliver it by default in the next release.

**Comment by Alex131089** [comment]
Thank you ; `qwindowsvistastyle.dll` alone seems to be enough for me though :)
