### ISSUE TITLE
old-style UI on Windows after updating to 2.2.1

### ISSUE THREAD

**Issue by PF4Public** [chris2511/xca#188]
![image](https://user-images.githubusercontent.com/10319700/79044113-f8455800-7c0b-11ea-930f-a35a51a550b8.png)

**Comment by chris2511** [comment]
Please see #182
where you also find the solution for this now.

**Comment by PF4Public** [comment]
@chris2511 Thanks for pointing this out. I did a quick search beforehand, but didn't find that issue.
If you plan to fix this with next release, i'll just wait for it.
