### ISSUE TITLE
Replace 3DES encryption

### ISSUE THREAD

**Issue by nthuemmel** [chris2511/xca#19]
Currently, all stored or exported private keys are encrypted using 3DES. As 3DES is quite old and considered to be broken if used as a block cipher for long-lasting TLS sessions, its deprecation is underway. It would be better to switch to a more modern encryption algorithm, such as AES256, or - even better - allow the user to choose it when creating the database or exporting private keys.

**Comment by karlo1941** [comment]
CA private keys should be stored only encrypted

**Comment by phoerious** [comment]
Hi, sorry for abusing this thread for questions, but which cipher is used internally for the database? I noticed that all exports are done with 3DES in 1.4, which apparently changed with 94c3835ca50a5b01fdb1e6301a4ddeebae8d3440, but it's not entirely clear to me which cipher is used internally in either 1.4 or 2.x. Could you give me a short hint please? Thanks!

**Comment by chris2511** [comment]
The documentation is outdated.
Commit 431076c90e029373da59724b0623139c1dcf3e3b changed the internal storage type  of private keys to PKCS#8 with AES_256:
https://github.com/chris2511/xca/blob/c238d0a811eb428755c3cdbeca5f4ad1ac076785/lib/pki_evp.cpp#L598

**Comment by phoerious** [comment]
Okay, thanks. Unfortunately, that means that 1.4 is still 3DES and it's the only version that's in Ubuntu 18.04 and below.
