### ISSUE TITLE
OID LN differs warning popups at startup

### ISSUE THREAD

**Issue by teward** [chris2511/xca#191]
Found in Debian Unstable package, which I maintain.  Information from that bug is here:

> XCA shipped oids.txt mismatches against openssl defined OIDs, causing two
> popups to appear at application startup.
> 
> Warnings are also output on console:
> 
>    0.00 Warning: OID:  "1.3.6.1.4.1.311.20.2.3" LN differs:  "Microsoft
> Universal Principal Name"   Microsoft User Principal Name
>    2.02 Warning: OID:  "1.3.6.1.4.1.311.20.2.2" LN differs:  "Microsoft
> Smartcardlogin"   Microsoft Smartcard Login
> 

This may need addressed here in upstream, otherwise I'll have to distropatch this.

**Comment by accumulator** [comment]
Commit in OpenSSL : https://github.com/openssl/openssl/pull/10029
Change seems to be released in openssl-1.1.1e

**Comment by chris2511** [comment]
Yeah, discovered that, too :-)

**Comment by chris2511** [comment]
Adding debian bug link for reference
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=958886
