### ISSUE TITLE
Migrate form sqlite to sql - schema error

### ISSUE THREAD

**Issue by Netcandy-dev** [chris2511/xca#192]
There's an error in the SQL schema when dumping the sqlite DB. The 'key_' field in the 'settings' table is defined as CHAR(20) but the value 'adapt_explicit_subject' is exceeding this limit. As such the import in an SQL databse as described on the website under Docmentation, Remote Databases fails.
From sqlite3 dump:

CREATE TABLE settings (key_ CHAR(30) UNIQUE, value VARCHAR(10000));
INSERT INTO "settings" VALUES('adapt_explicit_subject','no');

Tested on xca 2.2.1 on win10 using portable install, exporting sqlitedb on Linux (after copy if xdb file) with SQLite version 3.11.0 (Ubuntu). Trying to import in Postgresql.

**Comment by chris2511** [comment]
I also found it and fixed it for 2.3.0:
def5f8e72efbdfc826c53d9122ba8104ed49835e

**Comment by Netcandy-dev** [comment]
Great!
For all 2.2 users; manually edit the SQL dump and change the definition of key_ to CHAR(30) also works. Doesn't seem to have any negative impact.
