### ISSUE TITLE
open recent does not work on MacOSX

### ISSUE THREAD

**Issue by silv3r23** [chris2511/xca#196]
when starting XCA 2.2.1 and 2.3.0 on MacOS 10.15.5 it does not start the last used xdb.
the function "open recent" does not work, it is empty. Every time using XCA its needed to go via "open file" and search for the location of the xdb from scratch

**Comment by Alyoscha** [comment]
+1

**Comment by forum4cc** [comment]
same problem here

**Comment by kic68** [comment]
+1

**Comment by daftu** [comment]
+1

**Comment by CJFWeatherhead** [comment]
Workaround / Fix: Create the "xca" directory in $HOME/Library/Application Support/data

A file called "dbhistory" should be created when you close the database

**Comment by silv3r23** [comment]
@CJFWeatherhead could you please explain how to do that? I have installed xca with brew cask. As you said workaround, is it on the roadmap to get it fixed some time?

**Comment by CJFWeatherhead** [comment]
I'm unsure what you mean? I don't know if Brew Cask puts the data in a different location (I'm using the .dmg installed to the Applications directory).

I'm essentially saying
`mkdir $HOME/Library/Application Support/data`

**Comment by silv3r23** [comment]
I created the "xca" directory in the mentioned path, worked for me, thank you!

**Comment by chris2511** [comment]
fixed in XCA 2.4.0with commit:
89635900 Create user-settings directory after creating QApplication
