### ISSUE TITLE
PKCS#11 "please insert card" after updating ykcs11 to 2.x causing serial change

### ISSUE THREAD

**Issue by gertvdijk** [chris2511/xca#198]
I've used XCA with an EC key on my Yubikey NEO PIV as CA, on Ubuntu 18.04 with the Yubico Stable PPA enabled. I started that small XCA database last year with the 1.7.x version of the ykcs11 pkcs11 library.

_One thing I remember in the past is that it would always show me serial "1234" for the card, which is odd, but decided to ignore it._

Now, early this year, ykcs11 is updated to 2.0 and comes with many fixes, including a serial number that is actually reflecting the one of the 'card'. However, this causes XCA to be confused whenever I want to use the card to sign a certificate for example.

**How do I tell XCA to have a pointer to the new card reference?** Is that a missing feature or is there a way around it? I've tried to re-import the key from the security token menu, but that fails with the error that the key is already present and will not be imported.

Downgrading to ykcs11 1.4.x from Ubuntu 18.04's own repository fixed it for now, and I can use the Yubikey again. It's not a long-term solution, though, as my other newer Yubikeys don't work with it. The 1.7.x version of the tools are vanished as the PPA only contains a single version. :confused: 

Haven't confirmed it yet, but I assume this will be a problem for everyone upgrading to Ubuntu 20.04 with existing databases as it ships with ykcs11 2.0 now.

(I noticed the token ID reference change with my OpenVPN and pkcs11 integration already before, but there I could just fix that by updating to the new pkcs11-id of the key slot.)

Before update (everything OK on current database):
![Screenshot from 2020-06-06 02-14-59](https://user-images.githubusercontent.com/1550527/83931574-bc5ae900-a79d-11ea-96a4-1466c9e77b56.png)

After update:
![Screenshot from 2020-06-06 02-16-23](https://user-images.githubusercontent.com/1550527/83931578-bf55d980-a79d-11ea-9fd4-7bbfe2c6aac4.png)
_Note that both the name and the serial are different._

Then error:
![Screenshot from 2020-06-06 02-17-18](https://user-images.githubusercontent.com/1550527/83931561-ae0ccd00-a79d-11ea-8c1b-992143419d06.png)

**Comment by chris2511** [comment]
Hi Gert,
what XCA Version do you use?
The observed behavior is known as issue #83 and fixed since XCA 2.2.0.
Ubuntu Focal should come with XCA 2.2.1:
https://packages.ubuntu.com/focal/xca

You may delete the token-item in the XCA database and re-import it to work around the issue: https://github.com/chris2511/xca/issues/115#issuecomment-487583113

**Comment by gertvdijk** [comment]
> You may delete the token-item in the XCA database and re-import it to work around the issue

Thanks! That worked. :smile: :tada: 

I was super scared to do that, because the dialog mentions it will delete the key on the token, but just by discarding that, the entry was gone and I could re-import it. The CA certificate remained in the database and after re-import of the key from the token, it pointed at the new 'card' again.

And thanks for your quick reply, much appreciated. :+1: 

> what XCA Version do you use?

I thought I was using a modern version, but no, the Ubuntu bionic 1.4.1 version it was.
My apologies for not mentioning that crucial info in the initial report.

FWIW, I created a backport of the version from Debian unstable (2.2.1 at time of writing) to Ubuntu Bionic for anyone else interested (disclaimer: no guarantees): https://launchpad.net/~gertvdijk/+archive/ubuntu/xca-backport
