### ISSUE TITLE
Error with version 1.4 when exporting certificate to p12 

### ISSUE THREAD

**Issue by lvandenb** [chris2511/xca#2]
When I export a certificate to p12 file The following error occurs.

(pki_x509:Rebus)
error:0D0E10DF:asn1 encoding routines:asn1_get_uint64:too large
error:0D0E10DF:asn1 encoding routines:asn1_get_uint64:too large

(pki_x509.cpp:454)

**Comment by lvandenb** [comment]
seems to be solved in 1.4.1 pre02 ..

**Comment by chris2511** [comment]
Hello lvandenb,

this has presumably  been fixed for XCA 1.4.1 with commit 365507b36e0633a6f978e632f97a0cdaca6b4dde
The pre-version 1.4.1-pre02 containing this change is available at https://hohnstaedt.de/downloads/

Please tell me whether 1.4.1-pre02 fixes it. You're not the only one with this issue....

Oh, a race :-)
You already approved it. Nice. Thanks!
