### ISSUE TITLE
WIN10x64 mariadb: "Prepared statement needs to be re-prepared

### ISSUE THREAD

**Issue by evmuc** [chris2511/xca#200]
After installation (Win10 2004 x64) trying to implement remote db setup with Mariadb 10.1.37-MariaDB-3 following error occured:

![sqlerror](https://user-images.githubusercontent.com/10739181/85140586-bf49e500-b245-11ea-88fc-89b304600b45.PNG)

Also restart of DB dosn't work (as suggested by other user as working solution)

**Comment by jory3** [comment]
Same here. The first time I used a remote Mariadb I was able to store a Private Key and a Certificate, when I reconnect I get this message for several tables and the list of Keys and Certificates are empty.

**Comment by jory3** [comment]
My solution was to move the database from a shared hosting to a MariaDB-container on Jelastic by Hidora. That works for me.

**Comment by chris2511** [comment]
See https://github.com/chris2511/xca/issues/563
