### ISSUE TITLE
Unable to access the Certificate Trust Form

### ISSUE THREAD

**Issue by rtomenchok** [chris2511/xca#201]
In an older version, I was able to set a trust attribute on the certificates.  The form had a frame with the caption of "Trustment" with three radio buttons:  Never trust this certificate, Only trust this certificate if we trust the signer, and Always trust this certificate.

What happened to the form?

**Comment by chris2511** [comment]
I dropped it.
Trust management is not an XCA task, but the responsibility of the client receiving the certificate
