### ISSUE TITLE
Warning message at first startu on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by tsmets** [chris2511/xca#203]
I installed on Ubuntu through 
` apt install xca`

At start up I received the following warnings :
![image](https://user-images.githubusercontent.com/329785/87685919-3363a400-c784-11ea-9887-0df138fa2f82.png)
![image](https://user-images.githubusercontent.com/329785/87686314-a79e4780-c784-11ea-8d0a-c35c7e487cf6.png)

Nothing blocking.
It is just annoying.

\T,

**Comment by chris2511** [comment]
See Issue #191 .
You may help yourself by deleting the lines from /usr/share/xca/oids which silences the warnings.

See my change in https://github.com/chris2511/xca/commit/76e3f86783b5b472c5601750d2ddca615570fffd#diff-7b3c3a6dc31775739f710c32453eb0f1

**Comment by boospy** [comment]
So, no Update to Focal with the package? Your are in contact with Thomas Ward <teward@ubuntu.com> ?
