### ISSUE TITLE
XCA hung when importing EC keys. For example prime256v1

### ISSUE THREAD

**Issue by Olegandr** [chris2511/xca#208]
Come to report his issue, found it was already mentioned.
XCA hung when importing EC keys. For example prime256v1

_Originally posted by @advcron in https://github.com/chris2511/xca/issues/106#issuecomment-640854143_

**Comment by zoredache** [comment]
I believe I am also seeing this.

**Comment by seaowl** [comment]
Me to.
XCA Version: 2.3.0 / ECC With RFC 5639 Brainpool curves / OpenSSL 1.1.1g 21 Apr 2020 / QT version: 5.12.0

Steps to reproduce:

- Create EC private key with openssl:
`openssl ecparam -name prime256v1 -genkey -noout -out ec_key.pem`
- Try to import with xca.exe for Windows. xca.exe start utilizing CPU and hangs forever.
