### ISSUE TITLE
CSR's

### ISSUE THREAD

**Issue by southeasterntech** [chris2511/xca#212]
I'm trying to secure some internal servers inside the LAN only.  I created my CA's and made some certificates, but I'm questioning the fact that I didn't involve creating a CSR.  Is that because I created my own CA and therefore I don't need the CSR?

Thanks
Shane

**Comment by chris2511** [comment]
Exactly.
A CSR is only necessary to send a public key with personal data to an external CA.
Since you as CA also generated the private key of the client certificates and knew  the content of the distinguished name,
you did not need it.
