### ISSUE TITLE
Crash when importing EC keys

### ISSUE THREAD

**Issue by dannytech** [chris2511/xca#215]
I'm generally unable to import any `secp384r1` keys into XCA, any attempt to do so simply crashes the program. I've tried using PFX, decrypting the key first, and trying other keys. I noticed a couple other GitHub issues about hanging with EC, but the behavior I'm noticing here is usually crashing. That is, when importing a private key using the "Import" or "Import PFX" buttons, the keys will guarantee an immediate crash. However, when importing via Ctrl+V or the Paste PEM menu item, a similar problem does not arise. Instead, it either succeeds (this only happened in the beginning, and rarely, and now it no longer works), or hangs as the CPU usage constantly increases.

The keys were generated with the command `openssl ecparam -genkey -name secp384r -out key.pem`.

**Comment by xczh** [comment]
Confirmed. I tried and it carshed again.

**Comment by DerArtem** [comment]
The problem appeared in Version 2.2.0 - older versions are working fine. I have used a prime256v1 key. When trying to import xca freezes.

**Comment by xczh** [comment]
> The problem appeared in Version 2.2.0 - older versions are working fine. I have used a prime256v1 key. When trying to import a .der ecoded key xca freezes.

Is this problem solved now? @chris2511

**Comment by chris2511** [comment]
Close as dup of #208
