### ISSUE TITLE
[Feature request] Support for UID

### ISSUE THREAD

**Issue by JayBrown** [chris2511/xca#217]
Many certificates have a UID=<UserID> thing, next to the OU (organizational unit), CN (common name) etc.

E.g., a code-signing certificate by Apple looks like this:

![snap](https://i.imgur.com/12ZklyY.jpg)

```
openssl x509 -in ~/codesign0.der -inform DER -noout -text -fingerprint
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1578867237078431566 (0x15e943630d8ff74e)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=Developer ID Certification Authority, OU=Apple Certification Authority, O=Apple Inc., C=US
        Validity
            Not Before: Feb 18 23:39:36 2017 GMT
            Not After : Feb 19 23:39:36 2022 GMT
        Subject: UID=2BUA8C4S2C, CN=Developer ID Application: AgileBits Inc. (2BUA8C4S2C), OU=2BUA8C4S2C, O=AgileBits Inc., C=US
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
```

I have looked into the xca options under Subject > Distinguished Name, and UID is not there, not even in the additional types you can choose. Please note that x500UniqueIdentifier is not the UID.

Would be great if xca would support this in a future update.

**Comment by chris2511** [comment]
You may add "UID" to the dn.txt file to support the UserID.
Please see: https://hohnstaedt.de/xca/index.php/documentation/objectids

**Comment by JayBrown** [comment]
Wow, even more than I asked for. Thank you!. 👍
