### ISSUE TITLE
Encryption for exported keys

### ISSUE THREAD

**Issue by Jafaral** [chris2511/xca#218]
When I export files with private keys like .p12 or .pem, what encryption is used?  What is the default ? Is that user-configurable ? Did that change in recent releases ?

Thanks!

**Comment by Jafaral** [comment]
@chris2511 Can you please shed some light on this ?

**Comment by chris2511** [comment]
XCA uses AES-256 for encryption
The PKCS#12 Algorithm can be selected in the options
