### ISSUE TITLE
Import Certs

### ISSUE THREAD

**Issue by nefas83** [chris2511/xca#22]
Tried to import a bunch of cert with the import from the top menu.
But the application will freeze. 
At the import button on the side it will work.

Best Regards

**Comment by chris2511** [comment]
Tested here and it works on linux.
Did you use "Import->Certificates" or "Import->PEM file" ?
Did you import exactly the same certificates with the button ?
Can you paste the imported certificates here or send them to my private mail address ?

**Comment by chris2511** [comment]
Closing stalled issue as **wontfix**.
Please reopen if there is new information
