### ISSUE TITLE
[Change Request] Consider changing PKCS12 export extension from .p12 to .pfx by default, as p12 is a legacy Netscape holdover, and PFX is the 'standard' per RFC now.

### ISSUE THREAD

**Issue by teward** [chris2511/xca#230]
.p12 is a netscape holdover, while .pfx is Microsoft's naming for a PKCS12 export file.

Unfortunately, Windows refuses to accept .p12 and requires .pfx.  Since the majority market share uses PFX because of Microsoft, we should probably consider the default export for a cert/key PKCS12 file .pfx instead.

**Comment by mq2195** [comment]
RFC7292 also has no mention of .pfx file extension.
I understand desire of Microsoft software users for convenient file naming, but is that enough to force this naming policy on other platforms users?
Maybe configurable default extension for PKCS12 export files is the answer.
