### ISSUE TITLE
[Enhancement] Ability to specify database port

### ISSUE THREAD

**Issue by exabrial** [chris2511/xca#233]
First, thank you! Open source work often goes without a thank you, and I very much appreciate your efforts and the wonderful application you've made.

We'd love to be able to use a cloud database to store our XCA DB. Most of the time, when you spin up a managed DB, they use some non-default port (Digital Ocean does this for sure). The Open Remote Database option dialog box does not allow you to specify a port.

Anyway thank you again, cheers!

**Comment by chris2511** [comment]
Did you try appending the host name by the port number with a colon?
Yesterday I thought about implementing it, when I realized I already did that while adding support for remote databases :-)

**Comment by exabrial** [comment]
No I didn't, I'll give that a try!

**Comment by chris2511** [comment]
Should work. Please reopen otherwise.
