### ISSUE TITLE
Big Sur 11.0.1

### ISSUE THREAD

**Issue by sem174** [chris2511/xca#234]
Not work, freezes. No log, no errors.

**Comment by docspy** [comment]
Same for me. Installed via homebrew version 2.3.0

**Comment by sem174** [comment]
<img width="392" alt="Снимок экрана 2020-11-15 в 15 01 34" src="https://user-images.githubusercontent.com/8233588/99184461-0801bd80-2754-11eb-9365-5164feb85739.png">
Homebrew don't work

**Comment by mhuter** [comment]
Version 2.3.0.78 from local download area works on BigSur:
https://www.hohnstaedt.de/downloads/xca-2.3.0.78.dmg

**Comment by sem174** [comment]
All ok, works
