### ISSUE TITLE
MacOS Big Sur, App start without window

### ISSUE THREAD

**Issue by linusklan** [chris2511/xca#236]
Icons is visible in launchbar, but no applicaion window

**Comment by linusklan** [comment]
J found solution, by set system env QT_MAC_WANTS_LAYER=1
export QT_MAC_WANTS_LAYER=1, open /Applications/xca.app, and it works.

**Comment by trendchiller** [comment]
same here

**Comment by chris2511** [comment]
Please try the pre-version:
https://www.hohnstaedt.de/downloads/xca-2.3.0.78.dmg
and report whether it works without setting QT_MAC_WANTS_LAYER

**Comment by trendchiller** [comment]
looks good so far, thank you, Christian,  for your fast support. !

**Comment by sdjnmxd** [comment]
Everything is normal on macOS big sur 11.0.1, and it seems that the functions are available. thank!

**Comment by thomaskrampe** [comment]
2.3.0.78 works fine on Big Sur. I don't see any issue yet.

**Comment by carlfitzsimmons** [comment]
I just upgraded to Big Sur and ran across the same problem as described. I had found the 2.1 version series worked but not any in the 2.2 series. I was looking for a solution I came across this thread and downloaded 2.3.0.78. So far so good. I will be using this to create server side verification for OpenVPN soon. @chris2511 thanks for providing this update

**Comment by hashfunktion** [comment]
@chris2511 Thanks for the quick solution, works fine!

**Comment by linusklan** [comment]
Thank you @chris2511

**Comment by MichaelOrtho** [comment]
When I tried v2.3.0 it broke my DB (before any prompt) and CPU went to 100%. That happens to all versions starting with v2.2.0. This fix allowed me to recover my DB and it is working as expected. Thank you @chris2511!

**Comment by urda** [comment]
> J found solution, by set system env QT_MAC_WANTS_LAYER=1
> export QT_MAC_WANTS_LAYER=1; open /Applications/xca.app, and it works.

This allowed me to boot the `2.3.0` on my Mac for normal usage.

**Comment by ijaureguialzo** [comment]
Just tested and 2.3.0.78 works on Big Sur 11.2 (20D64).

**Comment by urda** [comment]
<img width="560" alt="image" src="https://user-images.githubusercontent.com/1648492/115923831-b14f8c80-a433-11eb-8ced-965a6ad3a091.png">

launches under

<img width="257" alt="image" src="https://user-images.githubusercontent.com/1648492/115923847-bb718b00-a433-11eb-87b0-bc6c61d7466a.png">

---

The `2.3.0` on public download for Macs still has this problem. This should get fixed sooner than later since it's impacting the public.

**Comment by urda** [comment]
> Please try the pre-version:
> https://www.hohnstaedt.de/downloads/xca-2.3.0.78.dmg
> and report whether it works without setting QT_MAC_WANTS_LAYER

Does this version not support remote databases?

**Comment by carlfitzsimmons** [comment]
Evening Chris,

I was able to open .xdb files. It seems as though there is no way to set a primary directory for cert work. Also mot certain if that was something that was available/worked in previous versions

Carl

On Apr 23, 2021, at 4:52 PM, Peter Urda ***@***.******@***.***>> wrote:



Please try the pre-version:
https://www.hohnstaedt.de/downloads/xca-2.3.0.78.dmg
and report whether it works without setting QT_MAC_WANTS_LAYER

Does this version not support remote databases?

**Comment by chris2511** [comment]
Please try https://hohnstaedt.de/downloads/xca-2.3.148-High-Sierra.dmg

- It is almost ready to become the 2.4.0 release
- It is officially signed with my Apple developer certificate and notarized by Apple

So the Gatekeeper should be satisfied

**Comment by ijaureguialzo** [comment]
Just tested 2.3.148 on 11.3 (20E232) and it launches without issue; it only warns about that the program is downloaded from the internet, but doesn't give any gatekeeper related messages. 

Tried opening a db and all my certs are there so far.

Seems good to me.

**Comment by urda** [comment]
> Please try https://hohnstaedt.de/downloads/xca-2.3.148-High-Sierra.dmg
> 
> 
> 
> - It is almost ready to become the 2.4.0 release
> 
> - It is officially signed with my Apple developer certificate and notarized by Apple
> 
> 
> 
> So the Gatekeeper should be satisfied

Does this include network database features? That was holding me back from trying the other version as I keep my XCA database on an internal DB.

**Comment by chris2511** [comment]
Yes

**Comment by urda** [comment]
> > Does this include network database features? That was holding me back from trying the other version as I keep my XCA database on an internal DB.
> 
> 
> 
> Yes

I'll give it a try later this evening after work

**Comment by chris2511** [comment]
Fixed with the officially signed and notified release build 2.4.0
https://github.com/chris2511/xca/releases/download/RELEASE.2.4.0/xca-2.4.0.dmg

The missing remote database drivers in the 2.4.0 DMG will be addressed with Issue #278

**Comment by thomaskrampe** [comment]
Official signed 2.4.0 XCA build works perfectly on 11.3.1. Thanks for your work and effort Chris. What's about a new BigSur style app icon?  ;-)

**Comment by urda** [comment]
YES @chris2511 thanks so MUCH. Booted up just fine over here.

<img width="560" alt="image" src="https://user-images.githubusercontent.com/1648492/117953817-43c4ac80-b2cb-11eb-8b09-5ed13a14438f.png">
