### ISSUE TITLE
secp256r1 not included

### ISSUE THREAD

**Issue by Frank1773** [chris2511/xca#237]
is there a plan to implement **secp256r1**?

**Comment by mistial-dev** [comment]
Thank you @horsth .  This was driving me nuts.

When I get a chance, I'll put a pull request together to change the label to make sure that prime256 v1 is labeled as a NIST/X9.62/SECG curve, like it is for prime192v1.

![image](https://user-images.githubusercontent.com/69981049/145904504-2de8e6e6-8e08-4099-8168-ed27dc604db8.png)
