### ISSUE TITLE
Secured Connection to Database

### ISSUE THREAD

**Issue by anthonyjlmorel** [chris2511/xca#238]
First, I would like to thank you for the tremendous work here.

I would like to know if it is possible to connect to a DB (mariaDB or MySQL) in a secured manner?
If I require SSL or certificate from my DB, XCA is unable to connect.

Thanks !

**Comment by chris2511** [comment]
Did you read:
https://hohnstaedt.de/xca/index.php/documentation/remote-databases
Are you able to connect encrypted with the mysql/mariadb command line client tool on the host where XCA is executed?

**Comment by anthonyjlmorel** [comment]
My bad, I didn't came across this, closing now.
