### ISSUE TITLE
Name Constraints of signing certificate are not respected when creating a new certificate

### ISSUE THREAD

**Issue by mq2195** [chris2511/xca#239]
[BUG] or [FEATURE REQUEST] ?

It is possible to create invalid certificate with following:

``
X509v3 Subject Alternative Name:
DNS:testserver.example.net, IP Address:192.168.22.1, IP Address:192.168.122.1, IP Address:192.168.23.1, IP Address:192.168.32.1, IP Address:192.168.33.1
``

When Root CA is defined with following Name Constraints:

`X509v3 Name Constraints:
Permitted:
DNS:example.net
DNS:example.org
Excluded:
IP:0.0.0.0/0.0.0.0
IP:0:0:0:0:0:0:0:0/0:0:0:0:0:0:0:0`

Tested with chain: Root CA -> Sub CA -> testserver.example.net
Root CA and Sub CA have exactly the same Name Constraints defined. (yes, I am aware that Sub CA does not need them - they are "inherited" automatically)

Encountered errors when trying to use this certificate:
SEC_ERROR_CERT_NOT_IN_NAME_SPACE
verify error:num=48:excluded subtree violation

**Comment by chris2511** [comment]
I vote for "Feature Request", because it requires additional code to check the constraints and is rather a usability thing.

**Comment by dtklein** [comment]
Feature request, but definitely an important and valuable feature that I would like to see implemented
