### ISSUE TITLE
Warning dialogues show up on startup

### ISSUE THREAD

**Issue by morciej** [chris2511/xca#241]
In xca version 2.2.1-1 currently in Mint Ulyana/Ubuntu Focal repositories, the following messages show up on startup:

![Screenshot_2020-12-06_21-02-07](https://user-images.githubusercontent.com/17895139/101311524-77744580-3806-11eb-8925-24a0ac7c712e.png)

![Screenshot_2020-12-06_21-02-30](https://user-images.githubusercontent.com/17895139/101311534-7c38f980-3806-11eb-9d98-07cda7720bed.png)

Surprising, I have nothing releated in the database that I am using - just a couple of keys and a self-signed certificate. :-)

**Comment by chris2511** [comment]
Duplicate of #191 and fixed with 76e3f86783b5b47
