### ISSUE TITLE
Addition of XCA to PortableApps.com!

### ISSUE THREAD

**Issue by Peppernrino** [chris2511/xca#242]
I have packaged XCA in .paf.exe format for PortableApps.com, and would like to finally inform you!

https://portableapps.com/node/59733

Let me know what you think. If there are no bugs, etc, we can put it on the list to be added to the official list of apps. :)

**Comment by chris2511** [comment]
Just go ahaed. Thanks for your work.

**Comment by Peppernrino** [comment]
no man. thank you for yours. i'm just a package man. :D
