### ISSUE TITLE
doc says ec curve can be typed in

### ISSUE THREAD

**Issue by horsth** [chris2511/xca#243]
I wanted to generate EC key with secp256r1 (same as #237 ). That one seems not available in combobox. According to documentation it should be possible to type in different curves but it seems only combobox works.

**Comment by horsth** [comment]
with my original problem, how to generate the ECC key with secp256r1 now solved my only remaining "problem" is, that the documentation indicates one should be able to write "arbitrary" text for selecting a curve into the combobox dialog while in reality you can only select existing one of the existing entries. Maybe as simple as outdated documentation?

**Comment by chris2511** [comment]
It's about RSA/DSA key **sizes**
> Even if the **size** drop-down list only shows the most usual key **sizes**, any other **size** may be set here by editing this box.
