### ISSUE TITLE
Could not load the Qt platform plugin xcb

### ISSUE THREAD

**Issue by sbuller** [chris2511/xca#244]
I'm trying to run the flatpak on my system, but hitting an error.
My system runs Sway on Fedora 32. Sway is a wayland based window manager.
XWayland is available, and I can confirm that other X11 based applications work, including through flatpak. I've verified io.atom.Atom specifically.

I'm not sure what to provide besides command line output:

```
$ flatpak run io.github.chris2511.xca
   0.00 Warning: could not connect to display
   0.00 Info: Could not load the Qt platform plugin "xcb" in "" even though it was found.
   0.00 Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```

**Comment by chris2511** [comment]
If there are still flatpak issues, please report them here:
https://github.com/flathub/de.hohnstaedt.xca
