### ISSUE TITLE
Can't compile xca on windows -missing ltdl.h?

### ISSUE THREAD

**Issue by xiaodongde** [chris2511/xca#250]
ltdl.h:No such file or directory 
In file included from ..\xca/lib/pki_base.h:17:0
......

**Comment by chris2511** [comment]
The `ltdl.h`is part of http://ftp.gnu.org/gnu/libtool
I'm cross-compiling XCA for windows on linux. If you do so, too, please see: https://github.com/chris2511/xca/blob/master/INSTALL.w64
If you compile XCA on windows and succeed, please write it down for me and others.
