### ISSUE TITLE
Issuer is not supported when Use certificate to signing

### ISSUE THREAD

**Issue by senioi** [chris2511/xca#251]
`Use certificate to signing`
Advanced:
```
**basicConstraints=critical,CA:TRUE
authorityKeyIdentifier=keyid, issuer
subjectKeyIdentifier=hash**
```

**`XCA:`**
**Use certificate to signing:**
![image](https://user-images.githubusercontent.com/42415346/106397785-21103580-644a-11eb-8597-0fd9f6647ad3.png)
**CA chain created with XCA:**
![image](https://user-images.githubusercontent.com/42415346/106397645-75ff7c00-6449-11eb-98a0-79d8b8210311.png)

**`OPENSSL:`**
**`CA chain created with OPENSSL`**
**Advanced parameters:**
![image](https://user-images.githubusercontent.com/42415346/106397950-09857c80-644b-11eb-8d6c-a4534f76f5c5.png)
**Advanced parameter preview:**
![image](https://user-images.githubusercontent.com/42415346/106397916-d6db8400-644a-11eb-9559-249bf92f91e5.png)

**`issue`**
Is there any way to make XCA support **authorityKeyIdentifier=keyid, issuer** ?

**Comment by chris2511** [comment]
You need to use: `authorityKeyIdentifier=keyid, issuer:always`
See https://www.openssl.org/docs/man1.0.2/man5/x509v3_config.html#ARBITRARY-EXTENSIONS
