### ISSUE TITLE
"Network Database" is greyed

### ISSUE THREAD

**Issue by AchMol** [chris2511/xca#252]
Hi all,
thanks for the MAC OSX Version xca-2.3.0.78.dmg which shows the windows. But I cannot activate the network database because it is greyed out under OSX Big Sur.

Do I need another (QT mysql) driver or something?

It works fine with a local database.

Thanks,
AchMol

**Comment by AchMol** [comment]
Hi all,

is really nobody using an external DB with XCA?

Thanks,
AchMol

**Comment by chris2511** [comment]
xca-2.3.0.78.dmg is an unofficial pre-release, which was only intended to test that it works on Big Sur.
I need to create an official release and am working on it.

**Comment by chris2511** [comment]
Did you try: `QT_MAC_WANTS_LAYER=1; open /Applications/xca.app` with XCA 2.3.0?
This should enable network database use on Big Sur until the next release.

**Comment by AchMol** [comment]
Hi Chris,

yes thanks, I choosed the 2.3.0.78 because of the missing XCA GUI under Big Sur and 2.3.
I tried  the env QT_MAC_WANTS_LAYER=1 but the "network database" menu is still greyed out.

So I will wait for the next Release...  ;-)

Thanks so far for this wonderful little Application!

AchMol

**Comment by chris2511** [comment]
Still no luck with remote database on macOS, but tracked with #278
