### ISSUE TITLE
[Feature request] CRL Generation Command Line Argument 

### ISSUE THREAD

**Issue by calw20** [chris2511/xca#253]
First a thankyou and appreciation, XCA has not only cut down but cut out my horrible OpenSSL wrappers developed and provided a simple system to handle a small certificate chain. Thankyou for the hours saved.

As someone who uses a MySQL database, its quite tedious to manually generate CRLs. The ability to have XCA create CRLs automatically via a command line option would be awesome improvement to XCA.

Many thanks for your current work, can't wait for it's future,

**Comment by swoga** [comment]
duplicate of #157

This feature was in the works before but the branch was deleted: https://github.com/chris2511/xca/commit/a1a398a17d01822248c25876d26a27436fab238d

**Comment by calw20** [comment]
Oh neat, is it known if there are plans to re-implement this or will we have to use a1a398a?

**Comment by swoga** [comment]
I think this feature was not ready yet, as it was still in a development branch.

**Comment by chris2511** [comment]
commit 2f91723 and the whole cmdline handling (opening remote databases, acquiring passwords, etc.) has been merged into master and will be available in the next release.

**Comment by calw20** [comment]
Awesome! Thanks for the great work.
