### ISSUE TITLE
xca-2.3.0.msi is triggering the rule "Suspicious MsiExec Directory" on virustotal.com

### ISSUE THREAD

**Issue by vbrozik** [chris2511/xca#255]
Detection on VirusTotal:
https://www.virustotal.com/gui/file/a3d2295af4720455f20c366bd5c2c5a50625abab97b0209618e8a1e3c3c71168/detection

is triggering the rule Suspicious MsiExec Directory by Florian Roth from Sigma Integrated Rule Set:
https://github.com/Neo23x0/sigma/blob/master/rules/windows/process_creation/win_susp_msiexec_cwd.yml
Decription of the rule: Detects suspicious msiexec process starts in an uncommon directory

The detection was triggered for this execution event:
```
$EventID: '1',
$Image: 'C:\Users\admin\Downloads\msiexec.exe'
```

Could you please check the xca-2.3.0.msi installer for this path/event?

**Comment by chris2511** [comment]
Maybe it is the uninstaller?
```
 <Shortcut Id="UninstallXCA"
                          Name="Uninstall XCA"
                          Description="Uninstalls XCA"
                          Target="[System64Folder]msiexec.exe"
                          Arguments=" /x [ProductCode]"/>
```
Where does your `System64Folder` point to?
                  
No idea what exactly is the problem.

**Comment by vbrozik** [comment]
I think `System64Folder ` normally resolves to `C:\Windows\SysWOW64`.

I noticed the problem when I was checking the latest release in VirusTotal and I wanted to let you know about it.

Now for me it seems that the problem could be in the virtual machine on VirusTotal where the evaluation of `xca-2.3.0.msi` was performed. But I am just guessing.

**Comment by chris2511** [comment]
msiexec is the generic windows installer application, usually located in 
`C:\Windows\System32\msiexec.exe`
Having a copy of it in 
`C:\Users\admin\Downloads\msiexec.exe`
looks suspicous to me and virustotal.com. Delete it and try again...

**Comment by vbrozik** [comment]
I am not sure if I understand what you mean by "Delete it and try again..."

If you mean deleting some files on your own machine it does not make sense here. Your machine is not involved at all with the checks on VirusTotal. You just upload the file (xca-2.3.0.msi) there. All the malware-checking work is performed in the VirusTotal infrastructure. You cannot affect it.
