### ISSUE TITLE
Install guide / binary is missing

### ISSUE THREAD

**Issue by zappee** [chris2511/xca#257]
Hello,

Maybe this is a fantastic tool, but unfortunately, I have no chance to try it. There is no way to make it works on my Linux. I have not found either binaries or a clear installation guide.

Could you please provide the binary file for Linux?

Thanks,
Arnold

**Comment by chris2511** [comment]
apt install xca
rpm install xca
https://github.com/chris2511/xca/blob/master/INSTALL
https://github.com/flathub/flathub/pull/1829
