### ISSUE TITLE
Huge memory consumption on Freeze

### ISSUE THREAD

**Issue by un-creatrix** [chris2511/xca#264]
When either downloaded or built through home brew, XCA crashes and starts consuming all memory and eventually over runs into paging till all memory is consumed. MacOS steps in and stops XCA at that point.

**Comment by chris2511** [comment]
Could you try https://hohnstaedt.de/downloads/xca-2.3.148-High-Sierra.dmg
and/or the current master?
If it still happens, please tell me which macOS version you use.

**Comment by un-creatrix** [comment]
Works great, I am on BigSur with the M1 chip and am getting up to speed with my dev environment on such

**Comment by chris2511** [comment]
https://github.com/chris2511/xca/releases/download/RELEASE.2.4.0/xca-2.4.0.dmg
is released, signed and notified.

Please update.
