### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by handfreezer** [chris2511/xca#267]
Hello,
  Is it possible to add TLS mode for mariadb at least, with eventually an autosigned CRT as parameter to check certificate of the server?

Best regards

**Comment by chris2511** [comment]
Does https://hohnstaedt.de/xca/index.php/documentation/remote-databases answer your questions?
It also has a "TLS Encrypted Database Connection" chapter

**Comment by handfreezer** [comment]
Yes , it seems.
Thx
