### ISSUE TITLE
Can't edit templates on 2.3.0.78-dev on macOS 11.2.3 

### ISSUE THREAD

**Issue by henningkessler** [chris2511/xca#269]
Hi there,

When I select a template and klick on the button "Vorlage ändern" nothing happens...

Thanks for the great software.

Henning

**Comment by chris2511** [comment]
The 2.3.0.78 was a pre-release.
Please try https://hohnstaedt.de/downloads/xca-2.3.148-High-Sierra.dmg
which is almost ready to become the next release: 2.4.0.
