### ISSUE TITLE
Certificate warn interval

### ISSUE THREAD

**Issue by PF4Public** [chris2511/xca#27]
Right now certificates are coloured according to percentage of remaining time. This keeps 5 year certificates coloured for their entire last year. Wouldn't it be better to colour all certificates, say 5 or 10 days before expiry? Or a user configurable setting maybe?

**Comment by PF4Public** [comment]
Wonderful!
Thanks.

**Comment by PF4Public** [comment]
Will configurable expiry date calculation be available for colouring or only for vCalendar export?

**Comment by chris2511** [comment]
Primarily for coloring.

Am 29. April 2018 20:29:32 MESZ schrieb PF4Public <notifications@github.com>:
>Will configurable expiry date calculation be available for colouring or
>only for vCalendar export?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/chris2511/xca/issues/27#issuecomment-385271254

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by PF4Public** [comment]
That would be great, thanks again.
