### ISSUE TITLE
How to enable DEBUG/logging mode for XCA ?

### ISSUE THREAD

**Issue by jaredbarez** [chris2511/xca#276]
I would like to see actual openssl commands/proc_calls that are invoked during CSR/CRT activities (i.e. signing, revoking, etc.). Please help. Thanks

**Comment by chris2511** [comment]
A pretty comprehensible piece of code how to use the x509 API is by the authors of openssl themselves:
https://github.com/openssl/openssl/blob/master/apps/x509.c

**Comment by jaredbarez** [comment]
Unfortunately that answer doesn't help me. I want to enable debug logging mode for XCA executable itself. Is there debug mode for XCA ? Please help

**Comment by chris2511** [comment]
You may start xca from the console with the environment variable XCA_DEBUG=1
and xca will print a lot of more or less useful information on the console.

**Comment by jaredbarez** [comment]
Thank you very much !

**Comment by jaredbarez** [comment]
Thank you very much !
