### ISSUE TITLE
Incomplete data in "X509v3 Authority Key Identifier" atribute

### ISSUE THREAD

**Issue by jaredbarez** [chris2511/xca#277]
Why XCA generated certificates with "X509v3 Authority Key Identifier" atribute don't have _DirName_ and _serial_ values set ? Only _keyid_ value is set.

**Comment by chris2511** [comment]
According to [RFC5280 4.2.1.1](https://tools.ietf.org/html/rfc5280#section-4.2.1.1) all 3 entries are optional. 
You may deselect the checkbox in XCA and force the desired entires with `authorityKeyIdentifier = keyid, issuer:always` on the "Advanced" tab as described in [OpenSSL x509v3_config](https://www.openssl.org/docs/manmaster/man5/x509v3_config.html)

XCA by default only uses the keyid to ease a CA rollover. If the serial is **not** included in the client certificates AuthKeyId,
the issuing certificate maybe re-issued with the same key and longer validity times and different serial
and still be a valid issuer for certificates issued by the previous CA

**Comment by jaredbarez** [comment]
Thank you for clarification.

**Comment by polski-g** [comment]
I am attempting to utilize XCA to generate a certificate chain for use in kanidm. The developers over there say that Authority Key Identifier [is required](https://github.com/kanidm/kanidm/issues/655#issuecomment-2169044656) for CAs. If true, then Authority Key Identifier should be checked by default when selecting the CA template on the Source tab.
