### ISSUE TITLE
Building on macOS created xca.app in root not xca-2.4.0 subfolder

### ISSUE THREAD

**Issue by lhaeger** [chris2511/xca#279]
Looks as if you forgot to change line 4 in `INSTALL.mac`
```
cd **xca-2.3.0**
./configure && make
```

**Comment by chris2511** [comment]
the toplevel xca.app is a raw, unsigned and un-macdeployqt'd incarnation.
The  "xca-2.4.0" subdirectory contains the fully deployed APP

**Comment by lhaeger** [comment]
> the toplevel xca.app is a raw, unsigned and un-macdeployqt'd incarnation.
> The "xca-2.4.0" subdirectory contains the fully deployed APP

It should be, but since you try to cd into 2.3.0 instead of 2.4.0 it is not being created in my test. Or did I miss something here?
