### ISSUE TITLE
[2.0.0 Windows] cannot export private key or pkcs12 chain with private key

### ISSUE THREAD

**Issue by dembach** [chris2511/xca#28]
i have got a private and public key, also a certificate of the signing ca.

now i want o try to export as pkcs12 chain. 
the chain is beeing exported, but it contains no private key.

ok, next try to export the files and use openssl to create the pkcs12 chain.
on exporting the private key to a file, all files i do export , i will never be asked for a password and all file length are 0.
ok, i said... let´s try to export via clipboard:
now the application crashes (not responding anymore)

going back to 1.x does not work, it seems that there is a database change.

exporting the complete certificate structure also does not create a valid file for the private key ( 0 bytes)

thanks

Markus from germany

**Comment by chris2511** [comment]
The expression

> database is somewhat corrupted

sounds like a serious issue.

Do you think XCA did something wrong?
Did you upgrade an existing database from XCA 1.x to 2.0.0?
For further investigation, i would either need a reproduction-guide or your database.
If you think you can't provide either of them (which I fully understand), please close this issue.

**Comment by dembach** [comment]
I was using 1.3.7 at first and tried upgrading to 2.0.0 , but the error
stayed the same...



Christian Hohnstädt <notifications@github.com> schrieb am Do., 26. Apr.
2018, 15:29:

**Comment by chris2511** [comment]
Close as _worksforme_
