### ISSUE TITLE
brew install xca FAILS due to checksum MISMATCH

### ISSUE THREAD

**Issue by urda** [chris2511/xca#280]
```bahs
$ brew install xca
==> Downloading https://github.com/chris2511/xca/releases/download/RELEASE.2.4.0/xca-2.4.0.dmg
==> Downloading from https://github-releases.githubusercontent.com/649898/7d150200-b262-11eb-92cc-d63fec9be8e9?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-A
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 3445524ef5e81d5f19c4d4ace1f849480fe982458e31cebe689b6fd8b11200bc
  Actual: a5672fd46168b8d81c226dc47dd0022773382389291676c8aa17d6765e20b697
    File: /Users/urda/Library/Caches/Homebrew/downloads/f6a6abe9fb7a8fb879e8f94592040d850ab2000d7380091b49519c27490014c6--xca-2.4.0.dmg
To retry an incomplete download, remove the file above.
```

However the website reports:

```
a5672fd46168b8d81c226dc47dd0022773382389291676c8aa17d6765e20b697
```

As the valid SHA value, which is confirmed via:

```
$ shasum -a 256 ./xca-2.4.0.dmg
a5672fd46168b8d81c226dc47dd0022773382389291676c8aa17d6765e20b697  ./xca-2.4.0.dmg
```

However brew shows the wrong values via:

- https://github.com/Homebrew/formulae.brew.sh/blob/a573e2448e3628ce50e26d0ef279db03ec84c31b/_data/cask/xca.json#L15
- https://github.com/Homebrew/homebrew-cask/blob/c49e38fcf579d16716b9e282203e27e1efe50b44/Casks/xca.rb#L3

Which I think was added via:

- https://github.com/Homebrew/homebrew-cask/pull/105394

This SHASUM needs to be corrected.

**Comment by urda** [comment]
# Workaround:

I consider this a semi-safe workaround as the XCA website reports it and we can see a commit with the SHA via:

https://github.com/chris2511/xca/blame/e0dc4446c52b29dcaa3d110db16666de9e1dd09a/release/binary-hashes.json#L78

So unless the contributor was compromised (unlikely I believe) we can consider this hash semi-safe. One can do a `brew edit xca` and edit the checksum themselves, adjust the checksum, and continue.

**Comment by chris2511** [comment]
Especially since both checksums are correct, somehow.
To fix issue #278 I did a rebuild of the xca-2.4.0 sources for macOS without xca code change, but with Qt sql driver plugins
and updated the DMG on github.
See e0dc4446c52b29dcaa3d110db16666de9e1dd09a

**Comment by urda** [comment]
@chris2511 can the brew formula not be updated to match the expected SHA of `a5672fd46168b8d81c226dc47dd0022773382389291676c8aa17d6765e20b697 ` ?

**Comment by chris2511** [comment]
@urda to increase confusion, I changed the binary again.
It was not backwards-compatible to older macOS Releases (High-Sierra and up)
Please see: 267bf4f8f8dc8dd15fe4a36e12d1d922da4bd064 and #281 

> can the brew formula not be updated to match the expected SHA

It probably can, but I have no control over it. It just happens magically :-)
I never cared. I assume, somebody does it after receiving an xca github-release-notification?

**Comment by cmeh** [comment]
I've updated the expected sha256 checksum for xca's DMG in its brew formula by [this PR](https://github.com/Homebrew/homebrew-cask/pull/105751).

**Comment by urda** [comment]
@cmeh thanks for stepping up and helping to correct the issue￼

**Comment by urda** [comment]
@cmeh works great thanks

```bash
$ brew install xca
==> Downloading https://github.com/chris2511/xca/releases/download/RELEASE.2.4.0/xca-2.4.0.dmg
==> Downloading from https://github-releases.githubusercontent.com/649898/e81a3f00-b4d5-11eb-9422-c323138527af?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-
######################################################################## 100.0%
==> Installing Cask xca
==> Moving App 'xca.app' to '/Applications/xca.app'
🍺  xca was successfully installed!
```
