### ISSUE TITLE
xca 2.4.0 breaks macOS Mojave compatibility

### ISSUE THREAD

**Issue by HackintoshHD** [chris2511/xca#281]
The published build of xca 2.4.0 has obviously not been compiled with macOS 10.14.6 as a target, it states macOS 10.15 Catalina has become the minimum system requirement:
![xca 2 4 0 on Mojave](https://user-images.githubusercontent.com/2894628/118180601-02e9a680-b437-11eb-9ea2-9ab731b4cabe.png)

However, if you launch `/Applications/xca.app/Contents/MacOS/xca` manually, the application is executed without a glitch and the only visible sign of the problem described above is the striked-through app icon. I therefore assume raising the minimum OS requirement was unintentional.

Would it be possible to compile for Mojave again? - Thank you very much.

**Comment by chris2511** [comment]
Messed it up while fixing #278.
I'll try again tomorrow to fix #278 and this one at the same time.
Wish me luck!

**Comment by HackintoshHD** [comment]
Thank you very much for this swift reply and I definitely wish you all luck I can (also in my own interest 😁).

**Comment by HackintoshHD** [comment]
Thank you very much, I confirm it's now executable on Mojave again.
