### ISSUE TITLE
template don't save/restore correctly

### ISSUE THREAD

**Issue by Akuna-Tarata** [chris2511/xca#287]
Hi , 
after loading database, importing templates or duplicating them, the name of the templates are changed to the name of the mailaddress. Editing them isn't saved in the database:
Using Version: 2.4.0

Example:
The order:
1. Import templates
2. Change templates ("Internal Name" and "organizationalUnitName")

![2021-05-28 23_49_39-Window](https://user-images.githubusercontent.com/18229980/120045450-51d73480-c010-11eb-9843-2ce753ccb456.jpg)
![2021-05-28 23_45_03-Window](https://user-images.githubusercontent.com/18229980/120045453-53086180-c010-11eb-92e9-59c16d6ffd71.jpg)

3. Close database
4. Load database - "Internal Name" of all Templates is changed to "emailAdress"

![2021-05-28 23_33_17-Window](https://user-images.githubusercontent.com/18229980/120045456-53086180-c010-11eb-9732-540979f4bccf.jpg)
![2021-05-28 23_32_40-Window](https://user-images.githubusercontent.com/18229980/120045457-53a0f800-c010-11eb-8dc2-61b0c44ed731.jpg)

This is a new behaviour. I regularly used templates and this never happened in old versions

**Comment by Akuna-Tarata** [comment]
Creating a new template is working.
But importing or even duplicating is leading to strange behaviour in "Internal Name".

**Comment by markuslf** [comment]
Same here: If you create a template and import it into a new database, "Internal name" is taken from "emailAddress" (in previous versions "filename" was used, which was the perfect choice). If you overwrite the "Internal name", the new name isn't saved.

Version: 2.4.0, Working with Remote Databases
Compile time: | OpenSSL 3.0.0 7 sep 2021 | QT version: 5.15.2
-- | -- | --
Run time: | OpenSSL 3.0.5 5 Jul 2022 | QT version: 5.15.5
