### ISSUE TITLE
Compile errors on RHEL8

### ISSUE THREAD

**Issue by scylla999** [chris2511/xca#290]
Can't seem to compile on RHEL8 or CentOS8:

./bootstrap
make

configure:      ***************************************************
configure:      *   X Certificate and Key management 2.4.31
configure:      ***************************************************
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for strip... strip
checking for windres... no
configure: Compiling for host: LINUX
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for OpenSSL... yes
checking for Qt5... no
checking for Qt6... no
configure: WARNING: Qt pkg-config failed, using fallback defaults ( -lQtCore -lQtGui )
checking for lrelease-qt... /usr/lib64/qt5/bin//lrelease-qt
checking for lconvert-qt... /usr/lib64/qt5/bin//lconvert-qt
checking for rcc-qt... no
checking for rcc... /usr/lib64/qt5/bin//rcc
checking for qcollectiongenerator... no
checking for qcollectiongenerator... qcollectiongenerator
checking for lt_dlopen in -lltdl... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking ltdl.h usability... yes
checking ltdl.h presence... yes
checking for ltdl.h... yes
Unable to execute a freshly compiled application, maybe you have to adjust your LD_LIBRARY_PATH or /etc/ld.so.conf
checking for GNU make... make
configure: A usable 'make' executable was found in /usr/bin/make
checking for sphinx-build... no
configure: creating ./config.status
config.status: creating Local.mak
config.status: creating misc/Info.plist
config.status: creating misc/variables.wxi
config.status: creating doc/conf.py
config.status: creating local.h
config.status: local.h is unchanged
  GEN    commithash.h
  CC     [lib] db_crl.o
In file included from db_base.h:12,
                 from db_key.h:11,
                 from db_x509super.h:12,
                 from db_crl.h:11,
                 from db_crl.cpp:9:
base.h:18:10: fatal error: qglobal.h: No such file or directory
 #include <qglobal.h>
          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [/home/install/xca/Rules.mak:34: db_crl.o] Error 1
make: *** [Makefile:90: lib/.build-stamp] Error 2

**Comment by chris2511** [comment]
>  configure: WARNING: Qt pkg-config failed, using fallback defaults ( -lQtCore -lQtGui )

indicates the problem...

After the 2.4.0 release I dropped the qt4 support. If compiling worked in the past, you should checkout the RELEASE.2.4.0 tag.
Otherwise you need to install the "qt5-devel" package, me thinks.

**Comment by scylla999** [comment]
It's installed:
 rpm -qa | grep qt5
qt5-rpm-macros-5.12.5-3.el8.noarch
qt5-srpm-macros-5.12.5-3.el8.noarch
qt5-qtbase-gui-5.12.5-8.el8.x86_64
qt5-qtbase-postgresql-5.12.5-8.el8.x86_64
qt5-qttools-common-5.12.5-3.el8.noarch
qt5-qtbase-common-5.12.5-8.el8.noarch
qt5-linguist-5.12.5-3.el8.x86_64
qt5-qtbase-5.12.5-8.el8.x86_64
qt5-qtbase-mysql-5.12.5-8.el8.x86_64
qt5-qtbase-devel-5.12.5-8.el8.x86_64
qt5-qtsvg-5.12.5-1.el8.x86_64

**Comment by dogukancagatay** [comment]
That error was fixed by installing `qt5-qttools-devel` for me.

**Comment by scylla999** [comment]
@dogukancagatay   That did the trick!   Thank You so much.

**Comment by sahsanu** [comment]
@dogukancagatay thank you. I came here because of the same error but in Ubuntu 20.04 so you gave me the clue for the right package to install in my system and in Ubuntu/Debian it is **qttools5-dev**
