### ISSUE TITLE
MacOS - Can't load pkcs11 module - file not found, but file exist. Xca 2.3 works great

### ISSUE THREAD

**Issue by linusklan** [chris2511/xca#292]
Hi.

Look at screens, is error: "File not found"
![image](https://user-images.githubusercontent.com/44973805/121157716-11ff2100-c84a-11eb-9580-4d36adc1d26d.png)

Xac 2.3 is working fine
![image](https://user-images.githubusercontent.com/44973805/121158036-57235300-c84a-11eb-9f5b-bc41b382d633.png)

I found an error in the "Console" application
Library Validation failed: Rejecting '/Users/Shared/e-dowod-sdk-64.dylib' (Team ID: none, platform: no) for process 'xca(1660)' (Team ID: HWR8GSJ73M, platform: no), reason: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

I noticed that the new Xca is signed, do pkcs11 modules therefore also have to be signed?

I downloaded the version from here: https://github.com/chris2511/xca/releases/download/RELEASE.2.4.0/xca-2.4.0.dmg

**Comment by florian-schramm-gcx** [comment]
I have the same issue. Any news about a possible solution?

**Comment by linusklan** [comment]
@chris2511 , Coud you add entitlements.xml file:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.cs.disable-library-validation</key>
	<true/>
</dict>
</plist>

and add "entitlements.xml"  it in Makefile:
CODESIGN=codesign --deep --signature-size=96000 --options=runtime --timestamp --entitlements entitlements.xml


This will allow pkcs11 libraries to be loaded from other developers when the application is signed.
