### ISSUE TITLE
The following error occurred: unable to open database file Error opening database

### ISSUE THREAD

**Issue by alecgerona** [chris2511/xca#297]
Fresh install on PopOS 20.10 via flatpak. Creating and opening a database both don't work.

**Comment by marek22k** [comment]
For me too.

**Comment by evakhoni** [comment]
same error trying to create new db under $HOME, however $HOME/Documents/ succeeded.

**Comment by chris2511** [comment]
Probably fixed: https://github.com/flathub/de.hohnstaedt.xca/issues/1
Please report XCA flatpak issues in that repo.
