### ISSUE TITLE
Debian Build Oddness: Lots of errors, missing files

### ISSUE THREAD

**Issue by teward** [chris2511/xca#299]
During attempts to build 2.4.0 in Debian, we get a lot of error messages showing up:

> error: missing binary operator before token "("

This shows up in a ton of places with QT_VERSION_CHECK references.

As a result of these, QT version components are not being imported (QVariant, QString, etc.) and causing hard compiling failures in the build system.

Attached is the full build output from a Debian Unstable environment:
[xca_2.4.0-1_amd64-2021-07-19T18:28:38Z.build.txt](https://github.com/chris2511/xca/files/6843164/xca_2.4.0-1_amd64-2021-07-19T18.28.38Z.build.txt)

(Only took me forever to get to this due to FT Job stuff)

**Comment by linusklan** [comment]
QT_VERSION_CHECK is in QtCore developer package

You don't have  Qt Developer package installed, or Qt developer package does't have pkg-config

please look here:
> checking for Qt5Core >= 5.0 Qt5Widgets >= 5.0 Qt5Sql >= 5.0 Qt5Help >= 5.0... no
!!! You don't have Qt5 !!!

> checking for QtCore >= 4.7 QtCore < 5.0 QtGui >= 4.7 QtGui < 5.0 QtSql >= 4.7 QtSql < 5.0 QtHelp < 5.0... no
!!! You don't have Qt4 too.

> configure: WARNING: Qt pkg-config failed, using fallback defaults ( -lQtCore -lQtGui )

**Comment by teward** [comment]
> QT_VERSION_CHECK is in QtCore developer package
> 
> You don't have Qt Developer package installed, or Qt developer package does't have pkg-config
> 
> please look here:
> 
> > checking for Qt5Core >= 5.0 Qt5Widgets >= 5.0 Qt5Sql >= 5.0 Qt5Help >= 5.0... no
> > !!! You don't have Qt5 !!!
> 
> > checking for QtCore >= 4.7 QtCore < 5.0 QtGui >= 4.7 QtGui < 5.0 QtSql >= 4.7 QtSql < 5.0 QtHelp < 5.0... no
> > !!! You don't have Qt4 too.
> 
> > configure: WARNING: Qt pkg-config failed, using fallback defaults ( -lQtCore -lQtGui )

Interesting, since we pull in qt5core-dev which already would include it.  Especially because we see these packages pulled in:

 * libqt5gui5
 * libqt5core5a
 * Every other package that gets pulled in by gt5core-dev and these, which are all Qt dependencies which had built *fine* in the previous version of XCA:

```   libqt5core5a libqt5dbus5 libqt5designer5 libqt5designercomponents5
  libqt5gui5 libqt5help5 libqt5network5 libqt5positioning5 libqt5printsupport5
  libqt5qml5 libqt5qmlmodels5 libqt5quick5 libqt5quickwidgets5 libqt5sensors5
  libqt5sql5 libqt5sql5-sqlite libqt5test5 libqt5webchannel5 libqt5webkit5
  libqt5widgets5 libqt5xml5
```

I should also point out this is the Debian packaging, not a random 'from source' build.  This is the first time these errors and the NUMEROUS header check "missing binary operator" errors have appeared.

**Comment by sahsanu** [comment]
@teward I had the same errors in Ubuntu 20.04 but I solved them installing package **qttools5-dev**. Once installed I could compile it without errors.

**Comment by teward** [comment]
> @teward I had the same errors in Ubuntu 20.04 but I solved them installing package **qttools5-dev**. Once installed I could compile it without errors.

You basically said the same thing the other person said, which pulled in the dependencies.  Hence the question "what's going on here".

**Comment by teward** [comment]
> @teward I had the same errors in Ubuntu 20.04 but I solved them installing package **qttools5-dev**. Once installed I could compile it without errors.

Derp, makes sense.

HOWEVER, the configure script would do better by attempting to test for each of these independently and then yes/no error or not.  This error is resolved now, but we need to worry about OpenSSL 3 now.
