### ISSUE TITLE
XCA OSX backward compatibility.

### ISSUE THREAD

**Issue by rvalle** [chris2511/xca#30]
installing XCA is reporting that it requires latest OSX version.

is there any particular reason for that? 

I have some macs with Yosemite, El Capitan, etc. are they not supported?

**Comment by peterkelm** [comment]
Update: Same applies to version 1.4.1

**Comment by chris2511** [comment]
Probably because i updated my MacBook Air to High Sierra recently.
I think I need to install a 10.10 SDK, but looks like the XCode-cmd-line-tools don't support downloading other SDKs and the full blown Xcode requires more gigabyte > 10 than currently available on my Mac :-(

Do you have a hint?

**Comment by iqt4** [comment]
Running 'El Capitan' and can't even open the .dmg since 1.4.1 :-(
Sorry, can't help with Xcode. But I had similar version issues with another software (https://github.com/GNS3/gns3-gui/issues/2317).  May those developers can help out?!

**Comment by rvalle** [comment]
@chris2511 I dont't know. I am just surprised that apple is generating non-backwards compliant binaries for "simple" applications. I mean, is not like XCA uses the latest APIs or capabilities, etc

My macbook is a bit old, and I don't want to update becase I fear that will make it totally obsolete.
Anyway, I have installed XCA in a Raspberry pi, with Ubuntu mate.

 I works fantastically, and supports PKCS11, HW tokens etc.

**Comment by peterkelm** [comment]
@chris2511: Maybe booting from an external USB drive (that has sufficient space)?
Our machines are on 10.12.x still but I haven't used Xcode in ages...

**Comment by chris2511** [comment]
I tried to get information how to install older SDK.
I tried to download an older XCode with a 10.11 SDK, but

> _Your Apple ID must be associated with a paid Apple Developer Program or Apple Developer Enterprise Program to access certain software downloads._ 

I already pay enough for code-signing certificates, web-space, SSL certificate to provide software for free. Spending another annual $100 to release XCA for mac for free (probably just to find out that it did not help either) does not sound smart to me.
Even though i could use the app store then, i think - and I will have a valid mac-code-signing cert, possibly.

**Comment by peterkelm** [comment]
@chris2511, it is evident that this would not be an option.

I haven't touched Xcode for a number of years now but took a few minutes to research this issue. The xcodelegacy might be worth a look: https://github.com/devernay/xcodelegacy

Additional information from Apple on how to set the deployment tagte in Xcode: https://help.apple.com/xcode/mac/current/#/deve69552ee5

After installation `xcodebuild -showsdks`should list the selected SDKs.

FYI: I was able to download older Xcode versions (that include the SDKs in question) without issue using my free Apple developer account. I would be surprised if Xcode downloads are no longer free...

**Comment by chris2511** [comment]
After reading a little more, I stumbled over the _CFLAG  -mmacosx-version-min=10.10_
Can it be that easy?? :-)
Please try http://xca.hohnstaedt.de/downloads/xca-2.0.1+Yosemite.dmg

**Comment by iqt4** [comment]
I can't open the xca-2.0.1+Yosemite.dmg. Reason: "Keine aktivierbaren Dateisysteme"

**Comment by chris2511** [comment]
Oh.

**Comment by chris2511** [comment]
.. will investigate, soon ..

**Comment by chris2511** [comment]
Downloaded http://xca.hohnstaedt.de/downloads/xca-2.0.1+Yosemite.dmg,
double clicked it and it opened successfully...

MD5 (Downloads/xca-2.0.1+Yosemite.dmg) = a0d26225866c38174583a7155bd3a0ad

**Comment by peterkelm** [comment]
@chris2511, I had no problem downloading and mounting the xca-2.0.1+Yosemite.dmg disk image referenced above on Mac OS X 10.12.6 (16G1314). 

However, the app fails on launch with a dyld error for a missing library:

Termination Reason:    DYLD, [0x1] Library missing

Dyld Error Message:
  **Library not loaded: @rpath/QtGui.framework/Versions/5/QtGui
  Referenced from: /Volumes/VOLUME/*/xca.app/Contents/MacOS/xca
  Reason: image not found**

Process:               xca [12024]
Path:                  /Volumes/VOLUME/*/xca.app/Contents/MacOS/xca
Identifier:            de.hohnstaedt.xca
Version:               2.0.1+ (2.0.1+)

Does that ring a bell?

**Comment by chris2511** [comment]
No, not really.
I mounted it and looked at:
/Volumes/xca-2.0.1+/xca.app/Contents/Frameworks/QtGui.framework
There is a "QtGui" file.

You may check the libraries referenced by QtGui with the "otool" command
In the "/Volumes/xca-2.0.1+/xca.app/Contents/Frameworks/QtGui.framework" directory:

otool -L QtGui | grep ' .*' | sed 's/@rpath/../' | while read a b; do ls $a || echo NO FILE $a $b; done

**Comment by iqt4** [comment]
Just to summarize. I'm running 10.11.6 and can't update OS X. 
v1.3.2 - ok
v1.4.0 - Message 'You need OS X 10.12 or newer
v1.4.1 and newer - I can't open the DMG

**Comment by j3g** [comment]
+1 to discovering this issue
thanks for troubleshooting with us

**Comment by klanomath** [comment]
The final dmg created in High Sierra is formatted to APFS and can't be read with additional tools in macOS versions lower than 10.12.x (I don't remember what x is, I think it's 4). 

A (free) retrofit kit to read APFS volumes in 10.10-10.12 is available here: http://dl.paragon-software.com/free/Paragon-1218-FRU_MacInstallUnlock_1.0.164.dmg 

A hfs+ dmg is preferred though ;-)

**Comment by chris2511** [comment]
Commit message said:

> Partially fix #30: XCA OSX backward compatibility
Reopen

**Comment by chris2511** [comment]
How's the state of this? Does the 2.1.1 DMG work for you?
With 0c8df14b7e7e1f5b2366a462daa2efabb834ecd0 for 2.1.0 
I added a MacOSX build switch `CFLAGS="-mmacosx-version-min=10.10"` to be Yosemite compatible. However, I have no Yosemite MAC to test.

**Comment by peterkelm** [comment]
@chris2511, mounting the xca-2.1.1.dmg disk image and launching xca works fine on macOS Sierra 10.12.6 (16G1510).

Thanks a million!

**Comment by chris2511** [comment]
Seems to be fixed. If anyone thinks different, please reopen.
