### ISSUE TITLE
XCA-specific 'variables' in create certificate dialog?

### ISSUE THREAD

**Issue by tedd-wq** [chris2511/xca#301]
I noticed in the default TLS server template, the subject alternative name gets filled with "DNS:copycn". It seems this is a variable XCA uses to copy the common name to the SAN. I tried searching the online manual, but couldn't find any reference to this.

Is this documented anywhere and are there any other variables we can use?

**Comment by chris2511** [comment]
It is pretty undocumented. There is only the detailed commit message 22966937de709c0aeff8638fe4c4078480887cd9
Otherwise there are only the openssl specials `email:copy` / `issuer:copy` as described in https://www.openssl.org/docs/man1.1.1/man5/x509v3_config.html

**Comment by chris2511** [comment]
DNS:copycn now documented: da42acdc6ab7f592cca8f08e12a5b5191c9a373a
