### ISSUE TITLE
TLS connection to remote MySQL database do not work

### ISSUE THREAD

**Issue by jonathanmarsaud** [chris2511/xca#306]
Hi,

It seems that XCA does not have any TLS connection to MySQL when used in Remote Database.  
I used [this documentation](https://hohnstaedt.de/xca/index.php/documentation/remote-databases) to deploy it, and as soon as I enable `require_secure_transport=ON` on my MySQL server, I cannot connect to it with an error:

```raw
Connections using insecure transport are prohibited while -- require_secure_transport=ON.
QMYSQL: Unable to connect
```

Or even without `require_secure_transport=ON` (so `OFF`) if I `ALTER USER 'myuser'@'%' REQUIRE SSL;` I cannot longer log with error:

```raw
Access denied for user 'myuser'@'1.2.3.4' (using password: YES)
QMYSQL: Unable to connect
```

I didn't test it on Linux, but the Documentation seems to say that it works, even if `ssl-verify-server` is not possible because of Qt MySQL driver. The rest, TLS transmission, should operate.

Have you any clues about this. Is it specific to macOS? For information I'm using macOS Big Sur 11.5.2 on Apple Silicon chip (M1), so XCA is launched through Rosetta 2 since it's still a x86_64 binary in the `.dmg`:

```raw
$ file /Applications/xca.app/Contents/MacOS/xca
xca: Mach-O 64-bit executable x86_64
```

```raw
XCA

ECC With RFC 5639 Brainpool curves

Version: 2.4.0
OpenSSL: 1.1.1k 25 Mar 2021
Qt: 5.15.2
```

Thanks!

**Comment by tisully** [comment]
Hi,
I also try to do a connection to a remote XCA with TLS connection on MySQL and I have the same problem as mentioned by @jonathanmarsaud. I test it on Linux with a `Fedora 33` with the following XCA info:
```
XCA v2.3.0
OpenSSL:  1.1.1k FIPS 25 Mar 2021
Qt:  5.15.2
```
Thanks

**Comment by jonathanmarsaud** [comment]
Any updates on this issue?
