### ISSUE TITLE
[Feature request] Add JWK export

### ISSUE THREAD

**Issue by t-arn** [chris2511/xca#313]
Please add following feature to XCA, similar to what this tool here does: https://russelldavies.github.io/jwk-creator/

* Export the public key of a certificate as a JSON Web Key (JWK)
   This should also include the optional attributes x5c, x5t and x5t#S256 as specified in rfc7517

* Export a private key as a JSON Web Key (JWK)

**Comment by EmperorArthur** [comment]
Thank you!

This is vital when dealing with many modern protocols.  Like Open ID Connect. Especially in an enterprise environment where we are mandated to work with custom software that doesn't support auto-discovery.
