### ISSUE TITLE
[Feature Request] Support UPN type for EAP/802.1X certificates

### ISSUE THREAD

**Issue by DraugurHundur** [chris2511/xca#315]
When you use EAP-TLS/802.1.X and others on Microsoft OSes, the Subject Alternative Name in the certificate must contain a User/Universal Principal Name (UPN) (e.g. user@windows.domain or computer$@windows.domain), this is currently possible with XCA if you use the following syntax for the SAN:

`otherName:1.3.6.1.4.1.311.20.2.3;UTF8:user@windows.domain`

or slightly easier to read

`otherName:msUPN;UTF8:computer$@windows.domain`

It would be great if we can have a UPN type available in XCA and use a much simpler syntax such as  `UPN:user@windows.domain`

**Comment by ciscohack** [comment]
+1 
please include the UPN field  feature in future xca update
