### ISSUE TITLE
"Manage Security token" does not list any private keys

### ISSUE THREAD

**Issue by bluecmd** [chris2511/xca#318]
Hi,

I am using XCA 2.4.0.

I am trying to re-import a private key using the "Manage Security token" dialog. However, it only shows the public key and the certificate object. If I use `pkcs11-tool -O`, those are the objects that are displayed - but if I also pass `--login --pin XYZ` the private key object is shown.

Is it possible to tell XCA to login on the token when managing the security objects?

**Comment by chris2511** [comment]
XCA expects for every public key a private key object to be available on the token. This is used when required for signing.

https://hohnstaedt.de/xca-doc/html/smartcard.html#key-management-on-the-token

It is of course possible to implement a login via pin during management, but why is it necessary?

**Comment by bluecmd** [comment]
Ah, so importing the public key would lead to adding a private key reference? I see, that's pretty neat. The issue can be closed if that's correct.
