### ISSUE TITLE
Alloc/dealloc mismatch (main branch)

### ISSUE THREAD

**Issue by melg8** [chris2511/xca#329]
Hi, @chris2511 I'm really impressed by your work on xca!
I found small issue with allocation/de-allocation mismatch.

## Problem
Memory allocated for array of elements with type `struct option` is here:
https://github.com/chris2511/xca/blob/72ab898db70405fc30bbfd6ebfeb0f46f6b13aff/lib/arguments.cpp#L243

But then `long_opts` is getting deleted as single pointer to value, and not as heap allocated array of elements:
https://github.com/chris2511/xca/blob/72ab898db70405fc30bbfd6ebfeb0f46f6b13aff/lib/arguments.cpp#L314

## Solution
Proper way to delete it would look like that:
``` C++
    delete[] long_opts;
```
You can spot this issue by running xca under valgrind. Hope it helps!

Btw, if you interested, i can try and explore other memory related issues and report it back.

**Comment by melg8** [comment]
@chris2511 I've opened #331, #332, #333. I want to use xca repo as playground for improving my QA/refactoring/code modernization skills. But if review/merge process will be not very hard/long, i think i can add some value to the main repo. For example, i have plans for fixing some/all compiler warnings in xca. Should i try to add them as merge requests too? Should i split them on per warning basis?

**Comment by chris2511** [comment]
Thanks for your work. Any support and fixes are very appreciated and will be merged happily.

Please be careful when fixing the deprecation warnings, to keep XCA compatible with Qt 5.0.0 and OpenSSL 1.1.1

e.g. https://doc.qt.io/qt-5/qhelpenginecore.html#documentsForIdentifier - This function was introduced in Qt 5.15.
