### ISSUE TITLE
Collaborative use of a MySQL or PostgreSQL backend?

### ISSUE THREAD

**Issue by git-madresc** [chris2511/xca#338]
Just figured out, you now support remote DBIs, which is great. Is this a simple data storage thing or do you actually do some locking in there, that two or more persons can use XCA concurrent?

**Comment by chris2511** [comment]
There are measures to make XCA collaborative with remote SQL databases.

1. Database updates are performed within a transaction.
2. Each update increments a stamp on the changed items (items table)
3. XCA regularly polls for stamp changes made by others and reloads the items.
