### ISSUE TITLE
Wrong certificate chain order in exported PKCS#12 with chain

### ISSUE THREAD

**Issue by lemielek** [chris2511/xca#339]
Versions tested 2.1.2 and 2.4.0.

When I do export certificate with chain to PKCS#12 .p12 file  OpenSSL shows bad order in that file.
openssl pkcs12 -info -in cert_file.p12

For example:
key
certficate
root CA
intermediate CA 1
intermediate CA 2

So I had to export key and certificates chain to pem and build p12 file from them with this:
openssl pkcs12 -export -in certificate_chain_exported_from_xca.pem -inkey certificate_key.pem -out certificate_v2.p12

And test with that show correct order in chain:
openssl pkcs12 -info -in certificate_v2.p12
certficate
intermediate CA 2
intermediate CA 1
root CA

and key of course in proper place.

Could you sort it in that order?
Or in better way if it is needed.

I do not have any cross certificates to check, so I do not know how it should look with them.

Rafal

**Comment by urda** [comment]
I can also confirm issues with the "`PEM chain (*.pem)`" option myself with my chain being in a "reversed" order. Flipping the chain myself corrected my import for a Synology server. 

It looks https://github.com/chris2511/xca/blob/main/lib/db_x509.cpp has had some work on it recently if that helps maintainers?

**Comment by urda** [comment]
Possible close-relation to #309 ?

**Comment by chris2511** [comment]
Clients should not depend on the order of CA certificates in the PKCS#12 or PEM file.
Works as described as expected behavior in the initial comment with 2.7.0.
I did not change anything, though.
