### ISSUE TITLE
Cannot open network database

### ISSUE THREAD

**Issue by pc-bastler** [chris2511/xca#344]
Hi,

I installed XCA 2.4.0 on my Debian Bullseye (KDE Plasma) via the flatpak installer.

I cannot open my network database, the option for opening nw-dbs is greyed out.

How can I get it to work, which addtl. packages do I need?

Best wishes

**Comment by joestr** [comment]
I experience the same issue. Just installed from flatpak and "Open Remote database" is greyed out.

![Screenshot picturing XCA](https://i.imgur.com/EEbNX7D.png)

**Comment by chris2511** [comment]
https://github.com/chris2511/xca?tab=readme-ov-file#sql-remote-database-drivers
