### ISSUE TITLE
please include the authority key identifier in CRLs by default

### ISSUE THREAD

**Issue by harridu** [chris2511/xca#345]
Reading RFC3280 I had the impression that the authority key identifier is *not optional* in a CRL (https://www.ipa.go.jp/security/rfc/RFC3280-05EN.html#521). Anyway, it shouldn't hurt to include it by default.

**Comment by chris2511** [comment]
Implemented by 9da73073c8d24cf630523db43ffb4f47b5104a7d for 2.4.0

**Comment by harridu** [comment]
Thank you. I highly appreciate your work on xca.
