### ISSUE TITLE
Can't use Yubikey PIV for signing

### ISSUE THREAD

**Issue by FinlayDaG33k** [chris2511/xca#357]
Hii there,

I'm trying to move away from the CA I currently have in software to the one offered by my YubiKey over PIV.  
However, after I import my "Digital Signature" keys through the `Token` -> `Manage Security Token` menu and try to create a new certificate, it doesn't show my imported YubiKey certificate, probably because it's not being marked at a CA.  

I can't, however, find what I'm doing wrong here, since there is no guide on how to do this.
Is this a bug or am I just doing something wrong?

![image](https://user-images.githubusercontent.com/13424273/168900274-79d1ad36-f066-4204-b277-6eabc3687634.png)
![image](https://user-images.githubusercontent.com/13424273/168900336-e8b48be4-39cc-4f23-9701-212b86174539.png)

**Comment by chris2511** [comment]
You can happily ignore all existing yubikey certificates and simply remove them from the XCA database.
You should use one of the Yubi-keys to create your own self-signed CA certificate in XCA.
Afterwards you can use this CA to issue other certs and the CA key is always on the token.
