### ISSUE TITLE
Unstable with domain search

### ISSUE THREAD

**Issue by HerroBert** [chris2511/xca#362]
Version 2.4 on Windows 10 64bit

xca gets unresponsive after running a while with a search string (search box) and database file is located on a net share,
I have 140 certificates, 840 csr and 170 keys stored.

**Comment by chris2511** [comment]
Probably fixed with #366 (Not Responding after upgrade)

**Comment by HerroBert** [comment]
Will be rolled out with next release?

**Comment by HerroBert** [comment]
push, this problem is very annoying...

**Comment by chris2511** [comment]
Please verify with 2.7.0, See #535 and #533

**Comment by HerroBert** [comment]
I have XCA 2.7.0 running for hours with colorized expired certificates. No problem so far...
