### ISSUE TITLE
  XCA 2.4.0 does not load OpenSC's PKCS11 library

### ISSUE THREAD

**Issue by n4al** [chris2511/xca#373]
I am running XCA 2.4 on macOS 11.6.8 with SmartHard-HSM token (OpenSC 0.22 driver). When I try to load the PKCS11 library that comes with OpenSC he following error message is printed:

8203 Debug: Failed to load PKCS#11 provider "/Library/OpenSC/lib/opensc-pkcs11.so"

There is no additional information to help troubleshooting. 

It used to work with 2.3.0. However, now 2.3.0 fails to start (it hangs on the password screen)

**Comment by florian-schramm-gcx** [comment]
Same issue for me. Is a fix for 2.4 planned?

**Comment by iqt4** [comment]
Same issue here. Can't load any PKCS#11 library on MacOS: file not found!

**Comment by FLWFTW** [comment]
Pinging this to see if there's been any follow ups. I have the same issue on Fedora 37: "Failed to open PKCS11 library: /usr/lib/libp11-kit.so: file not found"

**Comment by chris2511** [comment]
Tested with XCA-2.7.0:

On my "Apple M2" 15.0 (24A335) it works with opensc via "brew"
```
% file /opt/homebrew/lib/opensc-pkcs11.so    
/opt/homebrew/lib/opensc-pkcs11.so: Mach-O 64-bit bundle arm64
```

On my old intel MacBook Air it also works
with OpenSC-0.25.1 installed from OpenSC:
```
% file /Library/OpenSC/lib/opensc-pkcs11.so 
/Library/OpenSC/lib/opensc-pkcs11.so: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit bundle x86_64
- Mach-O 64-bit bundle x86_64] [arm64]
/Library/OpenSC/lib/opensc-pkcs11.so (for architecture x86_64):	Mach-O 64-bit bundle x86_64
/Library/OpenSC/lib/opensc-pkcs11.so (for architecture arm64):	Mach-O 64-bit bundle arm64
```
