### ISSUE TITLE
XDB File encryption method

### ISSUE THREAD

**Issue by afsilvasantos** [chris2511/xca#379]
Hi, 

I have a doubt. What is the encryption method used to store the private keys in the xdb files?

Thanks

**Comment by jonnycastaway** [comment]
Hello,
i have the same question.
In [this topic](https://github.com/chris2511/xca/issues/133#issuecomment-539549568) there is the information that nothing is encrypted in the database.
So i need a bit clarity!
Are the Private Keys encrypted in the Database and if yes, with which method?

**Comment by chris2511** [comment]
It is stored as PKCS#8 encrypted key with either the database password (or the individual password of the key).
The algorithm used is: `AES 256 cbc`
https://github.com/chris2511/xca/blob/27853766893c1ddb82948496ac3d043f98f3012e/lib/pki_evp.cpp#L679
