### ISSUE TITLE
Feature Request: Quick view of certificates without trying to open XCA

### ISSUE THREAD

**Issue by daniejstriata** [chris2511/xca#384]
I often use XCA to quickly view the content of a cert but after I'm done and close the window from my file explorer.
![image](https://user-images.githubusercontent.com/13314239/190089827-df896e40-db2b-4cf5-a056-fbca2fe64256.png)
It proceeds to try and open the defualt XCA database which I'd cancel and the finally cancel the main XCA window.
![image](https://user-images.githubusercontent.com/13314239/190090218-b456d42d-e299-4b2c-8e4f-d2a42d9f436a.png)
![image](https://user-images.githubusercontent.com/13314239/190090286-f770d6b2-7123-42ad-ace0-a2b799df0506.png)
![image](https://user-images.githubusercontent.com/13314239/190090364-1658a05a-3d7b-412b-82bd-2aab101b7e56.png)

Can XCA not terminate after closing the window or clicking on Done without having to click through all the windows once I'm done viewing the cert?

**Comment by gyles19** [comment]
I use File/Exit to explicitly close XCA and it doesn't do that.   When you terminate the app via the client window close button you're relying on your desktop display manager to communicate that action back to the application, and things can quickly go into the weeds given the plethora of different desktop window managers these days.

**Comment by daniejstriata** [comment]
@gyles19 At the time I'm experiencing the gymkhana trials to close, I'm inside my file explorer and casually viewing the certificate as I've assigned XCA to view it. XCA is not open at time and I have no need to open XCA and it's DB. I just want to quickly view the cert contents.
