### ISSUE TITLE
Remote database disabled when compiled from source on ubuntu 20.04

### ISSUE THREAD

**Issue by mbacicc** [chris2511/xca#385]
I tried compiling it on a Ubuntu 20.04 from the commit with SHA `dac8f97cc10e89542c4b825521368999f3bf02b2` following the procedure found on the readme.

Everything went smootly with the compilation and install process.

The app opens correctly, but the remote database option is gray.

![image](https://user-images.githubusercontent.com/46646960/192092127-1d37c359-fe72-420c-bd95-3c17517713b4.png)

I tried to set the db connection string from the command line with the verbose option and I obtain the following log:

```
$ xca --database xca@<db_host>/QMYSQL3:xca --verbose
   007 Warning: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-utente'
   008 Debug: DB open failed:  3
   008 Debug: pki_base::count 0
```

I copied the db string from a windows machine where there is the 2.4.0 version installed and I reversed the backslash on linux.

The remote db is working and reachable from the windows machine:

![image](https://user-images.githubusercontent.com/46646960/192092315-589a343f-88b8-40a6-8e28-50917fc9fceb.png)

I tried looking for cmake option, but I'm not an expert. Am I missing something?

Thank you for all your work!

**Comment by funked00** [comment]
I had the same problem. you need to install support for your type of database.
apt install libqt5sql5-psql
worked for me.
