### ISSUE TITLE
missing packages on "Install the dependencies" for Linux

### ISSUE THREAD

**Issue by MMS-RBKN** [chris2511/xca#387]
Hi. 
Thanks a lot for your work. 
I followed the installation steps for Linux with my Ubuntu 22.04. At the step 
Make: cmake --build build -j5
I get the error: "Builder name qthelp not registered or available through entry point".
For getting it working, I had to install the packages ""python3-pyside2.qthelp python3-sphinxcontrib.qthelp additionally.  I installed both together, so I cannot tell, whether one would have been enough. Maybe you'll add that on the manual. 

By the way: The build is allways showing 18%: 
> $ cmake --build build -j5
[ 18%] Automatic MOC and UIC for target xcadoc
[ 18%] Built target translations
[ 18%] Built target xcadoc_autogen
[ 18%] Built target xcadoc
[ 18%] Prepare Sphinx source directory
[ 18%] Built target manpage
[ 18%] Built target sphinx-src
[ 18%] Create HTML documentation
[ 18%] Built target sphinx-qthelp
[ 18%] Built target sphinx-qtcollgen
[ 18%] Built target sphinx-html
[ 18%] Automatic MOC and UIC for target xca
[ 18%] Built target xca_autogen
[ 18%] Create HTML documentation
[ 18%] Linking CXX executable xca
[ 18%] Built target xca
$ echo $?
0

Best regards.
Roberto

**Comment by funked00** [comment]
I had the same problem. It works for me after installing python3-sphinxcontrib.qthelp

**Comment by gyles19** [comment]
I had this last week, now I know what more to install. I wish a deb package for 2.4 was available, Ubuntu 22.04 is stuck with a 2.2 release.

**Comment by chris2511** [comment]
Fixed with fbc010a1f0511d4e069c21eea3396647c008edac
