### ISSUE TITLE
Generating CRL by command line blocked by gui-message

### ISSUE THREAD

**Issue by funked00** [chris2511/xca#388]
Hi,

I would like to generate a CRL time-controlled via the command line. My syntax is:
xca.exe --no-gui --database=xca@192.168.7.103/QPSQL:xca --sqlpass=file:xca_sqlpass --password=file:xca_password --crlgen="Root CA - G1" --pem -- print

Despite the --no-gui option, a window opens with the message "Successfully created the revocation list 'Root CA -G1'. The CRL is only output after a mouse click.

Best regards
Daniel

**Comment by chris2511** [comment]
For XCA 2.4.0 you could "Suppress success messages".
It is fixed in the next release.
