### ISSUE TITLE
Subject is not keeping its order when using dn - style subjects like email=a@b.c,cn=name,ou=ou2;ou=ou1,dc=comp,dc=be

### ISSUE THREAD

**Issue by lvandenb** [chris2511/xca#39]
for example it becomes

OU=Default Users,OU=Users,OU=Sck,DC=sck,DC=be,CN=Name

instead of CN=Name,OU=Default Users,OU=Users,OU=Sck,DC=sck,DC=be

**Comment by chris2511** [comment]
Hello,

I need more details. Please tell me how to reproduce.
Did it happen while signing a request, while creating a new certificate, during template editing or
while renewing a certificate, or when applying a template, or ... ?

**Comment by lvandenb** [comment]
Christian
This screenshots can help :
[cid:image001.jpg@01D403E4.D8F21E80]

After saving the template, and reopening, this becomes

[cid:image002.jpg@01D403E4.D8F21E80]

And using this template results in a (not working )subject like this :
OU=Default Users,OU=Users,DC=sck,DC=be,emailAddress=luc.vandenbroucke@sckcen.be,CN=Vandenbroucke Luc,OU=Sck

So every time I use the template, or create a certificate based on another,  I have to erase the settings on top of screen , and refill the list like the first screen, and then create the certificate.
This way it becomes like it should
emailAddress=luc.vandenbroucke@sckcen.be,CN=Vandenbroucke Luc,OU=Default Users,OU=Users, OU=Sck,DC=sck,DC=be


Thanks,
Luc Vandenbroucke
