### ISSUE TITLE
Question: hide expired and revoked certificates

### ISSUE THREAD

**Issue by gg3nx** [chris2511/xca#391]
Is there a way to hide expired and revoked certificates?
I would like to keep them but be able to hide them from certificates view.

**Comment by harridu** [comment]
metoo. Company policy requires to keep compromised keys and revoked certificates for evidence. Some toggle to show/hide them would be very helpful.

**Comment by Proger116** [comment]
Toggle to show/hide is a great idea, I thought about it for a long time
