### ISSUE TITLE
Key fingerprint as dnQualifier

### ISSUE THREAD

**Issue by igitlin** [chris2511/xca#396]
Can you add new feature
new feature
when creating a RSA key, generate its dnQualifier and save it. What would later be added to the dnQualifier field when creating a certificate. In some programs this is a required field.

**Comment by chris2511** [comment]
You can create the dnQualifier value from the `x509 SHA1` entry on the fingerprint tab of the key details.
`echo "0000 <x509 SHA1 Fingerprint>" | xxd -r | base64`
For example 
`echo "0000 A2:38:02:3A:A6:5A:8E:0E:C8:9E:B3:2A:4B:76:50:0C:38:96:A4:EF" | xxd -r | base64`

And then add it as additional subject entry dnQualifier when generating the certificate.

This is an assumption from reading https://stackoverflow.com/questions/64802057/openssl-dnqualifier-hash
Please approve and test it. XCA could then be extended to automate this.
