### ISSUE TITLE
Displayed private-key

### ISSUE THREAD

**Issue by Eldarion85** [chris2511/xca#397]
Hello,
if you open the database without a password, no private-key can be exported. If you click on the key, the details will open. Now the key is displayed in this window. The help says the key shown is encrypted with the database password. So far so good.
But when I change the database password and reopen the database, it shows the exact same key. What is that for a key that is displayed there even without the database password and how is it generated. If it encrypts the private key with the database password, it would have to change if the database password is changed. But that doesn't happen.

**Comment by chris2511** [comment]
The displayed key is the public part. In case of RSA the modulus. It is also part of the resulting certificate and not secret.
The private key is not required for displaying purposes and left encrypted in the database until it is needed to sign something.
Changing the database password re-encrypts all private keys with the new password.
