### ISSUE TITLE
3DES deprecated in OpenSSL 3.x

### ISSUE THREAD

**Issue by stone14z** [chris2511/xca#398]
For parsing pkcs12 files that have been encrypted using RC2 or DES or 3DES, the code 'OSSL_PROVIDER_load(NULL, "legacy");' must be called  before the PKCS12_parse API call otherwise an error is thrown.

It is not clear how to generate the PKCS12 file without using RC2 or 3DES as the encryption algorithm.  If this is supported, how is it invoked and if it is not supported can support be added?

**Comment by chris2511** [comment]
Fixed with 9b749d799bfdc2db6ecde3e163477a3a3724cc41
