### ISSUE TITLE
mark a key as being compromised, revoke all derived certificates

### ISSUE THREAD

**Issue by harridu** [chris2511/xca#399]
If a private key has been leaked, then it should be possible to mark it in xca and to revoke all derived certificates. Company policy might require to keep the compromised key and certificates in the database, but further usage (i.e. creating new certificates) must be prohibited. xca must not use bad keys.

In general it is almost impossible in xca to find the certificates derived from a specific key. This could be improved, but maybe I am too blind to see.

**Comment by chris2511** [comment]
On the certificate or request tab select the "Key name" column (right click on backround or column header)
and sort by "Key name" or enter the key name in the search bar below to reduce the certificate list
