### ISSUE TITLE
can't create a certificate valid for only 30 minutes

### ISSUE THREAD

**Issue by SvenRoederer** [chris2511/xca#4]
For some tests I'd like to create a certificate (renew an existing certificate) which is only valid for 30 minutes.
When I manually edit a sub-item of the date and time in the calendarPopup it instantly gets changed back to the value it had before.
This only happens, when "Local Time" is enabled.

My locale is "Deutschland" on a Windows7 host, running xca 1.4.0

**Comment by chris2511** [comment]
Hi Sven,

Congrats, you found a QT bug.

QDateTimeEdit with the format-string "yyyy-MM-dd hh:mm t" with 't' getting replaced by the timezone (CET in our case) results in the observed, strange behavior. I added the following workaround to XCA: 7d8cb0890871a0e43e73fa25e326fd44167cb859

    Christian

**Comment by chris2511** [comment]
You may use the following workarounds to set the time
- Set the time in UTC (and check by clicking "Local time")
- use the Up/Down keys. They work as expected even in "Local Time"

So I think You can create a certificate valid for only 30 minutes, right?

**Comment by chris2511** [comment]
Released with XCA 2.0.0-pre01
