### ISSUE TITLE
Create certificate for domain user using UPN

### ISSUE THREAD

**Issue by zuku81** [chris2511/xca#400]
Hi,
is any way to create cert for domain user where SAN = domain UPN like user@domain.local, I have tried put in SAN form something like:
otherName:1.3.6.1.4.1.311.20.2.3;UTF8:user@domain.local
but after certificate creation I have SAN < unsupported >

![image](https://user-images.githubusercontent.com/23002928/202921453-12a9129f-2b44-4146-8724-0b3e999ca276.png)

**Comment by karlo1941** [comment]
for microsoft computer (see symbol **$** must be):
subjectAltName=otherName:msUPN;UTF8:computerName$@example.com, DNS:computerName.example.com

for microsoft user:
subjectAltName=otherName:msUPN;UTF8:firstName.lastname@latloto.lv, email:firstName.lastname@latloto.lv


if open certificate with crypto shell extensions, you can see for computer certificates:
Other Name:
     Principal Name=computerName$@example.com
DNS Name=computerName.example.com

and for user certificates:
subjectAltName=otherName:msUPN;UTF8:firstName.lastName@example.com, email:firstName.lastName@example.com
Other Name:
     Principal Name=firstName.lastName@example.com
RFC822 Name=firstName.lastName@example.com

**Comment by chris2511** [comment]
See #315
