### ISSUE TITLE
User settings path is C:\program files\xca\settings instead of user appdata

### ISSUE THREAD

**Issue by gdei** [chris2511/xca#403]
On a fresh install of xca 2.40 on Win10 22H2, the user settings path as shown in the about dialogue is "C:\program files\xca\settings" which is not writeable by the user.

This leads to the recent file list being empty and not being able to set a file as default database.

I didn't find a way to change the settings path via configuration / install switches, but I remember this worked at some time before. However, it's broken since at least v 2.30

**Comment by chris2511** [comment]
Fixed with XCA 2.5.0, however I dont know which change exactly it was....
