### ISSUE TITLE
The key from file '' is incomplete or inconsistent, when attempting to generate a CSR with an ed25519 key

### ISSUE THREAD

**Issue by daleglass** [chris2511/xca#404]
This is from version 2.4.0, which should support this key type. It works just fine with RSA keys.

**Comment by tilman19** [comment]
I sadly get the same error on ED25519 keys when creating a certificate. 
Using the exact same settings with an RSA key (2048 bits) everything works as expected.

**Comment by chris2511** [comment]
Works for me on Windows and Mac OS with XCA 2.4.0.
What I did:
 - Click New Certificate
 - Apply TLS server extensions
 - Set common name
 - Click Generate Key
    - Select ED25519
    - (Key is successfully generated.)
 - Click apply
 - (Certificate is successfully generated)

`The key from file '' is incomplete or inconsistent` is an error, which is raised during import, but not while signing.

**Comment by redy01** [comment]
Same here,
I'm using TLS_client template.
As I remember it works on Ubuntu 20.04 but not on fedora 38

**Comment by WalterFaber** [comment]
Same issue here.
I can not create new certificates with ed25519 keys.

XCA 2.4.0
OpenSSL 3.0.2
Ubuntu 22.04

Is this fixed in 2.5.0?
Is there any workaround?

Thank you in advance for your help

**Comment by WalterFaber** [comment]
> Is this fixed in 2.5.0?

I can now answer it by myself: yes*

*built latest version according to documentation
