### ISSUE TITLE
Digital envelope routines:EVP_DecryptFinal_ex:wrong final block length

### ISSUE THREAD

**Issue by pandel** [chris2511/xca#413]
Hi!

While trying to sign a CSR with a password secured private key from the database, I get the following error message:

```
Der folgende Fehler ist aufgetreten:
(7pki_evp[4]:PrivKey)
error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length

(pki_evp.cpp:615)
```

I tried it with version 2.4.0 on Mac and on Windows. Same result.

What is happening here?

**Comment by mgilan** [comment]
I just found out I have the same issue on macOS. I'll have to test the Win and Linux versions next week.

**Comment by chris2511** [comment]
This error happens when entering a wrong password.
I really need to improve the message and behaviour.

**Comment by mgilan** [comment]
Sorry for the late reply. Anyway, the error really looked like that, and thanks to your confirmation, I found that I had a typo in password recordeds for my small CA 🙂 Thanks again!
