### ISSUE TITLE
PSKS12 without password cannot be imported

### ISSUE THREAD

**Issue by snevas** [chris2511/xca#416]
Dialog asks for password anyway. Cancel / empty input does nothing.

**Comment by snevas** [comment]
`openssl pkcs12 -info -in cert.p12 -nodes` displays certs and private key perfectly

**Comment by chris2511** [comment]
Can not reproduce with a PFX exported by XCA without password:
https://hohnstaedt.de/downloads/bogus-rootca.pfx works fine without asking for a password.
Tested with 2.4.0 and current `main`

**Comment by chris2511** [comment]
I assume, this is a duplicate of:  **Impossible to import PKCS#12 #460**
