### ISSUE TITLE
CRL don't get unique name anymore

### ISSUE THREAD

**Issue by geijt** [chris2511/xca#42]
In version 1.x every CRL that was created received a unique name using an incremental number that was added behind the 'Internal Name'. Now, in version 2.0.1 (Win), they don't get an unique name anymore. This makes them more difficult to find back, especially when the list with CRLs is long.

**Comment by chris2511** [comment]
Indeed, the numbered postfix of the name is gone.
You may use the "Date" column in the CRL view, reflecting the insertion/creation date or the "next Update" column to immediately find the most recent CRL.

**Comment by chris2511** [comment]
Won't fix
