### ISSUE TITLE
Importing keys from a token crashes if private key list is empty (Qt6 only)

### ISSUE THREAD

**Issue by Bobo1239** [chris2511/xca#424]
I've found a peculiar bug which, for whatever reason, only occurs with a Qt6 build. (so not with Qt5)

If I have a PKCS#11 token which has already has some keys and I try to import them (Token > Manage Security Token > Import (All)) and the key list is still empty (e.g. fresh database), then I get a crash in [this line](https://github.com/chris2511/xca/blob/2ba114d393e75a1a74ccde09fc9354d510813bd1/lib/db_base.cpp#L315) after clicking the Import button. If the key list is not empty, the crash doesn't occur. If it's a Qt5 build, the crash doesn't occur. Not sure if this makes any sense and I don't really know how Qt and can't tell if `beginInsertRows(idx, 0, 0);` is maybe wrong or not.

My setup:
- Arch Linux
- I force a QT6 build by removing `Qt5` from [here](https://github.com/chris2511/xca/blob/2ba114d393e75a1a74ccde09fc9354d510813bd1/CMakeLists.txt#L83)
- I can reproduce this using SoftHSM.

**Comment by chris2511** [comment]
Fixed with 02fc95c70bab2e364b30dac5e66500b6204831ca
