### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by jreo** [chris2511/xca#426]
![image](https://user-images.githubusercontent.com/33395101/236880875-89ab5779-8664-497c-8db5-df124193a619.png)

Ubuntu 22.04.2 LTS

cmake version 3.22.1

**Comment by chris2511** [comment]
`sudo apt install python3-sphinxcontrib.qthelp`

See https://gitlab.kitware.com/cmake/cmake/-/issues/22546
Will change the https://github.com/chris2511/xca/blob/main/README.md
