### ISSUE TITLE
Loading CRL at startup generates an error

### ISSUE THREAD

**Issue by Dehumanizer77** [chris2511/xca#437]
We have been running XCA successfully for past several years, however recently we started to experience this error on startup:
The following error occurred:
error:0680009B:asn1 encoding routines::too long
error:06800066:asn1 encoding routines::bad object header
error:0688010A:asn1 encoding routines::nested asn1 error

It appears there is a problem with certificate revocation list, when it gets loaded, it generates this error. When I create a new CRL, it shows up in the UI and the CRL is valid and can be used, however when I then close XCA and reopen it, I get the error and CRL does not show up. If I generate another CRL, then on startup I get this error twice. 
If I manually remove all CRLs from the mysql database, there is no error and of course no CRLs in the UI. 

There are 130 revoked certificates in the CRL, so I am thinking if something does not overflow after 128 revoked certificates?
It was working fine just up until recently.

**Comment by Dehumanizer77** [comment]
Thanks a lot! I'm ashamed that I didn't figure this out myself :-)

**Comment by chris2511** [comment]
https://en.wikiquote.org/wiki/Talk:Bill_Gates#640_k/1_MB

https://learn.microsoft.com/de-de/sql/t-sql/data-types/char-and-varchar-transact-sql?view=sql-server-ver16#varchar---n--max--

Probably `VARCHAR(max)` will do the trick ...

**Comment by AnonATXDO** [comment]
Does anything speak against using longtext here instead of VARCHAR?
