### ISSUE TITLE
CRL is always generating with SHA256 algorithm in 2.4

### ISSUE THREAD

**Issue by mahyarff** [chris2511/xca#443]
Hi
In version 2.4 I had faced an issue which trying to generate a CRL from a CA certificate with any hash algorithm in options, always results in a CRL with SHA256!
Then I downloaded 2.3.0 portable and above issue does not happened.

Another issue was CRL Number, which does not care about the number given in options and it always increase from previous crl number.

**Comment by chris2511** [comment]
Fixed (again) with current HEAD
