### ISSUE TITLE
Right click does not work

### ISSUE THREAD

**Issue by gregory112** [chris2511/xca#445]
All of a sudden, I cannot right click on anything and the context menu does not pop up. It does, only the first time right after opening xca. What should I do? The logs show nothing. I can no longer renew a certificate as the menu exists on the context menu by right clicking.

**Comment by gregory112** [comment]
I'm using Wayland, and force running it with wayland with `QT_QPA_PLATFORM=wayland` mode works I just tried. Maybe it's because XWayland.

**Comment by chris2511** [comment]
Cannot reproduce. XCA works fine with Xorg and Wayland here with debian bookworm
