### ISSUE TITLE
Show more information in Recent Databases

### ISSUE THREAD

**Issue by storm49152** [chris2511/xca#446]
This is a small feature request. I'm on XCA 2.4.0.

The `Recent Databases` submenu of the `File` menu will show a number of latest opened XCA databases; both file or remote databases.

When a remote database is used (MariaDB in my case), it will only show `QMYSQL3.xca`. This is not very helpfull when you have multiple of them, because they will all have the same name, and you'll have to guess which one to open.

In the `~/.xca/dbhistory` file, I see that the databases are stored in the form of: `<user>@<host>/QMYSQL3:xca`, which means more information is already available; it's just not shown.

I would like to request that the `<user>@<host>` part is shown instead of or in addition to just `QMYSQL3`.

**Comment by chris2511** [comment]
When hovering over the item a tooltip should show the whole path / descriptor.

**Comment by storm49152** [comment]
Yes. However, why can't the connection name be shown? Sure, I can hover over a menu item, but having multiple QMYSQL3 menu items looks a bit silly, since the connection information already exists to show in the tooltip. IMHO, showing the name of the connection is better, because then you immediately see which menu item you have to click.
