### ISSUE TITLE
2.4.233 exits immediately on macos

### ISSUE THREAD

**Issue by meermanr** [chris2511/xca#449]
[@chris2511  wrote](https://github.com/chris2511/xca/discussions/432#discussioncomment-5992487):
> You are very welcome to test those builds and report any issues

I tried both `macos-5.15.2` and `macos-6.5.1` from action [Fixup for a548227a073: install translation files again. · chris2511/xca@8983e50](https://github.com/chris2511/xca/actions/runs/5088625840) and found that they fix #309 (yay!) but that they don't open the GUI when launched.

When running from the terminal I see the following while the XCA icon briefly appears in the dock and then disappears as it exits:

```
meermanr@macos:/Applications/xca-beta-5.15.2.app/Contents/MacOS
@ uname -rm
22.6.0 arm64


meermanr@macos:/Applications/xca-beta-5.15.2.app/Contents/MacOS
@ file xca
xca: Mach-O 64-bit executable x86_64


meermanr@macos:/Applications/xca-beta-5.15.2.app/Contents/MacOS
@ ./xca --verbose
   001 Warning: QSqlDatabase: QPSQL driver not loaded
   001 Warning: QSqlDatabase: available drivers: QSQLITE QODBC QODBC3 QPSQL QPSQL7
   001 Warning: QSqlDatabase: QPSQL7 driver not loaded
   001 Warning: QSqlDatabase: available drivers: QSQLITE QODBC QODBC3 QPSQL QPSQL7
   001 Debug: NEW pki_base::count 1
   001 Debug: NEW pki_base::count 2
   001 Debug: NEW pki_base::count 3
   001 Debug: DEL pki_base::count 2
   001 Debug: DEL pki_base::count 1
   001 Debug: DEL pki_base::count 0
   001 Debug: pki_base::count 0
```

However, if I provide `--database` with a valid local file it launches fine:

```sh
/Applications/xca-beta-5.15.2.app/Contents/MacOS/xca --database certificates_xca.xdb
```

but outputs a bunch of warnings and a critical:

```
   001 Warning: QSqlDatabase: QPSQL driver not loaded
   001 Warning: QSqlDatabase: available drivers: QSQLITE QODBC QODBC3 QPSQL QPSQL7
   001 Warning: QSqlDatabase: QPSQL7 driver not loaded
   001 Warning: QSqlDatabase: available drivers: QSQLITE QODBC QODBC3 QPSQL QPSQL7
   203 Warning: Populating font family aliases took 77 ms. Replace uses of missing font family "Courier" with one that exists to avoid this cost.
   207 Critical: <QNSWindow: 0x7fd0748f3690; contentView=<QNSView: 0x7fd0748f3090; QCocoaWindow(0x6000037fd080, window=QWidgetWindow(0x60000248ea00, name="QLineEditClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
```

That said, the GUI seems to work "fine" as far as I can tell.

**Comment by meermanr** [comment]
BTW, what is the difference between the `macos-5.15.2` and `macos-6.5.1` builds?

**Comment by graaff** [comment]
I can second this behaviour on Linux: xca quits right away when started on the CLI, but works when given an existing database file.

**Comment by amette** [comment]
Same here on Gentoo Linux with 2.4.0.

**Comment by chris2511** [comment]
> BTW, what is the difference between the `macos-5.15.2` and `macos-6.5.1` builds?

They are the QT Versions used during compilation

**Comment by chris2511** [comment]
With current builds like https://github.com/chris2511/xca/actions/runs/6212531946 i cannot reproduce the issue.

**Comment by chris2511** [comment]
XCA 2.5.0 also runs fine on my MAC.
Reopen, if the issue still exists.

**Comment by graaff** [comment]
i can confirm that 2.5.0 on Linux now works as expected (shows the interface when started without arguments).
