### ISSUE TITLE
Unable to view Public Key

### ISSUE THREAD

**Issue by kalgecin** [chris2511/xca#45]
When opening a certificate for which I don't have a private key, the signature and key field are simply set as "Signer unknown" and "Not available" respectively, can you please add a way to see these fields? Would be very useful for reviewing other certificates

**Comment by chris2511** [comment]
The issuer certificate is really unknown and there is nothing XCA can do about.
The Distinguished name of the issuer is shown on the issuer tab.

The public key can be extracted by the context menu: Transform -> Public key
This will create a public key item in the "Private keys" tab, which can then be

- examined by double-click, or
- exported to the clipboard or a file, or
- used as key for a new certificate issued by one of the CAs in your database.

The public key of a CSR can be handled exactly the same way.

The CSR and certificate icons show a small key symbol if the private key is available.

Finally you may show the "Key name" column in the certificate tab to get the internal name of the key
displayed in the overview.

**Comment by kalgecin** [comment]
What about without importing the certificate. For example, I'm debugging a tls handshake and dump a PEM of the server certificate to a .pem file. I've set XCA as my default program to handle certificate file. XCA pops up a "X Certificate and Key management" window from which I can examine the certificate. So currently the only way is to import the certificate then examine it fully? wouldn't it make sense to add the public key information to the "Details" window? maybe a new tab?

**Comment by chris2511** [comment]
Damn, you're right :-)
