### ISSUE TITLE
Database Transaction initialization failed, with shared database on windows server

### ISSUE THREAD

**Issue by Yingliangzhe** [chris2511/xca#454]
Hello everyone, 

I use ubuntu 22.04 and from there I can open a shared database on windows server.
But I keep receiving the following error, as I created a new certificate. 

After configurating a new certificate, and clicking the OK button, it shows me a window, which says Database Transaction initialization failed. Does someone know, what is the problem? 

Also just after starting this application i also receive a message  "database is locked". After entering the password, it seems fine. But it will sometimes pop-up this window. 

Thank you in advance!

**Comment by chris2511** [comment]
https://www.google.com/search?q=sqlite+database+is+locked
```
If you are encountering the “SQLite database is locked” error, it means that the
database you are trying to access is already in use by some other process.
This can be caused by a number of different reasons, but the most common
cause is that another connection to the database has not been properly closed.
```

I strongly suggest to use a database server (SQL Server, PostgreSQL, ... ) when working on the same database from different hosts.
