### ISSUE TITLE
AIA, simultaneous OCSP and caIssuers

### ISSUE THREAD

**Issue by Forst** [chris2511/xca#46]
Currently, the AIA field in certificate extensions supports either OCSP or caIssuers parameter, it would be great if it was possible to specify both simultaneously.

<img width="720" alt="AIA certificate extension" src="https://user-images.githubusercontent.com/369699/42090397-ff0cb12e-7ba9-11e8-9990-1cfae3fc6816.png">

**Comment by Forst** [comment]
There is of course a way to do this by specifying advanced configuration for the certificate:

```
authorityInfoAccess = @aia_ext

[aia_ext]
caIssuers;URI.0 = http://ca.example.com/cert.crt
OCSP;URI.0 = http://ocsp.forstwoof.ru/
```

I think it would be nicer to provide this configuration in the user interface.

**Comment by fadlytabrani** [comment]
+1
