### ISSUE TITLE
Impossible to import PKCS#12

### ISSUE THREAD

**Issue by Makabane** [chris2511/xca#460]
I'm using the 2.5.0 portable version and when I want to import a certificate in PKCS#12 format, I select the file, enter the protection password and nothing happens when I validate.
I have to export my PKCS#12 in .key and .pem to import the two elements manually.

It works correctly with version 2.4.0 portable.

**Comment by chris2511** [comment]
For me it also works correctly with XCA-2.5.0-portable on Windows10.
Can you provide an example PKCS#12 file with test-key and cert, that does not work?
Gladly via private email.

**Comment by Makabane** [comment]
Damn!

I'm using Windows 11. Maybe that's the difference between our two environments?

I've tested with several PKCS#12 files and I've never been able to import them directly...
