### ISSUE TITLE
Version 2.5.0 - Export private key to the clipboard is not working 

### ISSUE THREAD

**Issue by Batnun** [chris2511/xca#462]
Hi,

When I go to the Private Keys tab, right-click on an entry, and select Export -> Clipboard, instead of the of the export options it just copy the **public key** to the clipboard... Export to a file is working as expected.

Regards

**Comment by chris2511** [comment]
This is because of security considerations.
The next item in the same context menu allows to change the Clipboard type to PKCS#8 or PEM Private

**Comment by Batnun** [comment]
Thanks, I've got it, but it's completely different from the previous version and not so user friendly...
