### ISSUE TITLE
XCA v2.5.0 PostgreSQL error Driver not loaded

### ISSUE THREAD

**Issue by Ben0it** [chris2511/xca#467]
**Environment :**

- Operating system : Windows 11
- XCA version 2.5.0

**Symptoms :**
v2.5.0 fails to open database connection to PostgreSQL database (from 2.4.0 upgrade) :
![image](https://github.com/chris2511/xca/assets/25719453/bd3fde2f-87fc-450c-b095-183df5bf0cba)

PostgreSQL database type is not listed (only ODBC) :
![image](https://github.com/chris2511/xca/assets/25719453/e8dfe4ba-c1d5-42c6-82a0-390373c09593)

**Additional information :**
XCA 2.5.0 was installed with PostgreSQL database driver selected :
![image](https://github.com/chris2511/xca/assets/25719453/a9f8a105-ecec-44de-a821-df866a9d7841)

**Workaround :**
Reverting to XCA 2.4.0 works fine.

**Comment by chris2511** [comment]
You need to install the PostgreSQL driver: https://www.enterprisedb.com/downloads/postgres-postgresql-downloads
Please see: https://github.com/chris2511/xca#sql-remote-database-drivers

**Comment by Ben0it** [comment]
That did it, thanks (I should have RTFM'd...).
