### ISSUE TITLE
XCA v2.5.0 MariaDB/MySQL error Driver not loaded

### ISSUE THREAD

**Issue by Bazze69** [chris2511/xca#469]
Hello,
refer to issue #467 but with MariaDB remote DB.
I applied the suggested solution but it didn't work.

- Downloaded MinGW driver from https://github.com/thecodemonkey86/qt_mysql_driver/releases (note: downloaded ver 6.5.2, same as QT version in XCA 2.5.0)
- copied qsqlmysql.dll to c:\Program Files\xca\sqldrivers\
- copied libmysql.dll, libcrypto-3-x64.dll and libssl-3-x64.dll to c:\Program Files\xca\ (note: the last file was already present in the XCA directory, so I tried both with and without overwriting the original)

Even after the above, XCA cannot see the MariaDB driver (only ODBC in the remote DB drivers list).
Thank you

**Comment by chris2511** [comment]
You installed the MinGW variant ?

**Comment by Bazze69** [comment]
Yes, I did.
I tried even the last version, 6.5.3: it didn't work

**Comment by KYannick** [comment]
I have the same issue on macOS (after the upgrade to macOS 14.0). Is there a place to download the macos mysql driver that is known to work? Did some looking around, and there are some instructions to build it yourself, but so far no success (I am also by far a Qt expert).

**Comment by jensver** [comment]
The problem is version 6.5.3.
When I run xca.exe from a cmd windows I get the error message: Cannot mix incompatible Qt library (6.5.3) with this library (6.5.2)

When installing 6.5.2 instead it works.
BUT, you will have to create a new db connection.
Previous db connection were saved as user@server/QMYSQL3:db_name
New connections are saved as user@server/QMYSQL:db_name
The file where these connections are stored is located in C:\Users\%USERNAME%\AppData\Roaming\xca

**Comment by Bazze69** [comment]
You're right, jensver!
The solutions, after installing qt_mysql_driver (MinGW flavour) version 6.5.2 (not newer), are two:
1) recreate all remote DB connections: you have to remove the AppData\Roaming\xca directory, start XCA and create new MariaDB connections;
OR
2) go to AppData\Roaming\xca, edit the file "dbhistory" substituting every occurrence of "QMYSQL3:" with "QMYSQL:"

The second solution maintain existing remote DB connections.

**Comment by Bazze69** [comment]
You're right, jensver!
The solutions, after installing qt_mysql_driver (MinGW flavour) version 6.5.2 (not newer), are two:
1) recreate all remote DB connections: you have to remove the AppData\Roaming\xca directory, start XCA and create new MariaDB connections;
OR
2) go to AppData\Roaming\xca, edit the file "dbhistory" substituting every occurrence of "QMYSQL3:" with "QMYSQL:"

The second solution maintain existing remote DB connections.

**Comment by RobThree** [comment]
Jesus Christ, I've been banging my head against the wall for an hour.

Thanks for the solution @Bazze69 

@chris2511 I am grateful for your great software, I really am, but this needs to be _much_ better documented (and preferrably fixed or worked around by the installer). For the last hour I thought I had lost access to my certs and keys...
