### ISSUE TITLE
Cant generate CRL

### ISSUE THREAD

**Issue by mnaiman** [chris2511/xca#475]
Upgraded to 2.5 and now when generating CRL via UI this error popup.
When rolled back to 2.4 CRL generation is ok.

The following error occurred:
(7pki_crl[]:NAME_OF_MY_CA)
error:0300009C:digital envelope routines::unsupported algorithm
error:068C0100:asn1 encoding routines::malloc failure
error:068C0100:asn1 encoding routines::malloc failure

(C:\Users\chris\build\xca-2.5.0\lib\pki_crl.cpp:250)

**Comment by chris2511** [comment]
Did you try the solution from #468

**Comment by mnaiman** [comment]
Yes, I have legacy db obviously - this is great software for a long time :)

Tried to change password (using version 2.5) and another error popup

The following error occurred:
(7pki_evp[1]:NAME_OF_MY_CA)
error:1D8C0102:ENCODER routines::passed a null parameter

(C:\Users\chris\build\xca-2.5.0\lib\pki_evp.cpp:573)

**Comment by chris2511** [comment]
The password change must be done with xca 2.4.0

**Comment by mnaiman** [comment]
Perfect, done.
Now works in 2.5 including CRL generation.

When selecting properties on CA certificate still shows legacy db.

![image](https://github.com/chris2511/xca/assets/2264442/ff81466d-914b-4dfe-abb7-565b8e0a7ccd)
