### ISSUE TITLE
[bug] Microsoft Store version cannot find Yubico's libykcs11.dll

### ISSUE THREAD

**Issue by tushev** [chris2511/xca#479]
XCA, installed from Microsoft Store, is unable to load "C:\Program Files\Yubico\Yubico PIV Tool\bin\libykcs11.dll":
![image](https://github.com/chris2511/xca/assets/18406797/232ab200-b756-48b3-b724-82d58e83411c)
 In the meantime, MSI version works just fine.

 I guess it's probably due to some sandboxing applied to MS store apps.

This is absolutely not a problem for me, just letting you (and others) to know about this.

Thanks!

**Comment by chris2511** [comment]
Copying the three dll: `libcrypto-1_1-x64.dll` `libykcs11.dll` `libykpiv.dll` to `C:\Windows\System32` will work.
Neither having the `Yubico PIV Tools\bin` directory in the PATH nor as current working directory make the library load successfully in the Store-App.
