### ISSUE TITLE
The SKI tickbox isn't generating an SKI extension for CSRs

### ISSUE THREAD

**Issue by DevJPM** [chris2511/xca#48]
Bug:
When ticking the box for "SKI" when creating a new CSR for an exisiting and known keypair no SKI extension is actually generated when looking at the ASN.1 output.

Steps to reproduce:

1. Create a private key
2. Open the CSR creation dialogue
3. Switch to the tab "extensions" and tick "Subject Key Identifier"
4. Enter all information neccessary for the CSR generation to work
5. Generate the CSR
6. Export it (eg to PEM)
7. Verify using an ASN.1 parser (eg [this one](https://lapo.it/asn1js/#303B300D06092A864886F70D0101010500032A00302702204403757A1D5CE1BB9366BAD2334E5A78478A35CE85B34266F124B92FD8648D5F0203010001)) that the resulting file lacks an SKI extension.

Latest Tested Platform for this bug:
Windows 10, x64, XCA 1.3.2
(but there is no mention of a fix in the changelog since then)

**Comment by chris2511** [comment]
+1 for writing great bug reports!
I was immediately able to reproduce with current HEAD and will fix it.
