### ISSUE TITLE
In Linux version dependency org.kde.Platform is end-of-life

### ISSUE THREAD

**Issue by fcarbon** [chris2511/xca#480]
I am able to use xca in Linux installed via flatpak, but I am getting an end-of-life warning when I update my flatpak pacjages.
I use the command to update my flatpak packages:  flatpak -y update

Info: runtime org.kde.Platform branch 5.15-21.08 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Info: applications using this runtime:
   io.github.chris2511.xca

Info: runtime org.freedesktop.Platform.GL.default branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   com.github.marktext.marktext, io.github.chris2511.xca
   
It looks that this may cause a problem in the future.

**Comment by daniejstriata** [comment]
Any progress made to publish 2.5 on flathub?
