### ISSUE TITLE
Export Issue PFX Chains

### ISSUE THREAD

**Issue by diegoqm95** [chris2511/xca#481]
We're using this tool to generate PFX Certificates that are executed in Azure Environments. Up to today we had no issues on the steps below:

1: Generate Key
2: Generate CSR
3: Export CSR (.pem)
4: Get CSR Signed and Import in DB (.p7b)
5: Export PFX Chain (.pfx)

Using v2.4.0 all works as expected but since the upgrade to v2.5.0 the Azure Function that processed them is rejecting the PFX Certs. It seems to be related to an encoding handling issue:

https://stackoverflow.com/questions/8286110/asp-net-the-specified-network-password-is-not-correct (Second answer, 1st one is already implemented)

I checked and both had the same Default hash and string type but the export from 2.5 was rejected. I imported the PFX and re-exported in v2.4 and worked as expected.

**Comment by chris2511** [comment]
Fixed with 4cb7b206a676ab5d00ce9407bfc027f78e2f71c2 for the next release.

**Comment by chris2511** [comment]
Verifications with the action build from this [action run](https://github.com/chris2511/xca/actions/runs/7746700519) are welcome.
