### ISSUE TITLE
Error on generating certificates

### ISSUE THREAD

**Issue by adbpos** [chris2511/xca#484]
The following error occurred:
(8pki_x509[]:192.168.1.253)
error:0300009C:digital envelope routines::unsupported algorithm
error:068C0100:asn1 encoding routines::malloc failure
error:068C0100:asn1 encoding routines::malloc failure

(C:\Users\chris\build\xca-2.5.0\lib\pki_x509.cpp:582)

**Comment by chris2511** [comment]
Please see "Signing, Renewal and CRL error in 2.5.0 #468"
