### ISSUE TITLE
.Key file generation

### ISSUE THREAD

**Issue by Paul9929** [chris2511/xca#486]
Hi I'm new to certificates but am starting to learn the hard way. What I need to accomplish is a self signed certificate with a password private key file with the file extension .key. The end goal is TLS for MQTT Client and Broker. Not sure if this is possible with XCA?

Thank you.

**Comment by chris2511** [comment]
It is possible with XCA. Actually, this is exactly what XCA was made for :-)
mosquitto doc says:
```
  keyfile file path
           Path to the PEM encoded server key.
```
Export the private key in PEM format (unencrypted, otherwise you need to enter the password when restarting the server) and name it as you like, for example `server.key`.
