### ISSUE TITLE
No start menu entry for flatpak package

### ISSUE THREAD

**Issue by makoONE** [chris2511/xca#490]
I use Debian 12 bookworm with the gnome desktop. After installing the flatpak package for XCA 2.5.0 there is no entry in the start menu. How can the problem be solved?

**Comment by 6XGate** [comment]
Same issue on any distro. Somehow there is no desktop entry in the exported files for the package.

**Comment by chris2511** [comment]
See: https://github.com/flathub/flathub/pull/5521
`flatpak install --user https://dl.flathub.org/build-repo/124558/de.hohnstaedt.xca.flatpakref`

If that works for you, too, please close this issue.
