### ISSUE TITLE
Reading oids.txt on Windows not working

### ISSUE THREAD

**Issue by RufusJWB** [chris2511/xca#492]
I have configured one additional OID in the oids.txt file:

![image](https://github.com/chris2511/xca/assets/1633499/b97b86d6-ae93-47d9-a170-9a2617e89f9f)

But it is not detected:

![image](https://github.com/chris2511/xca/assets/1633499/188db8db-c905-45bf-a473-c94a95abe6e8)

![image](https://github.com/chris2511/xca/assets/1633499/5e07d17d-6e75-48f7-a953-5dc3dd4ff308)

Any idea what I'm doing wrong?

**Comment by chris2511** [comment]
If you take the example cert from: [RFC8995 C1.5](https://www.rfc-editor.org/rfc/rfc8995.html#name-pledge-key-pair)

-----BEGIN CERTIFICATE-----
MIIBrzCCATWgAwIBAgIEHxj+5zAKBggqhkjOPQQDAjAmMSQwIgYDVQQDDBtoaWdo
d2F5LXRlc3QuZXhhbXBsZS5jb20gQ0EwIBcNMjEwNDI3MTgyOTMwWhgPMjk5OTEy
MzEwMDAwMDBaMBwxGjAYBgNVBAUTETAwLUQwLUU1LUYyLTAwLTAyMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEA6N1Q4ezfMAKmoecrfb0OBMc1AyEH+BATkF58FsT
SyBxs0SbSWLxFjDOuwB9gLGn2TsTUJumJ6VPw5Z/TP4hJ6NZMFcwHQYDVR0OBBYE
FEWIzJaWAGQ3sLojZWRkVAgGbFatMAkGA1UdEwQCMAAwKwYIKwYBBQUHASAEHxYd
aGlnaHdheS10ZXN0LmV4YW1wbGUuY29tOjk0NDMwCgYIKoZIzj0EAwIDaAAwZQIw
YirbvjT3G8uF3iaOQwD5DYjId6jdPAhAVLzsPbbccCvDf8oZIZqgq8VRjqrfNt6L
AjEAsl1Z+EfH7QOXqMDHqIH6qIbtZ2Q3UXpunKOCTW2tvPM1np1qom1/fyUcA+/w
uptx
-----END CERTIFICATE-----

and import it into XCA by pasting it on the main window, the extensions show:

```
MASA URL:
..highway-test.example.com:9443
```
The display of **MASA URL** proves that the OID has been read successfully from the oids.txt.

The extension is an IA5STRING according to https://www.rfc-editor.org/rfc/rfc8995.html#name-masa-uri-extension
So the final config string syntax as described in https://www.openssl.org/docs/manmaster/man5/x509v3_config.html (ARBITRARY EXTENSIONS) reads:

```
id-pe-masa-url = ASN1:IA5STRING:masa.sdo-qa.siemens.cloud
```

**Comment by RufusJWB** [comment]
Thank you! That's working
