### ISSUE TITLE
v2.5.0 Windows - error:0300009C:digital envelope routines::unsupported algorithm

### ISSUE THREAD

**Issue by tobiaskitsune** [chris2511/xca#494]
Hello,

Version 2.5.0 x64 under Windows 11 fails when singing a signing request with following error message:

> Der folgende Fehler ist aufgetreten:
> (8pki_x509[]:Test)
> error:0300009C:digital envelope routines::unsupported algorithm
> error:068C0100:asn1 encoding routines::malloc failure
> error:068C0100:asn1 encoding routines::malloc failure
>
> (C:\Users\chris\build\xca-2.5.0\lib\pki_x509.cpp:582)

This I can reproduce with the msi installer and with the portable version 2.5.0.
Private key and singing request was generated by xca. RSA key 4096 bis with SHA512. 

Im using xca since years without problem. Same database, same CA. No problems. The only thing I changed is that I re-installed Windows 11 and installed the latest version of xca. I cannot remember what version was installed before.

**Comment by chris2511** [comment]
Please see https://github.com/chris2511/xca/discussions/468
