### ISSUE TITLE
version 2.5  Remote Database

### ISSUE THREAD

**Issue by eliaszoghbimobimind** [chris2511/xca#495]
Hello  , please note that in the new version 2.5 the remote database drop down does not show the postgress connection

**Comment by AnonATXDO** [comment]
Please read the information on the github page about the remote SQL database in XCA 2.5.0

https://github.com/chris2511/xca#sql-remote-database-drivers

**Comment by chris2511** [comment]
During installation you may deselect everything but the "Command Line Tools", which results in a much smaller installation.
<img width="550" alt="Bildschirmfoto 2023-12-12 um 15 09 31" src="https://github.com/chris2511/xca/assets/266269/2d4d0dfd-fdb7-4b46-813c-239d6304e21f">
