### ISSUE TITLE
PKCS11 access to AWS CloudHSM results in CKR_SLOT_ID_INVALID error

### ISSUE THREAD

**Issue by vlady-github** [chris2511/xca#496]
When XCA attempts to connect to AWS CloudHSM, via PKCS11 interface, an error "CKR_SLOT_ID_INVALID" gets triggered.

The error generated by AWS' "cloudhsm_pkcs11" library indicates:

"ERROR [136372] ThreadId(3) [cloudhsm_pkcs11::slots::slot_manager] BP000: Invalid **slot id 1**"

Inspecting the slots on AWS CloudHSM with "pkcs11-tool" returns:

pkcs11-tool -L --module /opt/cloudhsm/lib/libcloudhsm_pkcs11.so
Available slots:
Slot 0 (**0x2000000000000001**): hsm1
...

The root cause has been identified to lie in the integer type of variables used to hold the Slot IDs. The integer type is not big enough to hold the whole number returned as a Slot ID by AWS CloudHSM (e.g. "**0x2000000000000001**"). As a result, the Slot ID value gets truncated (only the lower part of the number is stored, e.g. "**0x00000001**") and that causes invalid Slot IDs to be used (e.g. "**slot id 1**") for the operations against AWS CloudHSM. Respectively the error "CKR_SLOT_ID_INVALID" gets triggered for any operation.

The solution would be integer type used for variables that hold the Slot IDs to get changed to "unsigned long long".

**Comment by chris2511** [comment]
The size of the CK_SLOT_ID is fixed to "unsinged long":
http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#_Toc416959687

However, I think, I found the bug in XCA....

**Comment by vlady-github** [comment]
Thanks for the resolution.

Is there any other bug, that you referred to ?

**Comment by chris2511** [comment]
> Is there any other bug, that you referred to ?

https://github.com/chris2511/xca/blob/52da070dcf637ca6c633dacaf775efeb8eff4be3/lib/pkcs11_lib.cpp#L226
and the fix in 06009705bb4348e99b646b809584f0634d46ca88

Please try the fix from the development tree: https://github.com/chris2511/xca/tree/develop
or the action builds from: https://github.com/chris2511/xca/actions

I don't have an AWS account to verify the fix

**Comment by vlady-github** [comment]
That makes sense. When mangled through "int" big-number slot IDs get truncated.

It's another question whether it makes sense slot IDs to be so big numbers, but that's a matter of a HSM implementation.
