### ISSUE TITLE
Hang while importing 1.4.1 database into 2.1.0

### ISSUE THREAD

**Issue by storm49152** [chris2511/xca#50]
Hi,

I just updated from XCA 1.4.1 to 2.1.0 on Windows. When I open a XCA 1.4.1 database in XCA 2.1.0, it tells me that it's going to convert the database and make a backup. It's a small database but XCA never finishes and has "Not Responding" in the application title bar. Also, it keeps consuming anywhere between 15-20% CPU time. The resulting .xdb file can be opened but is incomplete. I've repeated this a couple of times but each time I have the same result.

**Comment by chris2511** [comment]
I would need the database which caused this. Of course you don't want to send me your private keys, but maybe after deleting all private keys, the problem still exists and you can send me the stripped database to my private mail?

**Comment by storm49152** [comment]
I just tried and after stripping the private keys the issue is still there AFAICT. Do I reply to the email to send you the database?

**Comment by chris2511** [comment]
Please send it to my private mail account: <christian@hohnstaedt.de>
