### ISSUE TITLE
Application argument for password not working (mremoteng xca)

### ISSUE THREAD

**Issue by 573dave** [chris2511/xca#501]
I'm trying to add xca as an external application in mremoteng.
When using this as the arguments to launch the app:
--database=%USERNAME% --password=%PASSWORD%
it will open the correct database, but not enter the password.
These variables are being passed to "C:\Program Files\xca\xca.exe" 
Self testing in the command line reveals the same issue, it will load the database but not load the password.
Is there a different argument? Or no allowed argument?

**Comment by chris2511** [comment]
You need the "pass:" prefix. See:
https://www.hohnstaedt.de/xca-doc/html/commandline.html#passphrase-arguments

--database=%USERNAME% --password=pass:%PASSWORD%

Or use env

--database=%USERNAME% --password=env:PASSWORD
