### ISSUE TITLE
ODBC the only option for "Open Remote Database" on Windows systems

### ISSUE THREAD

**Issue by laserguidedcake** [chris2511/xca#502]
Howdy fellows,

Recently when attempting to install xca 2.5.0 (using both the MSI and the portable version) and when attempting to open a remote database, the only option available is ODBC (no options for PostgreSQL or mariaDB).

Steps to reproduce: (on a windows 11 device)
1. Install the application via an MSI
2. Make sure to select choose a "Complete" or "Custom" install (make sure to "Entire feature will be installed on local hard drive" option is set for PostgreSQL driver.)
3. Finish the install and launch the application
4. Navigate to File > Open Remote DataBase
5. Notice there is only one option, ODBC, and not PostgreSQL

Perhaps I am missing something in the documentation?

**Comment by AnonATXDO** [comment]
Please see https://github.com/chris2511/xca?tab=readme-ov-file#sql-remote-database-drivers and #495. You have to install other database drivers yourself because of license issues (they are not shipped with Qt anymore by default).

**Comment by flybyray** [comment]
@AnonATXDO do you know what exactly needs to be in the path for windows?
I have installed postgresql 16 (via scoop) and the following files are in path now:

```
._libcrypto-3-x64.dll
._libssl-3-x64.dll
._libxml2.dll
._zlib1.dll
clusterdb.exe
createdb.exe
createuser.exe
dropdb.exe
dropuser.exe
ecpg.exe
icudt67.dll
icuin67.dll
icuio67.dll
icutu67.dll
icuuc67.dll
initdb.exe
isolationtester.exe
libcrypto-3-x64.dll
libecpg.dll
libecpg_compat.dll
libiconv-2.dll
libintl-9.dll
liblz4.dll
libpgtypes.dll
libpq.dll
libpq_pipeline.exe
libpq_testclient.exe
libpq_uri_regress.exe
libssl-3-x64.dll
libwinpthread-1.dll
libxml2.dll
libxslt.dll
libzstd.dll
oid2name.exe
pg_amcheck.exe
pg_archivecleanup.exe
pg_basebackup.exe
pg_checksums.exe
pg_config.exe
pg_controldata.exe
pg_ctl.exe
pg_dump.exe
pg_dumpall.exe
pg_isolation_regress.exe
pg_isready.exe
pg_receivewal.exe
pg_recvlogical.exe
pg_regress.exe
pg_regress_ecpg.exe
pg_resetwal.exe
pg_restore.exe
pg_rewind.exe
pg_test_fsync.exe
pg_test_timing.exe
pg_upgrade.exe
pg_verifybackup.exe
pg_waldump.exe
pgbench.exe
postgres.exe
psql.exe
reindexdb.exe
stackbuilder.exe
vacuumdb.exe
vacuumlo.exe
wxbase317u_vc_custom.dll
wxbase317u_xml_vc_custom.dll
wxbase317ud_net_vc_custom.dll
wxmsw317u_adv_vc_custom.dll
wxmsw317u_core_vc_custom.dll
wxmsw317ud_aui_vc_custom.dll
wxmsw317ud_html_vc_custom.dll
wxmsw317ud_xrc_vc_custom.dll
zic.exe
zlib1.dll
```

Tested this with PowerShell like this (first file in the bin directory)  `Get-Command ._libcrypto-3-x64.dll` 
The output shows the path to: `$env:USERPROFILE\scoop\apps\postgresql\current\bin\._libcrypto-3-x64.dll`

I guess this was an auto update without testing https://github.com/ScoopInstaller/Extras/commit/2f50f3c523fd4b64892c2e4005f7602848cb4549

**Comment by chris2511** [comment]
> do you know what exactly needs to be in the path for windows?

It's the `libpq.dll`and its dependencies.

**Comment by cbka** [comment]
maybe this should be exclusively named in the windows installer. this causes horrific discomfort ...

**Comment by cbka** [comment]
<3
