### ISSUE TITLE
XCA 2.5.0 seems always use sha256 hash regardless of Option settings (need to use SHA1)

### ISSUE THREAD

**Issue by oshoincontrol** [chris2511/xca#506]
Hi, in 2.5.0 version seems to ignore Hash algorithm settings while exporting PFX. Can't seem to export PFX with SHA1 which works with older Windows versions (2016). No matter what is select in Options, exported PFX seems to use SHA256.

**Comment by chris2511** [comment]
Fixed with 4cb7b206a676ab5d00ce9407bfc027f78e2f71c2 for the next release.

**Comment by chris2511** [comment]
Verifications with the action build from this [action run](https://github.com/chris2511/xca/actions/runs/7746700519) are welcome.
