### ISSUE TITLE
XCA 2.5.0 DLL error 

### ISSUE THREAD

**Issue by h3llhydr4** [chris2511/xca#508]
Hello,

Just updated to 2.5.0 version and I encountered the following error:

"The procedure entry point CreateEventW could not be located in dynamic link library api-ms-win-core-synch-l1-2-0.dll"

I tried to install microsoft visual c++ redistributable 2015-2022 and also to replace the dll with other one but the error still appears when I try to open the application.

Could you advice?

**Comment by chris2511** [comment]
Please see #515
