### ISSUE TITLE
p12 files corrupted

### ISSUE THREAD

**Issue by K1kc4** [chris2511/xca#509]
Hello,

After exporting p12/pfx files, i am unable to open them. On my fedora system i am getting "Could not parse invalid or corrupted data." and my Mac says that password is incorrect..
 
![image](https://github.com/chris2511/xca/assets/103556829/63489c9b-b318-4747-adc5-c0bfdc623db2)

Did anyone have simmilar problem ?

----
EDIT:

I just tried with 2.4.0 version, and it works..

**Comment by chris2511** [comment]
Fixed with 4cb7b206a676ab5d00ce9407bfc027f78e2f71c2 for the next release.

**Comment by chris2511** [comment]
Verifications with the action build from this [action run](https://github.com/chris2511/xca/actions/runs/7746700519) are welcome.
