### ISSUE TITLE
Importing exported data

### ISSUE THREAD

**Issue by storm49152** [chris2511/xca#51]
Hi,

Because I could not convert a 1.4 .xdb with XCA 2.1.0, I just created a new database and started exporting/importing everything from the old to the new database (export to clipboard -> PEM private -> Paste PEM data).
I noticed that each Private Key is imported having the same name (don't recall what it was exactly, but it had "RSA" and "2048" in there). which seems logical: a key doesn't have name info by itself. Luckily we don't have *that* many keys and they're all imported in the same order as found in the original database, so I took the effort to manually rename the internal names.

Since a PEM key has a begin- and end-markings, would it be possible to enhance this and add additional info that XCA can use when importing private keys so that it can automatically set the correct internal name? The same goes for Templates.

Also, would it be hard to make it possible to export the whole root-intermediate-cert chain and import it? Now you need to export/import each level separately. I know you preferably don't want to do this too often, but it might help a lot of other people.

**Comment by chris2511** [comment]
The "Extra -> Dump Database" will write all items into a directory structure at once.
Import them by selecting all items in one directory by the import menu.
This way, the key names will be partly kept (special characters replaced by underlines).

**Comment by storm49152** [comment]
Ah, okay, thanks for pointing that out.
