### ISSUE TITLE
DLL error in v2.5.0 : SystemParametersInfoForDpi not found

### ISSUE THREAD

**Issue by jeanbruder** [chris2511/xca#514]
Dear all,

I just upgraded XCA from 2.4.0 to 2.5.0 and face the following issue :
![image](https://github.com/chris2511/xca/assets/72472219/e1b2d4a5-4bc0-4b73-be1e-fcbfc9500d12)

I run the new version 2.5.0 under Windows 2012 R2, connected in a remote session from my laptop (using RDP).

Can You please help ? Back to 2.4.0 as long as this is not solved.

Regards,
Jean

**Comment by chris2511** [comment]
Please see #515
