### ISSUE TITLE
PKCS#12 export problem

### ISSUE THREAD

**Issue by EvBu75** [chris2511/xca#517]
when using the new option "PKCS#12 encryption algorithm", and set it to AES 
AND the private key was created in an older version of XCA than 2.5, the export of
the private key fails.
Although the PKCS12-container is created without any error-message from XCA, the file does not
contain a valid private key.
Setting the export-algorithm to 3DES solves the problem. 
Also, if the whole certificate is created in 2.5 from scratch (key-> request -> cert) this problem seems not fire up.

**Comment by chris2511** [comment]
This should be fixed with d32ab2e0d429d0a6fcfa088affcf825abc798a04 6d01928d5d74d9ceffd3665ae3a4d3629004a6f5 and probably 4cb7b206a676ab5d00ce9407bfc027f78e2f71c2
You are invited to verify with the latest [action-build](/chris2511/xca/actions/runs/7897725929)
