### ISSUE TITLE
Subject Alternative Name should not contain email:copy

### ISSUE THREAD

**Issue by reetp** [chris2511/xca#519]
XCA Version: 2.5.92-dev
commit: 4eb2067057987485e7c3a548111c8b1e38761246
OpenSSL 3.0.2 15 Mar 2022
QT version: 5.15.3

When editing the template I noticed that Subject Alternative Name permits

email:copy

![Screenshot_2024-02-14_13-10-09](https://github.com/chris2511/xca/assets/3800384/5fab616a-5b29-4965-9730-05c3f898f6b8)

But according to this it is not permitted (I am still learning about this stuff!)

https://www.openssl.org/docs/man1.1.1/man5/x509v3_config.html

The option should probably not be there!

I guess this is because the same menu routine is used for all the Edits under Extensions.

It also won't permit you to add the correct:

`issuer:copy`

It throws an error on saving the template:

"The certificate contains invalid extensions."

Had a brief look in the code, but I have never used QT creator before so a bit lost as to where options are :-) I get as far as v3ext.ui but can't see the options.

Generated certificate using 'email:copy' which is incorrect.

```
X509v3 Basic Constraints critical:
CA:FALSE
X509v3 Subject Key Identifier: C3:0D:D9:37:BB:B9:FC:7A:E4:C9:7C:72:4B:D8:9C:A3:91:FC:6F:1D
X509v3 Key Usage: Digital Signature, Key Encipherment, Data Encipherment, Key Agreement
X509v3 Extended Key Usage: TLS Web Server Authentication, TLS Web Client Authentication, IPSec End System, IPSec Tunnel, IPSec User
X509v3 Subject Alternative Name: email:admin@mydomain.com
X509v3 Issuer Alternative Name: email:copy
X509v3 CRL Distribution Points: 
Full Name:
URI:https://www.mydomain.com/crl/CA_Cert.der
```

I guess it needs that particular menu written separately, if such a thing is possible!

This also refers:

https://github.com/chris2511/xca/issues/301

**Comment by chris2511** [comment]
`email:copy` and `issuer:copy` are OpenSSL convenience shortcuts that copy the email address from the subject and the whole subject alternative name respectively.
`email:copy` only works and makes sense if you fill in the `emailAddress` in the subject of the certificate
`issuer:copy` only makes sense and works if the `subject alternative name` of the issuer is not empty. For templates XCA uses the `subject alternative name` of the same certificate for checking.

`email:` is a valid tag and `copy` is a sufficiently valid email-address, so it does not result in an error when used as `issuer alternative name`.

Using `email:copy` without providing an emailAddress results in an empty `subject alternative name`  and `issuer:copy` fails to copy the empty `subject alternative name`

The golden rule: 'If it hurts, stop doing it !'
