### ISSUE TITLE
permanent processor load / stucked instances as background process

### ISSUE THREAD

**Issue by stromatologe** [chris2511/xca#520]
With xca 2.5.0 Win64 and a rather big CA (1300 certs) work became slower every day.
In the end one core was at 50% load for several minutes after one removed old cert. Removal took several seconds.

Investigation first pointed to MariaDB via Network. Local MariaDB looked fine but became slower with working.
Then i found in the category "Hintergrundprozesse" (not shure background process) of the taskmanager stucked XCA processes with normal 25MB memory but no CPU load.
In the end this processes seam to slow down the active process - how i can´t imagine.

Check with local sqlite database, newer libssl/libcrypto (3.0.13.0/3.1.5) brought some speed but not for long.
I used the portabel package and checked against the app - only to find the app as background process after closing.

Lob für das tolle Programm, das ich schon seit 2006 benutze auf deutsch - DANKE!

**Comment by pc-bastler** [comment]
Which version do you have installed.

My collegue has the same problem (V2.5.0) with our MS SQL Server Database. I am still using 2.4.0 and it works like charme, no performance issues here.

**Comment by chris2511** [comment]
Performance improved, especially the background process.
You are invited to test the [current build](/chris2511/xca/actions/runs/8020825364).
