### ISSUE TITLE
XCA version 2.6.0 very slow (Win 10)

### ISSUE THREAD

**Issue by wniva** [chris2511/xca#533]
After updating to version 2.6.0, the XCA is very slow under Windows 10 Home.
Starting, operating (unfoldering, opening a certificate) and exporting are extremely slow.

I have now installed 2.4.0 again and XCA is working normally again.
I couldn't use version 2.5.0 because of the export problem with the missing private keys.

**Comment by chris2511** [comment]
Looks like selecting [Don't colorize expired certificates](https://hohnstaedt.de/xca-doc/xca.html#toc12.4) in the options dialog speeds up XCA.
