### ISSUE TITLE
XCA 2.5.0 & 2.6.0 very slow

### ISSUE THREAD

**Issue by JBau32** [chris2511/xca#535]
Most likely same problem as #533

Looking at the process activity, I see that it constantly spams the Windows Registry for Time zones. (QDateTime fromString)
Tracing it further it is due to `pki_x509::bg_color`/`pki_base::bg_color` which are being called a lot.
Temporarily removing that function using a debugger has lead to improved responsiveness and no more constant freezing.
There still is some stalls/freezes but not anytime i hover or select a certificate.

OS: Windows 11

**Comment by JBau32** [comment]
Found related QT6 bug: https://bugreports.qt.io/browse/QTBUG-120285

**Comment by chris2511** [comment]
On my Windows 11, XCA works pretty fast.
Even when running inside a virtual machine hosted on an old and slow linux-intel-I5.
If QT6 is the culprit, please try the [QT-5.15 action-build of XCA-2.6.0](/chris2511/xca/actions/runs/8056671415)

**Comment by JBau32** [comment]
It gets significantly slower if you add 200-500 certificates.

And yes, just tried, qt5 variant is unaffected.
Qt6 seems to have fixed this already on a later 6.6 patch, xca release uses 6.6.0.

**Comment by JBau32** [comment]
Unfortunately the qt5 variant seems overall slower.
So manually patching out `pki_x509::bg_color`/`pki_base::bg_color` functions on qt6 achieves the best results.
Nested RootCA + 200 + sub certificates are a big slowdown

**Comment by chris2511** [comment]
Looks like selecting [Don't colorize expired certificates](https://hohnstaedt.de/xca-doc/xca.html#toc12.4) in the options dialog also speeds up XCA without patching. The latest 6.6.2 release is still notably slower when colorizing expired certificates.

**Comment by JBau32** [comment]
Good to know!
That option will be my go-to workaround for now till QT devs have resolved that issue.

**Comment by WRW001** [comment]
Using the latest 6.6.3 QT release will resolve this issue. You can have expired certificates colorized without slowing XCA down. The CI&DI currently used can't build Windows binaries using QT 6.0.X, so there will be no PRs. You can make Windows binaries by yourself.
 #533

**Comment by GiladHi** [comment]
Any chance of a new release / build with QT 6.3.3? The only issue I have with the latest version is the speed...

**Comment by WRW001** [comment]
> Any chance of a new release / build with QT 6.3.3? The only issue I have with the latest version is the speed...

https://github.com/WRW001/xca/releases

**Comment by GiladHi** [comment]
Thanks for the new version and the quick reply! 😎

**Comment by GiladHi** [comment]
Seems like Google Chrome is blocking the downloading of this build... Maybe I should wait for the next official version.

**Comment by GiladHi** [comment]
Hi @chris2511 , 

Any chance of a new release / build with the latest QT version (6.6.3) in order to solve the speed issue on Windows?...

**Comment by chris2511** [comment]
https://github.com/chris2511/xca/releases/tag/RELEASE.2.7.0
