### ISSUE TITLE
XCA 2.6 on macOS - mySQL ODBC issue

### ISSUE THREAD

**Issue by Henri0404** [chris2511/xca#537]
Hi,

receive this message, even the driver is installed, macOS 14.4.

Der folgende Fehler ist aufgetreten:
[iODBC][Driver Manager]Data source name not found and no default driver specified. Driver could not be loaded, IM002 QODBC: Unable to connect

#ls -l /usr/local/opt/libiodbc/lib/libiodbc.2.dylib 
lrwxr-xr-x  1 root  wheel  58 Mar 12 17:57 /usr/local/opt/libiodbc/lib/libiodbc.2.dylib -> /opt/homebrew/Cellar/libiodbc/3.52.16/lib/libiodbc.2.dylib

Thanks

Henri

**Comment by chris2511** [comment]
See: https://mariadb.com/kb/en/creating-a-data-source-with-mariadb-connectorodbc/

You need at least `mariadb-connector-odbc` and a `.odbc.ini` like this in your home directory:

```
[Default]
Description = MariaDB Driver
Driver      = /opt/homebrew/lib/mariadb/libmaodbc.dylib
Database    = xca
Server      = mariadbsql.local
```

Afterwards a
```
isql -v Default <sqluser> <sqlpass>
```
worked.
 **_But:_** xca did not:
```
Error: The following error occurred:
?????????????????
```
and I have no clue why. Maybe it works for you.

**Comment by jonathanmarsaud** [comment]
Hi,

Also affected by this on macOS Sonoma and XCA 2.6, even with libodbc installed and properly linked according to the `README.md`.

**Comment by anddyL** [comment]
Hello,
Same problem. I installed the version with brew install and "xca-2.6.0-Darwin.dmg" and could not connect with mariadb.
