### ISSUE TITLE
XCA 2.6.0 gui language bug under macOS

### ISSUE THREAD

**Issue by jelockwood** [chris2511/xca#539]
@chris2511 
XCA 2.6.0 when run under macOS is displaying the user interface in the 'wrong' language.

We have tried it on at least three different Macs running either macOS Sonoma 14.4 or macOS Monterey 12.7.4 and all three exhibit the same error although the wrong language displayed may differ. In case it is not obvious in all three cases it should display in English.

I have seen this sort of bug before, possibly even a long time ago with XCA itself.

Here is one example screen capture showing 2.6.0 displaying using the 'wrong' language.
![Screenshot 2024-03-21 at 09 46 48](https://github.com/chris2511/xca/assets/4300786/4d89f587-bffc-4c31-a9bc-a0f05618f5d1)

Here is version 2.5.0 on _the same Mac_ displaying correctly in English.
![Screenshot 2024-03-21 at 09 46 17](https://github.com/chris2511/xca/assets/4300786/ed7ffa51-473d-4a1f-bbf7-921e94b642c2)

**Comment by chris2511** [comment]
Please see #532 
Fixed for the next release.
Leaving this open until the release to be found by others.

**Comment by jelockwood** [comment]
@dsoundmn 
The easiest temporary fix is to revert to the previous version i.e. 2.5.0 which did not have this bug.

**Comment by dsoundmn** [comment]
thank you! keep up the great work!

**Comment by chris2511** [comment]
> Thank you for the fix - do you have an estimated date for release? and by any chance, is there a fix we can apply locally to select the language?

The language is indonesian, i assume. You can switch to english:
In the menu select Berkas -> Bahasa -> inggris (English)

**Comment by Error404-net** [comment]
> > Thank you for the fix - do you have an estimated date for release? and by any chance, is there a fix we can apply locally to select the language?
> 
> The language is indonesian, i assume. You can switch to english: In the menu select Berkas -> Bahasa -> inggris (English)

I also have this issue, thanks for the manual translation.

**Comment by iMunas** [comment]
I was too lazy to look for a translation and added one line to the xca/Contents/Info.plist file
<...>
	<key>CFBundleLocalizations</key>
	<array>
		<string>id</string>
		**<string>en</string>**
		<string>hr</string>
		<string>nl</string>
<...>
After this, XCA started speaking in English

**Comment by 0x4D5352** [comment]
Selecting English in the language menu only fixed the XCA GUI, and the language remained in Indonesian when navigating through the Finder sub-windows. the plist fix @iMunas posted fixed that for me.

**Comment by chris2511** [comment]
https://github.com/chris2511/xca/releases/tag/RELEASE.2.7.0
