### ISSUE TITLE
Error in compiling code in linux

### ISSUE THREAD

**Issue by Erfankam** [chris2511/xca#550]
When I tried to build xca, after configuration, I faced an error describing error while liking test/renewal.cpp file and its dependencies. The problem was pthread missing library.
I could build and install whole application just by adding SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")
 in related Cmakefile (test/CMakeLists.txt).

I am using Cmake in linux. It should be a problem other that linux platform like apple.
Should we work on it?

**Comment by chris2511** [comment]
It seems to depend on the compiler version.
gcc-11 as used in the github action doesn't need it, but my Ubuntu 20.04 with gcc9 also fails to compile:
`test/renewal.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'`

I think
```
target_link_options(testxca PRIVATE -pthread)
```
in test/CMakeLists.txt will be a less intrusive solution.
A pull-request is appreciated

**Comment by Erfankam** [comment]
Sure. I will managed to send a PR soon. Thanks.
