### ISSUE TITLE
issues with icons in gnome dock

### ISSUE THREAD

**Issue by pieska** [chris2511/xca#552]
I added xca 2.6.0 to gnome 46 dock, the correct icon is shown and tool tip shows "XCA".

if I start xca, the xca entry is not shows as active but a new active app is added to the dock with a standard icon and the tooltip "hohnstaedt.de.xca".

anyone knows why this happens and how to fix it?

**Comment by chris2511** [comment]
- Which OS ?
- Self compiled or by package manager?
- You probably installe different instances (self-compiled, package manager, flatpak)?

**Comment by pieska** [comment]
sorry, forgot those details: Fedore Core 40, package installed by package manager, package is the only installed xca instance
