### ISSUE TITLE
Feature request: option to hide certificates, that are expired more than x days

### ISSUE THREAD

**Issue by janschmidt76** [chris2511/xca#557]
Hi Chris,

first, many thanks for your great piece of software! I'm using XCA for many years now, so there's a big amount of certs in the database, across multiple CAs. Sometimes, it's a little bit confusing to find/see certs between all red-marked expired certs. and I miss an option to hide certs expired more than e.g. 30 days. Would it be possible, to add such an option to the configuration dialog?

Kind regards,
Jan

**Comment by chris2511** [comment]
Duplicate of #391
