### ISSUE TITLE
issue/feature request - Version 2.6.0 invalid password during certificate import on other devices

### ISSUE THREAD

**Issue by ryder-hook** [chris2511/xca#559]
Hello,

Thanks for this nice software!
I renewed a certificate using version 2.6.0 end exported it as PKCS #12 (both variants). It was a certificate for a network gateway. I wanted to import the certificate there. Unfortunately this didn't work, I always got the error message "invalid password".
I then searched the Internet for a solution, where I found the information to use the export with the -legacy parameter when using openssl. I assume that the appliance cannot handle modern algorithms.
I then imported the certificate into the old version 2.4.0 of XCA and exported it again. The import into the appliance then worked.

So there is probably no error with XCA (hence the imprecise subject), but perhaps an option for the export could be implemented to avoid such problems in the future.

Wishes
Thorsten

**Comment by GiladHi** [comment]
XCA 2.6.0 is based on OpenSSL 3.0, which encrypt the private key using AES256.
I think that XCA 2.4.0 used an older version of OpenSSL, so the private key was encrypted using 3DES.

I had a similar issue with Windows Server 2016.

**Comment by ryder-hook** [comment]
@GiladHi , yes, this is exactly what was also my assumption. But Openssl 3.0 already have the -legacy cli parameter. 
This was the reason why I suggested this adoption.

**Comment by teward** [comment]
Note that a temporary workaround would be to export the certificate (certificate.crt), the cert key (privkey.pem), and the CA chain of certs (ca-chain.crt), and then use the following commands (OpenSSL 3.0) to create the pkcs12 (NOTE: My environment is Linux, but the OpenSSL binaries should be capable of still doing this provided you have the legacy provider available):

    openssl pkcs12 -legacy -export -in certificate.crt -certfile ca-chain.crt -inkey privkey.pem -out CertificateChain.pfx

The certs and keys can be in DER or ascii-armored PEM format, just as long as OpenSSL can parse it.

This is the workaround I came up with with XCA 2.4.0 to create 'legacy' PKCS12 bundles for Windows systems that need the older ciphers and algos and such, and this still works (even in Ubuntu 22.04 which is what I use on my regular system.)

**Comment by teward** [comment]
@chris2511 I believe this should be a higher priority item, because a single checkbox to *allow* legacy export for Windows and other appliances to read the PKCS12 files is important.  My workaround 'works' but it's pain so.

**Comment by teward** [comment]
@ryder-hook when you open your XCA database, and then go to File > Options, what option is selected for PKCS12 Encryption Algorithm?

**Comment by ryder-hook** [comment]
@teward , AES-256-CBC is selected in Version 2.6. I also have these two options. In the older version, this parameter was not available.

**Comment by teward** [comment]
> @teward , AES-256-CBC is selected in Version 2.6. I also have these two options. In the older version, this parameter was not available.

What happens if you choose the nob-AES-256 option?  Do the generated PKCS12 files work then?

**Comment by ryder-hook** [comment]
@teward, My original problem was that I had to import the certificate onto an appliance. The certificate itself must then be made available on the appliance via USB stick. That's why I can't simply do a new test now. I would have to recreate the certificate and install it on the appliance using a USB stick. Sorry for that.

**Comment by chris2511** [comment]
Even ancient, insecure PKCS#12 algorithms are supported (and tagged as insecure) with #383
