### ISSUE TITLE
duplicate Serials after Upgrade 2.1.0

### ISSUE THREAD

**Issue by funked00** [chris2511/xca#56]
Hi,

after opening my V 1.3.1 DB with version 2.10 the DB was converted. When signing the first CSR there was an error mesage: "Failed to retrieve unique random serial". In the next try there was no error message and the certificate was generated. But with a serial already in the database.

Best regards,
Daniel

**Comment by chris2511** [comment]
Did the certificates with identical serials have the same issuer?
It is only necessary for certificates issued by the same issuer to have unique serials.

The issue is caused by to narrow random serials (8 bit). It should be 64 bit.

**Comment by funked00** [comment]
Yes, the new certificate was signed by the same issuer. The serial was a two digit hex. I noticed the problem because this serial was on the crl already.
