### ISSUE TITLE
PKCS#12 Import: Internal Name differs from Common Name

### ISSUE THREAD

**Issue by leonardo0014** [chris2511/xca#569]
The tool is great for my certificate management with a GUI. I particularly like the fact that it is available for three operating systems. However, I still noticed something that seems annoying.

But to my actual concern
When I import a PCKS#12 container, the issuer certificates from the chain always get the same common name as the actual end-user certificate as an internal name. Would it be possible to additionally check and correct during import whether the common name differs from the certificate that was read first globally and, if so, which one is used?

The behavior is still present in the latest version (2.6.0)

**Comment by chris2511** [comment]
During certificate import from PKCS#12 the internal name is taken from the "Friendly name" property of the PKCS#12 container. And during export XCA uses the internal name of the certificate as friendly name in the PKCS#12 file.

The behavior is rather a matter of taste (and sadly I like it the way it is ...)

If you want to see the common name of each certificate you may turn on the "common name" column.
See https://hohnstaedt.de/xca-doc/html/common-actions.html#column-handling

**Comment by leonardo0014** [comment]
Thanks for the quick reply.
Then I just have to continue to manually correct the names of the imported issuing and issuer certificates
