### ISSUE TITLE
feature request: Enhance evaluation or search imported Revocation lists

### ISSUE THREAD

**Issue by leonardo0014** [chris2511/xca#570]
I also use XCA to manage external certificates and keep an eye on their dependencies and validity. The issuing certificates are also not always my own. ;-)

The contents of an imported revocation list are currently not automatically checked against the existing certificates in the database. Perhaps a button/function can be added to initiate an active check and then display this in the "Revocation" column. Alternatively, a search field in the revocation list would be useful to be able to search manually for the serial number. This function would help with static revocation lists to identify which imported certificate in the database has already been revoked.

Thank you in advance if this is ever implemented

**Comment by chris2511** [comment]
The demanded behavior should actually be implemented. I tested it right now and: **It works for me&trade;**.
When importing a certificate its revocation state is checked, and when importing a CRL, the revocation state of all certificates issued by the CA is re-evaluated.
However, the issuing CA must also be imported.
