### ISSUE TITLE
OpenSSL error (pki_evp.cpp:178) : error:140E0197:SSL routines:SSL_shutdown:shutdown while in init

### ISSUE THREAD

**Issue by jmhertlein** [chris2511/xca#58]
System: Arch Linux x64 using the xca from the AUR (which was recently promoted to the community repo, actually, which is where the package is right now). All of my packages are up-to-date as of today, 23 August 2018. Let me know if you need to know specific package versions of anything.

I am using Postgres 10 as the RDBMS.

I get the following error when trying to load my database.

Steps to reproduce:

0. A week or so ago, I made a single self-signed CA key + cert and signed 3-4 end-entity certificates with 10-year expiries. I saved and loaded the database a few times, if I recall correctly, and decrypting the db worked each time.
1. Fast forward to yesterday. I launched xca, typed in the password to log into the RDBMS, then typed in my password to decrypt the actual xca data. 
2. Upon hitting enter, I get a pop-up that says:

```
The following error occurred:
(7pki_evp[]:)
error:140E0197:SSL routines:SSL_shutdown:shutdown while in init

(pki_evp.cpp:178)
```

After I dismiss this pop-up, I am left at the main xca window but with none of my certs or keys visible.

I can reproduce it each time I try to access my certs/keys. 

When I run it from the command line, I see this on stdout/err.

STDOUT/ERR:
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
DB driver: "QIBASE"
DB driver: "QSQLITE"
DB driver: "QMYSQL"
DB driver: "QMYSQL3"
DB driver: "QODBC"
DB driver: "QODBC3"
DB driver: "QPSQL"
DB driver: "QPSQL7"
DB driver: "QTDS"
DB driver: "QTDS7"
Available Remote DB Drivers:  2
"QMYSQL3"
"QPSQL7"
Creating OID: "/usr/share/xca/oids.txt" 8 1061 "1.3.6.1.4.1.311.20.2" "dom" "Domain Controller"
Creating OID: "/usr/share/xca/oids.txt" 9 1062 "1.3.6.1.4.1.311.21.1" "MsCaV" "Microsoft CA Version"
Creating OID: "/usr/share/xca/oids.txt" 11 1063 "1.3.6.1.4.1.311.10.3.4.1" "msEFSFR" "Microsoft EFS File Recovery"
Creating OID: "/usr/share/xca/oids.txt" 12 1064 "1.3.6.1.5.5.8.2.2" "iKEIntermediate" "IP security end entity"
Creating OID: "/usr/share/xca/oids.txt" 19 1065 "0.2.262.1.10.7.20" "nameDistinguisher" "Name distinguisher"
Creating OID: "/usr/share/xca/oids.txt" 21 1066 "1.3.6.1.5.5.7.3.13" "id-kp-eapOverPPP" "EAP over PPP"
Creating OID: "/usr/share/xca/oids.txt" 22 1067 "1.3.6.1.5.5.7.3.14" "id-kp-eapOverLAN" "EAP over Lan"
SPLIT DB: QMap(("all", "xca@claudius/QPSQL7:xca")("dbname", "xca")("host", "claudius")("prefix", "")("type", "QPSQL7")("user", "xca"))
SPLIT DB: QMap(("all", "xca@claudius/QPSQL7:xca")("dbname", "xca")("host", "claudius")("prefix", "")("type", "QPSQL7")("user", "xca"))
SPLIT DB: QMap(("all", "xca@claudius/QPSQL7:xca")("dbname", "xca")("host", "claudius")("prefix", "")("type", "QPSQL7")("user", "xca"))
SPLIT DB: QMap(("all", "xca@claudius/QPSQL7:xca")("dbname", "xca")("host", "claudius")("prefix", "")("type", "QPSQL7")("user", "xca"))
Opening database: xca@claudius/QPSQL7:xca
Available Remote DB Drivers:  2
"QMYSQL3"
"QPSQL7"
SPLIT DB: QMap(("all", "xca@claudius/QPSQL7:xca")("dbname", "xca")("host", "claudius")("prefix", "")("type", "QPSQL7")("user", "xca"))
SPLIT DB: QMap(("all", "xca@claudius/QPSQL7:xca")("dbname", "xca")("host", "claudius")("prefix", "")("type", "QPSQL7")("user", "xca"))
SPLIT DB: QMap(("all", "xca@claudius/QPSQL7:xca")("dbname", "xca")("host", "claudius")("prefix", "")("type", "QPSQL7")("user", "xca"))
Available Remote DB Drivers:  2
"QMYSQL3"
"QPSQL7"
OpenDb::getDbType:  "QPSQL7"
"MW_database.cpp(40) Transaction: Begin Level 1, E:0 "
table_prefix: ""
"MW_database.cpp(52) Transaction: Commit Level 0, E:0 "
"QUERY: sql.cpp:76 (SELECT MAX(stamp) +1 from items) - Rows selected: -1"
"QUERY: sql.cpp:81 (UPDATE items SET stamp=? WHERE stamp=0[9]) - Rows affected: 0"
OpenDb::getDbType:  "QPSQL7"
OpenDb::getDbType:  "QPSQL7"
DB-DESC: "xca@claudius/QPSQL7:xca" "xca@claudius/QPSQL7:xca" QSqlError("", "", "")
"QUERY: db_base.cpp:117 (SELECT * FROM view_public_keys) - Rows selected: -1"
OpenSSL error (pki_evp.cpp:178) : error:140E0197:SSL routines:SSL_shutdown:shutdown while in init
Closing database: 
"settings.cpp(110) Transaction: Begin Level 1, E:0 "
"QUERY: settings.cpp:114 (UPDATE settings SET value=? WHERE key_=?[702,511,2, mw_geometry]) - Rows affected: 1"
"settings.cpp(123) Transaction: Commit Level 0, E:0 "
"QUERY: sql.cpp:76 (SELECT MAX(stamp) +1 from items) - Rows selected: -1"
"QUERY: sql.cpp:81 (UPDATE items SET stamp=? WHERE stamp=0[9]) - Rows affected: 0"
Empty filename passed to function
SPLIT DB: QMap(("all", "xca@claudius/QPSQL7:xca")("dbname", "xca")("host", "claudius")("prefix", "")("type", "QPSQL7")("user", "xca"))
```

Please let me know if you need any additional data.

**Comment by jmhertlein** [comment]
This actually only affects one user on the affected laptop. Changing to another user works. I'm closing this, I assume I've somehow hosed this user.

**Comment by jmhertlein** [comment]
Sorry, I figured out the issue and I think it does merit looking at.

I think the problem is that I had an expired certificate at ~/.postgresql/root.crt. The presence of this file is what triggers the bug. I don't know if the expired-ness matters, I didn't test that. But an empty file for root.crt does not trigger the bug.

I think, perhaps, the error message could be better. More specific about what exactly went wrong.

**Comment by chris2511** [comment]
This is a "nice" error:
XCA and the PostgreSQL driver use/share the same OpenSSL library and the same openssl-error-queue.
While trying to connect to the server, the postgres library runs into this error because of the expired certificate as you discovered. This is far away from XCA to manage. XCA only innocently issued a simple SELECT SQL statement.

XCA checks after many (almost all) OpenSSL crypto operations the OpenSSL error queue and reports any errors. This (pki_evp.cpp line 178) is a place where really no error was expected and especially no SSL error.

I could enclose the SQL call by OpenSSL error checks to report SQL-driver-SSL errors.
