### ISSUE TITLE
Latest XCA blocked by Windows Defender SmartScreen

### ISSUE THREAD

**Issue by Wernfried** [chris2511/xca#586]
I just wanted to update to latest version 2.7. I cannot start the program, it is blocked by Windows Defender SmartScreen.
Version 2.6 is running fine.

I would know how to disable the Defender SmartScreen on my computer, however then I may run into trouble with our IT Security department.

**Comment by Wernfried** [comment]
At least I found a workaround. Download the application from the [Microsoft Store](https://apps.microsoft.com/store/detail/xca/9N9K02V7XR1B?hl=en-us&gl=us). Application is installed in `C:\Program Files\WindowsApps\6575ChristianHohnstdt.xca_2.7.0.0_x64__y0rzgagnhdchr\VFS\ProgramFilesX64\xca` from there you can copy/move it to your preferred location.

I have no idea whether these versions have any difference.

**Comment by Wernfried** [comment]
Mystical SmartScreen Defender. It's not the first time I got such strange behavior,  see https://stackoverflow.com/questions/54891501/determine-why-a-program-is-blocked-by-windows-defender-smartscreen

**Comment by chris2511** [comment]
With my shiny new code signing certificate (See: Code signing for XCA releases #478) this issue should be gone

**Comment by Wernfried** [comment]
Latest version 2.9 is blocked again, despite it is signed. 
BTW, did you try to submit your tool at [Submit a file for malware analysis](https://www.microsoft.com/en-us/wdsi/filesubmission/)?
