### ISSUE TITLE
Failed to update the database schema to the current version

### ISSUE THREAD

**Issue by slr75git** [chris2511/xca#588]
Hello
I am on Windows 10.
I had a database created with version 2.4.0.
I upgraded 'xca' to version 2.7.0 and opened this database.
It was OK but I've noticed some slowdowns with the certificates part.
Then i downgraded back to version 2.4.0.
But when i tried to reopen the database i got this popup :
"Failed to update the database schema to the current version".
Does this mean that we can't switch between 2.x.x versions ?
I thought of doing a complete dump of the database but I'm losing all the comments on the objects.
How can i get the database back to the 2.4.0 schema ?
I hope i am as clear as possible.
Thank you

**Comment by chris2511** [comment]
You need to set the "schema" back to 7 in the settings table
and delete the takeys table.

You can use the following SQL command to downgrade the database:
`drop table takeys;update settings set value='7' where key_='schema'`
With the https://www.sqlite.org/2024/sqlite-tools-win-x64-3460100.zip
or with a GUI: https://sqlitebrowser.org/
