### ISSUE TITLE
Can not edit or add content in "X509v3 Subject Alternative Name"

### ISSUE THREAD

**Issue by RomelSan** [chris2511/xca#59]
In the Extensions tab.
Click Edit button for: "X509v3 Subject Alternative Name"
add an IP
and try to edit content.
Bug!

System: Windows 10 Pro x64 english.

**Comment by chris2511** [comment]
This is a duplicate of  #57 "SAN IP not working in 2.1.0" and fixed with commit 410142f358d31c10b4cc77cd050b935ef1590fc9
Workaround until next release: Edit the SAN directly in the input field without the edit button.
