### ISSUE TITLE
HTTPS_server template should include SAN / DNS extension entry

### ISSUE THREAD

**Issue by influenza** [chris2511/xca#6]
Several modern browsers require that a X.509 certificate include an X.509 v3 Subject Alternative Name DNS entry with all hostnames the certificate is valid issues for. It would be great if the built-in HTTPS_server template added a placeholder entry like, "DNS:your.server.name.here'.

Please point me at the definition of these included templates and I'll file a pull request.

Relevant template:
![2018-03-12-1234-23](https://user-images.githubusercontent.com/770755/37296667-06fdc3f4-25f2-11e8-90d4-0a2916810da5.png)

X.509 v3 extension applied by this template:
![2018-03-12-1234-31](https://user-images.githubusercontent.com/770755/37296677-102fdc96-25f2-11e8-8db3-6f15e31d3ab9.png)

Sample DNS Subject Alternative Name:
![2018-03-12-1236-01](https://user-images.githubusercontent.com/770755/37296692-1a844a74-25f2-11e8-91a3-68d7fb56f465.png)

**Comment by chris2511** [comment]
Hi Ron,
The temates are defined in the misc/ subdirectory.

Cheers
 
 Christian 

Am 12. März 2018 17:37:29 MEZ schrieb Ron Dahlgren <notifications@github.com>:
>Several modern browsers require that a X.509 certificate include an
>X.509 v3 Subject Alternative Name DNS entry with all hostnames the
>certificate is valid issues for. It would be great if the built-in
>HTTPS_server template added a placeholder entry like,
>"DNS:your.server.name.here'.
>
>Please point me at the definition of these include templates and I'll
>file a pull request.
>
>Relevant template:
>![2018-03-12-1234-23](https://user-images.githubusercontent.com/770755/37296667-06fdc3f4-25f2-11e8-90d4-0a2916810da5.png)
>
>
>X.509 v3 extension applied by this template:
>![2018-03-12-1234-31](https://user-images.githubusercontent.com/770755/37296677-102fdc96-25f2-11e8-8db3-6f15e31d3ab9.png)
>
>Sample DNS Subject Alternative Name:
>![2018-03-12-1236-01](https://user-images.githubusercontent.com/770755/37296692-1a844a74-25f2-11e8-91a3-68d7fb56f465.png)

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
