### ISSUE TITLE
Flatpak version dependency KDE 6.6 is End of Life

### ISSUE THREAD

**Issue by DarkSpir** [chris2511/xca#611]
I just updated my flatpak applications and got the notification that the runtime org.kde.Platform branch 6.6 is end-of-life but used by io.github.chris2511.xca.

Can you please check this and do a lib version bump if possible?

**Comment by ReversePolishLogic** [comment]
> [flathub/flathub#5521](https://github.com/flathub/flathub/pull/5521)

This was replaced by **de.hohnstaedt.xca**, which uses org.kde.Platform branch 6.7.
