### ISSUE TITLE
IP as Subject Alternative Name not working

### ISSUE THREAD

**Issue by erdnussflips** [chris2511/xca#62]
Hello,

when I add an entry of type IP to the SAN's and fill it with something like 127.0.0.1, after clicking outside the field, the field will be cleared.

Is that a bug?

My Environment:
- Windows 10 Pro 1803
- xca 2.1.0

Best regards
erdnussflips

**Comment by chris2511** [comment]
This is a duplicate of #57 "SAN IP not working in 2.1.0" and fixed with commit 410142f
Workaround until next release: Edit the SAN directly in the input field without the edit button.
