### ISSUE TITLE
error: missing binary operator before token "("  #if (QT_VERSION >= QT_VERSION_CHECK(5, 0, 0))

### ISSUE THREAD

**Issue by neatsdude** [chris2511/xca#63]
Hello Everyone,

I am facing issue while making the install file xca 2.1 

Sharing the output of the make file.

make
  UIC    [ui] ui_CaProperties.h
  UIC    [ui] ui_CertDetail.h
  UIC    [ui] ui_CertExtend.h
  UIC    [ui] ui_CrlDetail.h
  UIC    [ui] ui_ExportDialog.h
  UIC    [ui] ui_Help.h
  UIC    [ui] ui_ImportMulti.h
  UIC    [ui] ui_KeyDetail.h
  UIC    [ui] ui_MainWindow.h
  UIC    [ui] ui_NewCrl.h
  UIC    [ui] ui_NewKey.h
  UIC    [ui] ui_NewX509.h
  UIC    [ui] ui_Options.h
  UIC    [ui] ui_PwDialog.h
  UIC    [ui] ui_Revoke.h
  UIC    [ui] ui_SelectToken.h
  UIC    [ui] ui_XcaDialog.h
  UIC    [ui] ui_v3ext.h
  UIC    [ui] ui_SearchPkcs11.h
  UIC    [ui] ui_RevocationList.h
  UIC    [ui] ui_OidResolver.h
  UIC    [ui] ui_OpenDb.h
  UIC    [ui] ui_ItemProperties.h
  GEN    commithash.h
  MOC    [lib] moc_db_crl.cpp
  MOC    [lib] moc_db_key.cpp
  MOC    [lib] moc_db_temp.cpp
  MOC    [lib] moc_db_x509.cpp
  MOC    [lib] moc_db_x509req.cpp
  MOC    [lib] moc_db_x509super.cpp
  MOC    [lib] moc_db_base.cpp
  MOC    [lib] moc_db_token.cpp
  MOC    [lib] moc_pki_temp.cpp
  MOC    [lib] moc_pki_x509.cpp
  MOC    [lib] moc_pki_crl.cpp
  MOC    [lib] moc_pki_x509req.cpp
  MOC    [lib] moc_pki_key.cpp
  MOC    [lib] moc_pki_x509super.cpp
  MOC    [lib] moc_pki_pkcs12.cpp
  MOC    [lib] moc_pki_base.cpp
  MOC    [lib] moc_pki_multi.cpp
  MOC    [lib] moc_pki_evp.cpp
  MOC    [lib] moc_pki_scard.cpp
  MOC    [lib] moc_pass_info.cpp
  MOC    [lib] moc_pki_pkcs7.cpp
  MOC    [lib] moc_main.cpp
  DEP    [lib]
In file included from /home/cl-13/Downloads/xca-2.1.0/lib/exception.h:13:0,
                 from /home/cl-13/Downloads/xca-2.1.0/lib/pkcs11_lib.h:11,
                 from /home/cl-13/Downloads/xca-2.1.0/lib/pki_base.h:15,
                 from /home/cl-13/Downloads/xca-2.1.0/widgets/ExportDialog.h:12,
                 from db_x509.h:15,
                 from db_crl.h:11,
                 from db_crl.cpp:9:
/home/cl-13/Downloads/xca-2.1.0/lib/base.h:34:36: error: missing binary operator before token "("
 #if (QT_VERSION >= QT_VERSION_CHECK(5, 0, 0))

-------------[ CUT OFF duplicate error messages for readability :-) ] ------------

moc_main.cpp:13:2: error: #error "The header file 'main.h' doesn't include <QObject>."
 #error "The header file 'main.h' doesn't include <QObject>."
  ^~~~~
  CC     [lib] db_crl.o
In file included from db_crl.h:11:0,
                 from db_crl.cpp:9:
db_x509.h:12:10: fatal error: QListView: No such file or directory
 #include <QListView>
          ^~~~~~~~~~~
compilation terminated.
/home/cl-13/Downloads/xca-2.1.0/Rules.mak:30: recipe for target 'db_crl.o' failed
make[1]: *** [db_crl.o] Error 1
Makefile:77: recipe for target 'lib/.build-stamp' failed
make: *** [lib/.build-stamp] Error 2

I'll be glad if i get the solution.
As I have tried reinstalling the application as well the qt5 libraries.
Please help.

Thanks in advance.

Nitesh Dudhe

**Comment by chris2511** [comment]
It looks like the compiler does not find the QT library include files.
What does "./configure" say?
Did you also reinstall the "-dev" packages of QT

if you say "make xca" it prints the compile line like `g++ -Wall -Wextra -DXCA_PREFIX=\"/usr/local/share/xca\" -DETC=\"/usr/local/etc\" -DDOCDIR=\"/usr/local/share/doc/xca\" -g -O2  -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets ....`

Look whether the `/usr/include/x86_64-linux-gnu/qt5/QtWidgets` (or whatever path it is on your host) exists and contains a lot of .h files

**Comment by neatsdude** [comment]
Dear Chris2511,

Thanks for the reply,

this is the output for ./configure

./configure
configure:      ***************************************************
configure:      *   X Certificate and Key management 2.1.0
configure:      ***************************************************
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for strip... strip
checking for pkg-config... no
checking for OpenSSL... no
configure: WARNING: OpenSSL pkg-config failed, using fallback defaults ( -lcrypto )
checking for Qt5... no
checking for Qt4... no
configure: WARNING: Qt pkg-config failed, using fallback defaults ( -lQtCore -lQtGui )
checking for lrelease-qt... no
checking for lrelease... /usr/bin/lrelease
checking for lconvert-qt... no
checking for lconvert... /usr/bin/lconvert
checking for rcc-qt... no
checking for rcc... /usr/bin/rcc
checking for lt_dlopen in -lltdl... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking ltdl.h usability... yes
checking ltdl.h presence... yes
checking for ltdl.h... yes
Unable to execute a freshly compiled application, maybe you have to adjust your LD_LIBRARY_PATH or /etc/ld.so.conf
checking for GNU make... make
configure: A usable 'make' executable was found in /usr/bin/make
checking for linuxdoc... no
checking for sgml2html... no
configure: WARNING: 'linuxdoc' or 'sgml2html' not found, using pre-compiled documentation
configure: creating ./config.status
config.status: creating Local.mak
config.status: creating local.h
configure: creating ./config.status
config.status: creating Local.mak
config.status: creating misc/Info.plist
config.status: creating local.h
config.status: local.h is unchanged




As per the qt dev packages are concerned, I'm not able to find the appropriate package for Bionic Ubuntu 18.04.

Nitesh Dudhe

**Comment by chris2511** [comment]
Culprit is here:

`checking for pkg-config... no`
`checking for OpenSSL... no`
`checking for Qt5... no`

Please install the "pkg-config" package of your distribution. Maybe that helps to turn them all to yes.

**Comment by neatsdude** [comment]
Ohh....
I have installed "pkg-config" and now this is the new issue,
The output of make:
make
  GEN    commithash.h
  CC     [lib] db_crl.o
In file included from /usr/include/openssl/err.h:13:0,
                 from /home/cl-13/Downloads/xca-2.1.0/lib/pki_base.h:11,
                 from /home/cl-13/Downloads/xca-2.1.0/widgets/ExportDialog.h:12,
                 from db_x509.h:15,
                 from db_crl.h:11,
                 from db_crl.cpp:9:
/usr/include/openssl/e_os2.h:13:11: fatal error: openssl/opensslconf.h: No such file or directory
 # include <openssl/opensslconf.h>
           ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/cl-13/Downloads/xca-2.1.0/Rules.mak:30: recipe for target 'db_crl.o' failed
make[1]: *** [db_crl.o] Error 1
Makefile:77: recipe for target 'lib/.build-stamp' failed
make: *** [lib/.build-stamp] Error 2





As it shows that opensslconf.h present in openssl is not available.
Also I used openssl1.0 for it.

Nitesh Dudhe

**Comment by chris2511** [comment]
Does configure say at the end (versions may vary):

configure: The Versions of the used libraries are:
configure: Header:
configure: 	OpenSSL 1.0.2g  1 Mar 2016 0x1000207fL
configure: 	QT: 5.9.1
configure: Libraries:
configure: 	OpenSSL 1.0.2g  1 Mar 2016
configure: 	QT: 5.9.1
configure: ECC With RFC 5639 Brainpool curves enabled
checking for GNU make... make
configure: A usable 'make' executable was found in /usr/bin/make

**Comment by chris2511** [comment]
Your OS installation seems to be somehow damaged.
Did you try entering the error into your favorite search engine?
Please reopen if you still need help.
