### ISSUE TITLE
[Low Priority] Generating large DH params freezes UI

### ISSUE THREAD

**Issue by telmer6** [chris2511/xca#68]
Generating a large (2048, 4096) DH param freezes the XCA UI. The param is eventually generated, but given that you are displaying a progress bar, locking up the UI is misleading.

XCA 2.1.1
Windows 10 Edu v1803 b17134.254 
4GB RAM, 4 cores @ 3.7GHz

**Comment by 424778940z** [comment]
same problem here, 2048 will go through, 4096 seems never end

8700k 16g ram
win10 pro
xca 2.1.2

**Comment by 424778940z** [comment]
and is it possible to use multi core for calculate?
