### ISSUE TITLE
ocsp stapling

### ISSUE THREAD

**Issue by karlo1941** [chris2511/xca#72]
how to add "OCSP Must-Staple" feature to certificate?

it must be additional key like this:
1.3.6.1.5.5.7.1.24 = DER:30:03:02:01:05

**TLS Feature:**
status_request

or maybe must added to 
extendedKeyUsage=serverAuth,1.3.6.1.5.5.7.1.24

**X509v3 Extended Key Usage:**
TLS Web Server Authentication, TLS Feature

**Comment by chris2511** [comment]
According to RFC7633 and https://scotthelme.co.uk/ocsp-must-staple/

With OpenSSL < 1.1.0 use (also works with 1.1.0, just less readable):
  `1.3.6.1.5.5.7.1.24 = DER:30:03:02:01:05`
else
  `tlsfeature = status_request`
on the "Advanced" tab during certificate / CSR generation

Adding this as simple **OCSP must staple** checkbox to the XCA extensions sounds like a nice, reasonable feature.
