### ISSUE TITLE
Non-latin path in About dialog box

### ISSUE THREAD

**Issue by SY6502** [chris2511/xca#73]
![unicode](https://user-images.githubusercontent.com/35701909/46725432-d4a2f980-cc84-11e8-9a3c-e8a84a5ba3e1.png)

**Comment by chris2511** [comment]
Hello,

I was not able to reproduce the issue, yet.
Did you create that directory within XCA or with some other tool ?
What windows version do you use?

You could help me by opening a new database with empty password, create an XCA template and
store it into the location above. Verify that the working directory is displayed as crippled (Invalid UTF8) as above and send me the database to christian@hohnstaedt.de

Thanks

Christian

**Comment by SY6502** [comment]
I tried to create new database with non-latin characters in path name and they are displayed normally. I guess the problem comes from older XCA version (from 2015/2016) and the path is stored in XDB file by the old version.
