### ISSUE TITLE
Exiting XCA 2.1.1 corrupts database

### ISSUE THREAD

**Issue by TyraelTLK** [chris2511/xca#74]
Step to reproduce:
Run XCA
Open a database
Exit XCA

Run XCA
Open the previously used database

ERROR:

The following error occurred:
(7pki_evp[]:)
error:08068065:object identifier routines:OBJ_nid2sn:unknown nid
error:08066065:object identifier routines:OBJ_nid2ln:unknown nid
error:08068065:object identifier routines:OBJ_nid2sn:unknown nid
error:08066065:object identifier routines:OBJ_nid2ln:unknown nid
error:08068065:object identifier routines:OBJ_nid2sn:unknown nid
error:08066065:object identifier routines:OBJ_nid2ln:unknown nid
error:08068065:object identifier routines:OBJ_nid2sn:unknown nid
error:08066065:object identifier routines:OBJ_nid2ln:unknown nid
error:08068065:object identifier routines:OBJ_nid2sn:unknown nid
error:08066065:object identifier routines:OBJ_nid2ln:unknown nid
error:08068065:object identifier routines:OBJ_nid2sn:unknown nid
error:08066065:object identifier routines:OBJ_nid2ln:unknown nid
error:08068065:object identifier routines:OBJ_nid2sn:unknown nid
error:08066065:object identifier routines:OBJ_nid2ln:unknown nid

(pki_evp.cpp:178)

**Comment by argv-minus-one** [comment]
This bug was introduced in commit a8f54c8.

It isn't actually corrupting the database, just failing to read it. After clicking “OK” on the error dialog (*without* restarting XCA), try to open the same database again, and *then* it works.

**Comment by argv-minus-one** [comment]
Sorry it took me so long to get back to you. Yes, XCA 2.1.2 doesn't seem to have the problem. Thank you!
