### ISSUE TITLE
Checksum change for XCA 2.1.1 macOS release

### ISSUE THREAD

**Issue by g-a-c** [chris2511/xca#76]
Hi - the Homebrew Cask project seems to have an outdated checksum for the XCA 2.1.1 release DMG.

The expected checksum is `69692384d4239daf6e95b4d06bcf589eed33c829940a7d9ea74409a7fe937a01` however the current XCA 2.1.1 DMG download listed on your download page is `d376bba09657477a20b89b324154c7a76bd3360df37488153727f5d0861a857f`

So that the Cask project will accept a pull request to update this checksum without changing the version, could you please confirm publicly via this issue that the expected current checksum for XCA 2.1.1 is `d376bba09657477a20b89b324154c7a76bd3360df37488153727f5d0861a857f`?

Thanks.

**Comment by g-a-c** [comment]
This is a duplicate issue caused by GitHub wonkiness this morning - closing in favour of issue 77 which is linked to externally...

**Comment by chris2511** [comment]
Yes it is correct. Please also see: https://github.com/chris2511/xca/blob/master/misc/binary-hashes.json

Cheers
Christian 

Am 22. Oktober 2018 09:52:56 MESZ schrieb Gavin Chappell <notifications@github.com>:
>Hi - the Homebrew Cask project seems to have an outdated checksum for
>the XCA 2.1.1 release DMG.
>
>The expected checksum is
>`69692384d4239daf6e95b4d06bcf589eed33c829940a7d9ea74409a7fe937a01`
>however the current XCA 2.1.1 DMG download listed on your download page
>is `d376bba09657477a20b89b324154c7a76bd3360df37488153727f5d0861a857f`
>
>So that the Cask project will accept a pull request to update this
>checksum without changing the version, could you please confirm
>publicly via this issue that the expected current checksum for XCA
>2.1.1 is
>`d376bba09657477a20b89b324154c7a76bd3360df37488153727f5d0861a857f`?
>
>Thanks.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/chris2511/xca/issues/76

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
