### ISSUE TITLE
Checksum change for XCA 2.1.1 release

### ISSUE THREAD

**Issue by g-a-c** [chris2511/xca#77]
Hi - the Homebrew Cask project has `69692384d4239daf6e95b4d06bcf589eed33c829940a7d9ea74409a7fe937a01` recorded as their expected checksum for the XCA 2.1.1 DMG. Your download page now lists `d376bba09657477a20b89b324154c7a76bd3360df37488153727f5d0861a857f`.

Could you please confirm publicly via this issue that XCA 2.1.1 was re-released with a new checksum of `d376bba09657477a20b89b324154c7a76bd3360df37488153727f5d0861a857f` so that the Cask project will accept the pull request to update the checksum?

Thanks.

**Comment by chris2511** [comment]
Yes it is correct. Please also see: https://github.com/chris2511/xca/blob/master/misc/binary-hashes.json

Cheers
Christian

Am 22. Oktober 2018 10:49:55 MESZ schrieb Gavin Chappell <notifications@github.com>:
>Hi - the Homebrew Cask project has
>`69692384d4239daf6e95b4d06bcf589eed33c829940a7d9ea74409a7fe937a01`
>recorded as their expected checksum for the XCA 2.1.1 DMG. Your
>download page now lists
>`d376bba09657477a20b89b324154c7a76bd3360df37488153727f5d0861a857f`.
>
>Could you please confirm publicly via this issue that XCA 2.1.1 was
>re-released with a new checksum of
>`d376bba09657477a20b89b324154c7a76bd3360df37488153727f5d0861a857f` so
>that the Cask project will accept the pull request to update the
>checksum?
>
>Thanks.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/chris2511/xca/issues/77

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
