### ISSUE TITLE
Certificate with notAfter set to GeneralizedTime 9999-12-31 23:59:00 is shown as "invalid"

### ISSUE THREAD

**Issue by tuxmike** [chris2511/xca#80]
Hi,

I have an certificate which has set an notAfter value of GeneralizedTime 9999-12-31 23:59:00 UTC
(instead of the correct GeneralizedTime9999-12-31 23:59:59 UTC which is supposed to indicate no well-defined expiration date, according to rfc5280#section-4.1.2.5.2).
With GeneralizedTime 9999-12-31 23:59:00, the cert is shown as "invalid".
With GeneralizedTime 9999-12-31 23:59:59, the cert is shown as "valid" with "undefined" expiration date.
Why is 9999-12-31 23:59:00 displayed as invalid? It is still a valid time in the future, right?

Thx, tuxmike

**Comment by chris2511** [comment]
The XCA `asn1time` object is derived from QDateTime and able to convert from/to OpenSSL ASN1_TIME object.
QT < 5.11 considers years > 7999 as invalid. Nice discussion here:
https://bugreports.qt.io/browse/QTBUG-64401, especially https://bugreports.qt.io/browse/QTBUG-64401?focusedCommentId=378146&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-378146

Currently I do not intend to switch the pre-compiled MAC/W32 binaries to QT-5.11

P.S.: Cheers to Doc. E. Brown

**Comment by tuxmike** [comment]
Ok, thank you for your comment. Just curious, why OpenSSL shows a valid certificate, and XCA doesn't.
As quoted, would need fixing in QT, not in XCA. -> closed

PS: Thank you for this nice piece of Software, use it quite often.
