### ISSUE TITLE
Renew CA ROOT Cert

### ISSUE THREAD

**Issue by Lotusshaney** [chris2511/xca#82]
I can't find how to renew the ROOT CA Cert so that I can extend the date ?  Any idea how to do this as every time I have tried I cannot get existing server certs to be recognised with the new CA cert inplace.

**Comment by chris2511** [comment]
Transform -> Similar Certificate

Change the validity date.
Make sure to keep the DistinguishedName private key.
Done.
The issued certificates should automatically be moved to your new CA.

**Comment by chris2511** [comment]
Please leave this open as reminder. I will enable the "CA -> Renewal" context menu item
to also be enabled for the root CA.
