### ISSUE TITLE
Import ca-bundle

### ISSUE THREAD

**Issue by skonvols2k** [chris2511/xca#85]
Hi,
thanks for your app! During import of certificate, if the file contains more that one certificate (an example is file .ca-bundle, where root and intermediate are concat), only one certificate is imported.
Thanks

**Comment by chris2511** [comment]
Importing all PEM encoded items of possibly different type concatenated in one file
is possible by the menu item "Import -> PEM File"

**Comment by skonvols2k** [comment]
thanks
