### ISSUE TITLE
Show notice when caps lock is activated

### ISSUE THREAD

**Issue by farosch** [chris2511/xca#86]
It would be nice if xca would show an indication when caps lock is activated when typing the password to unlock a database. This is especially handy for keyboards that do not indicate caps lock via a LED.
Maybe something like this:
![xca_2018-11-30_09-19-15](https://user-images.githubusercontent.com/22905106/49277452-ed0fe300-f481-11e8-8085-b41d9f5344e1.png)

**Comment by chris2511** [comment]
There is no easy way to detect CapsLock operating-system independently.
Too much hassle for too little gain
