### ISSUE TITLE
[Feature request] Name Constraints (RFC5280 section 4.2.1.10)

### ISSUE THREAD

**Issue by jrb0001** [chris2511/xca#90]
Name constraints are useful to restrict a CA to only some defined domains, addresses and other namespaces. This is a really useful feature if you want or have to import some special purpose CA into your truststore but don't trust it enough to accept it for everything. It would be great if xca would allow to edit them through the UI.

**Comment by karlo1941** [comment]
Hi

You can use in Advanced Tab.
I some time research this feature, and now could explain how its works.

**Comment by jrb0001** [comment]
Yeah, that's what I did. But I still think having a real UI for it would be better.

**Comment by baddev1** [comment]
Can you please explain how it works in the Advanced Tab? Or is there already a how to?

**Comment by karlo1941** [comment]
yes, i can

svētd., 2021. g. 24. janv., plkst. 08:47 — lietotājs baddev1 (<
notifications@github.com>) rakstīja:

**Comment by alyandon** [comment]
I'd really appreciate a step-by-step guide on how to do this in the advanced tab even if the feature never gets baked into the UI.
