### ISSUE TITLE
[Feature Request] Default output folder

### ISSUE THREAD

**Issue by robsiera** [chris2511/xca#93]
Please consider to implement an extra Preference Option "Default Output folder".
This would be helpful when exporting to files.

**Comment by robsiera** [comment]
The same goes for a "default database location folder"

**Comment by robsiera** [comment]
That is not my experience.
When opening XCA, the "Open Database" always defaults to %USER%\Documents folder.
When Exporting, the path defaults to the folder of the XCA exe.
When Importing, the path defaults to the folder of the XCA exe.

I'm using the **portable** version.

**Comment by chris2511** [comment]
This is the intended behavior of the **portable** mode. Please see commit 00bd36f19bc86
If you want to move with XCA to any PC at any time, it makes no sense to remember paths on the PC.
If you don't, then installing XCA is a good idea to get those features as well as file-type assignments.

Maybe the Import/Export and Open Database folders should default to a sub-folder in the folder of the XCA exe in portable mode.

**Comment by robsiera** [comment]
Ok, I understand.
Yes, defaulting to a subfolder, eg Data, would already be a big improvement. User can create the subfolder he wants and can access them with one extra click.

**Comment by oxcelovel** [comment]
definitely not one extra click:

1st click on "..." button to open save as window
2nd click on data folder 
3rd click on server folder (I have 5 servers so I need separate them )
4th click on save button in "save as" window

and its only for single export, how much useless clicks
to export for 5-10 clients... 

UP for this feature. I use portable version 2.1.2 on external secure drive and keep
programs and files in separate directories.
