### ISSUE TITLE
Compiling v2.1.2 under macOS Mojave fails not finding libtool

### ISSUE THREAD

**Issue by lhaeger** [chris2511/xca#94]
I'm trying to compile xca from the xca-2.1.2.tar.gz package on my Mac and ./configure fails to recognize libltdl, which already has been installed via MacPorts. Here's the output:

xca $ ./configure
configure:      ***************************************************
configure:      *   X Certificate and Key management 2.1.2
configure:      ***************************************************
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for strip... strip
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
configure: Mac OSX detected
checking for pkg-config... /opt/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for OpenSSL... yes
checking for Qt5... yes
checking for lrelease-qt5... no
checking for lrelease... /opt/local/libexec/qt5/bin/lrelease
checking for lconvert-qt5... no
checking for lconvert... /opt/local/libexec/qt5/bin/lconvert
checking for rcc-qt5... no
checking for rcc... /opt/local/libexec/qt5/bin/rcc
checking for macdeployqt... /opt/local/libexec/qt5/bin/macdeployqt
checking for lt_dlopen in -lltdl... no
ERROR: Library 'ltdl' with symbol 'lt_dlopen' not found.
       Try installing the package 'libltdl-dev' or 'libtool'
I did install all dependencies via macports already, including openssl, qt5 and libtool:

xca $ port installed | egrep 'qt5|libtool|openssl'
  libtool @2.4.6_5 (active)
  openssl @1.0.2q_0 (active)
  qt5-qtbase @5.12.0_2+openssl (active)
  qt5-qtdeclarative @5.12.0_1 (active)
  qt5-qtmacextras @5.12.0_1 (active)
  qt5-qtmultimedia @5.12.0_1 (active)
  qt5-qtsvg @5.12.0_1 (active)
  qt5-qttools @5.12.0_1 (active)
  qt5-qttranslations @5.12.0_1 (active)

 xca $ find /opt/local -name *ltdl*
/opt/local/include/ltdl.h
/opt/local/include/libltdl
/opt/local/lib/libltdl.a
/opt/local/lib/libltdl.dylib
/opt/local/lib/libltdl.7.dylib
/opt/local/share/libtool/ltdl.h
/opt/local/share/libtool/ltdl.mk
/opt/local/share/libtool/ltdl.c
/opt/local/share/libtool/libltdl
/opt/local/share/aclocal/ltdl.m4

Obviously openssl and qt5 are found, but not so libtool. Any idea what I could try to fix this?

**Comment by chris2511** [comment]
Try:
export CFLAGS="-I/opt/local/include -L/opt/local/lib"

**Comment by lhaeger** [comment]
Unfortunately that does not make a difference at all. Exactly the same logs are produced. Any other suggestions? Could it be the check in configure does not work in macOS and fails despite libltdl being available?

**Comment by lhaeger** [comment]
Took a awhile to come back to this issue, but finally found out I have to set CPPFLAGS instead of CFLAGS for ./configure to succeed. Now make is producing a lot of warnings like this one:
```
clang: warning: -Xlinker -rpath: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Xlinker /opt/local/libexec/qt5/lib: 'linker' input unused [-Wunused-command-line-argument]
```
Could you let me know if they are critical or can be ignored?

**Comment by chris2511** [comment]
This messages are harmless and can be ignored.
Please close if issue is solved.

**Comment by lhaeger** [comment]
Thanks a lot!
