### ISSUE TITLE
Question about remote DB

### ISSUE THREAD

**Issue by ibanezgomez** [chris2511/xca#95]
Hi chris2511, first of all congratulate you about your nice proyect.

One question, I would like to use the xca with remote access by MySQL. I`m trying with the portable version of windows with version 2.1.2.

Can you tell me why the option of the remote database is empty?

**Comment by chris2511** [comment]
You need `sqldrivers\qsqlmysql.dll` and `libmysql.dll` from a regular installation put into the ZIP file
