### ISSUE TITLE
Can't not save Diffie Hellman (DH) key in database

### ISSUE THREAD

**Issue by mr-GreyWolf** [chris2511/xca#96]
Can't not save Diffie Hellman (DH) key dh2048.pem in database for use on OpenVPN server.

**Comment by chris2511** [comment]
Yes, there is no need to save it in the database.
See: https://hohnstaedt.de/xca-doc/xca-2.html#ss2.3

**Comment by mr-GreyWolf** [comment]
Please add the option for save Diffie Hellman (DH) key in database

**Comment by karlo1941** [comment]
agree
