### ISSUE TITLE
Can't use app on Mac: app from an unidentified developer

### ISSUE THREAD

**Issue by 1oglop1** [chris2511/xca#97]
My company mac is restricted to install only signed apps.
But I can install apps via `homebrew` so if you could make an `brew` installer or another alternative it would be great.

thank you!

**Comment by idcrook** [comment]
macOS 10.15 Catalina requires apps to be notarized (and therefore also signed).
latest `xca` (`2.1.2`) does not open in Catalina

**Comment by lhaeger** [comment]
> My company mac is restricted to install only signed apps.
> But I can install apps via `homebrew` so if you could make an `brew` installer or another alternative it would be great.

xca is available via [MacPorts](https://www.macports.org/install.php) and does not require  codesigning or notarization in that case, since MacPorts build the app from source on your machine.

`sudo port install xca`

**Comment by idcrook** [comment]
Thanks.  I was able to open `xca` on the GM Catalina that I upgraded to, and have been able to use since. Not sure if that is a quirk of having allowed it to open on earlier macOS release.

**Comment by chris2511** [comment]
`brew` and `MacPorts` are supported.

**Comment by idcrook** [comment]
`brew cask install xca`  (version 2.2.1 in upgrade) yesterday would not  allow me to open app in macOS Catalina, even with the Finder Right-click `Open` trick.  Only offered to move app to trash.

However after rebooting today, now the  Finder Right-click `Open` allows me to run `xca` again (in addition to moving to Trash). Not sure what is going on behind the scenes. Adding a note here in case it may provide a hint to others in the future.
